// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AuthForm from "./AuthForm.bs.js";
import * as TextField from "../ui/TextField.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

var loginButtonClasses = "rounded-2xl px-4 py-2 text-sm font-medium transition bg-white text-stone-950 shadow-sm";

var inactiveButtonClasses = "rounded-2xl px-4 py-2 text-sm font-medium transition text-stone-500";

function AuthCard(props) {
  var error = props.error;
  var isSubmitting = props.isSubmitting;
  var onFormChange = props.onFormChange;
  var form = props.form;
  var onModeChange = props.onModeChange;
  var isRegister = AuthForm.isRegisterMode(props.mode);
  return JsxRuntime.jsxs("section", {
              children: [
                JsxRuntime.jsx("p", {
                      children: "Wine",
                      className: "mb-3 font-mono text-xs uppercase tracking-[0.35em] text-stone-600"
                    }),
                JsxRuntime.jsx("h1", {
                      children: isRegister ? "Create your account" : "Welcome back",
                      className: "font-serif text-4xl leading-none tracking-[-0.04em] text-stone-950"
                    }),
                JsxRuntime.jsx("p", {
                      children: isRegister ? "Start your wine journal with a personal account." : "Sign in to continue to your wine journal.",
                      className: "mt-4 text-sm leading-6 text-stone-700"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("button", {
                              children: "Log in",
                              className: isRegister ? inactiveButtonClasses : loginButtonClasses,
                              type: "button",
                              onClick: (function (param) {
                                  onModeChange(AuthForm.loginMode);
                                })
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Sign up",
                              className: isRegister ? loginButtonClasses : inactiveButtonClasses,
                              type: "button",
                              onClick: (function (param) {
                                  onModeChange(AuthForm.registerMode);
                                })
                            })
                      ],
                      className: "mt-6 grid grid-cols-2 gap-2 rounded-2xl bg-stone-100 p-1"
                    }),
                JsxRuntime.jsxs("form", {
                      children: [
                        isRegister ? JsxRuntime.jsx(TextField.make, {
                                label: "Full name",
                                value: form.fullName,
                                onChange: (function (value) {
                                    onFormChange("fullName", value);
                                  }),
                                autoComplete: "name"
                              }) : null,
                        JsxRuntime.jsx(TextField.make, {
                              label: "Email",
                              value: form.email,
                              onChange: (function (value) {
                                  onFormChange("email", value);
                                }),
                              autoComplete: "email",
                              type_: "email"
                            }),
                        JsxRuntime.jsx(TextField.make, {
                              label: "Password",
                              value: form.password,
                              onChange: (function (value) {
                                  onFormChange("password", value);
                                }),
                              autoComplete: isRegister ? "new-password" : "current-password",
                              type_: "password"
                            }),
                        (error == null) ? null : JsxRuntime.jsx("div", {
                                children: error,
                                className: "rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700"
                              }),
                        JsxRuntime.jsx("button", {
                              children: isSubmitting ? "Working..." : (
                                  isRegister ? "Create account" : "Log in"
                                ),
                              className: "w-full rounded-2xl bg-stone-950 px-4 py-3 text-sm font-semibold text-white transition hover:bg-stone-800 disabled:cursor-wait disabled:bg-stone-400",
                              disabled: isSubmitting,
                              type: "submit"
                            })
                      ],
                      className: "mt-6 space-y-4",
                      onSubmit: props.onSubmit
                    })
              ],
              className: "w-full max-w-md rounded-[2rem] border border-stone-900/10 bg-white/80 p-8 shadow-[0_24px_80px_rgba(81,46,23,0.12)] backdrop-blur"
            });
}

var make = AuthCard;

export {
  loginButtonClasses ,
  inactiveButtonClasses ,
  make ,
}
/* AuthForm Not a pure module */
