// Generated by ReScript, PLEASE EDIT WITH CARE


function describeError(error) {
  var match = error.message;
  switch (match) {
    case "email_taken" :
        return "That email address is already registered.";
    case "invalid_credentials" :
        return "The email or password was not accepted.";
    case "invalid_email" :
        return "Enter a valid email address.";
    case "password_too_short" :
        return "Use a password with at least 8 characters.";
    default:
      return "Something went wrong. Try again.";
  }
}

function describeCollectionError() {
  return "Could not load your collections. Try refreshing.";
}

function describeCreateCollectionError(error) {
  var match = error.message;
  if (match === "invalid_collection_name") {
    return "Enter a name for the collection.";
  } else {
    return "Could not create the collection. Try again.";
  }
}

function describeInviteError(error) {
  var match = error.message;
  switch (match) {
    case "already_member" :
        return "That person already belongs to this collection.";
    case "forbidden" :
        return "Only collection owners can invite people.";
    case "invalid_email" :
        return "Enter a valid email address.";
    case "user_not_found" :
        return "That email does not match an existing account yet.";
    default:
      return "Could not send the invite. Try again.";
  }
}

function describeEntryError(error) {
  var match = error.message;
  switch (match) {
    case "forbidden" :
        return "You no longer have access to this collection.";
    case "invalid_consumed_at" :
        return "Enter when you drank the wine.";
    case "invalid_rating" :
        return "Rating must be a whole number from 1 to 5.";
    case "invalid_wine_name" :
        return "Enter a wine name.";
    case "invalid_wine_vintage" :
        return "Vintage must be a year between 1900 and 2100.";
    default:
      return "Could not save the entry. Try again.";
  }
}

function describeEntryHistoryError() {
  return "Could not load collection history. Try refreshing.";
}

export {
  describeError ,
  describeCollectionError ,
  describeCreateCollectionError ,
  describeInviteError ,
  describeEntryError ,
  describeEntryHistoryError ,
}
/* No side effect */
