// Generated by ReScript, PLEASE EDIT WITH CARE


function describeError(errors, error) {
  var match = error.message;
  switch (match) {
    case "email_taken" :
        return errors.authEmailTaken;
    case "invalid_credentials" :
        return errors.authInvalidCredentials;
    case "invalid_email" :
        return errors.authInvalidEmail;
    case "password_too_short" :
        return errors.authPasswordTooShort;
    default:
      return errors.authGeneric;
  }
}

function describeEntryError(errors, error) {
  var match = error.message;
  switch (match) {
    case "forbidden" :
        return errors.entryForbidden;
    case "invalid_consumed_at" :
        return errors.entryInvalidConsumedAt;
    case "invalid_rating" :
        return errors.entryInvalidRating;
    case "invalid_wine_name" :
        return errors.entryInvalidWineName;
    case "invalid_wine_vintage" :
        return errors.entryInvalidWineVintage;
    default:
      return errors.entryGeneric;
  }
}

function describeEntryHistoryError(errors) {
  return errors.entryHistoryGeneric;
}

function describeWineError(errors, error) {
  var match = error.message;
  switch (match) {
    case "forbidden" :
        return errors.wineForbidden;
    case "invalid_wine_name" :
        return errors.wineInvalidName;
    case "invalid_wine_vintage" :
        return errors.wineInvalidVintage;
    default:
      return errors.wineGeneric;
  }
}

export {
  describeError ,
  describeEntryError ,
  describeEntryHistoryError ,
  describeWineError ,
}
/* No side effect */
