// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AuthApi from "../api/AuthApi.bs.js";
import * as ApiClient from "../api/ApiClient.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Js_promise2 from "rescript/lib/es6/js_promise2.js";
import * as SessionStorage from "./SessionStorage.bs.js";
import * as ResponseDecoder from "../api/ResponseDecoder.bs.js";

function loadSessionToken() {
  return SessionStorage.loadSessionToken();
}

function restoreSession(sessionToken) {
  return Js_promise2.then(AuthApi.me(sessionToken), (function (response) {
                var user = Belt_Option.flatMap(ResponseDecoder.parse(response), ResponseDecoder.user);
                if (user !== undefined) {
                  return Promise.resolve({
                              sessionToken: sessionToken,
                              user: user
                            });
                } else {
                  return Promise.reject(ApiClient.invalidResponse());
                }
              }));
}

export {
  loadSessionToken ,
  restoreSession ,
}
/* AuthApi Not a pure module */
