// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function parse(raw) {
  var trimmed = raw.startsWith("#") ? raw.substr(1) : raw;
  var path = trimmed.startsWith("/") ? trimmed.substr(1) : trimmed;
  var segments = Belt_Array.keep(path.split("/"), (function (segment) {
          return segment !== "";
        }));
  var len = segments.length;
  if (len >= 6) {
    return "Home";
  }
  switch (len) {
    case 2 :
        var match = segments[0];
        if (match !== "wines") {
          return "Home";
        }
        var id = segments[1];
        if (id === "new") {
          return "NewWine";
        }
        var wineId = Belt_Int.fromString(id);
        if (wineId !== undefined) {
          return {
                  TAG: "Wine",
                  _0: wineId
                };
        } else {
          return "Home";
        }
    case 0 :
    case 1 :
    case 3 :
        return "Home";
    case 4 :
        var match$1 = segments[0];
        if (match$1 !== "wines") {
          return "Home";
        }
        var wine = segments[1];
        var match$2 = segments[2];
        if (match$2 !== "entries") {
          return "Home";
        }
        var match$3 = segments[3];
        if (match$3 !== "new") {
          return "Home";
        }
        var wineId$1 = Belt_Int.fromString(wine);
        if (wineId$1 !== undefined) {
          return {
                  TAG: "NewEntry",
                  _0: wineId$1
                };
        } else {
          return "Home";
        }
    case 5 :
        var match$4 = segments[0];
        if (match$4 !== "wines") {
          return "Home";
        }
        var wine$1 = segments[1];
        var match$5 = segments[2];
        if (match$5 !== "entries") {
          return "Home";
        }
        var entry = segments[3];
        var match$6 = segments[4];
        if (match$6 !== "edit") {
          return "Home";
        }
        var match$7 = Belt_Int.fromString(wine$1);
        var match$8 = Belt_Int.fromString(entry);
        if (match$7 !== undefined && match$8 !== undefined) {
          return {
                  TAG: "EditEntry",
                  _0: match$7,
                  _1: match$8
                };
        } else {
          return "Home";
        }
    
  }
}

function format(route) {
  if (typeof route !== "object") {
    if (route === "Home") {
      return "#/";
    } else {
      return "#/wines/new";
    }
  }
  switch (route.TAG) {
    case "Wine" :
        return "#/wines/" + String(route._0);
    case "NewEntry" :
        return "#/wines/" + String(route._0) + "/entries/new";
    case "EditEntry" :
        return "#/wines/" + String(route._0) + "/entries/" + String(route._1) + "/edit";
    
  }
}

function navigate(route) {
  globalThis.window.location.hash = format(route);
}

function useRoute() {
  var match = React.useState(function () {
        return parse(globalThis.window.location.hash);
      });
  var setCurrent = match[1];
  React.useEffect((function () {
          var handler = function () {
            setCurrent(function (param) {
                  return parse(globalThis.window.location.hash);
                });
          };
          globalThis.window.addEventListener("hashchange", handler);
          return (function () {
                    globalThis.window.removeEventListener("hashchange", handler);
                  });
        }), []);
  return match[0];
}

export {
  parse ,
  format ,
  navigate ,
  useRoute ,
}
/* react Not a pure module */
