// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ApiClient from "../api/ApiClient.bs.js";

function listWines(token, collectionId) {
  return ApiClient.request("/api/collections/" + String(collectionId) + "/wines", {
              headers: ApiClient.authHeaders(token, {})
            });
}

export {
  listWines ,
}
/* ApiClient Not a pure module */
