// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ApiClient from "../api/ApiClient.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function stringify(value) {
  return Belt_Option.getExn(JSON.stringify(value));
}

function listWines(token, collectionId) {
  return ApiClient.request("/api/collections/" + String(collectionId) + "/wines", {
              headers: ApiClient.authHeaders(token, {})
            });
}

function createWine(token, collectionId, producer, name, vintage, style, grape, region, country, param) {
  return ApiClient.request("/api/collections/" + String(collectionId) + "/wines", {
              method: "POST",
              headers: ApiClient.authHeaders(token, ApiClient.jsonHeaders),
              body: Belt_Option.getExn(JSON.stringify({
                        producer: producer,
                        name: name,
                        vintage: vintage,
                        style: style,
                        grape: grape,
                        region: region,
                        country: country
                      }))
            });
}

export {
  stringify ,
  listWines ,
  createWine ,
}
/* ApiClient Not a pure module */
