// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as EntryDetail from "../entries/EntryDetail.bs.js";
import * as EntryHistory from "../entries/EntryHistory.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function optionalDetailLine(label, value) {
  if (value !== undefined) {
    return JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("dt", {
                        children: label,
                        className: "text-xs font-medium uppercase tracking-[0.2em] text-stone-500"
                      }),
                  JsxRuntime.jsx("dd", {
                        children: value,
                        className: "mt-1 text-sm leading-6 text-stone-700"
                      })
                ]
              });
  } else {
    return null;
  }
}

function wineLabel(summary) {
  var producer = summary.wine.producer;
  if (producer !== undefined) {
    return producer + " " + summary.wine.name;
  } else {
    return summary.wine.name;
  }
}

function WineDetail(props) {
  var selectedWine = props.selectedWine;
  var selectedWineLabel = selectedWine !== undefined ? wineLabel(selectedWine) : "this wine";
  if (selectedWine !== undefined) {
    return JsxRuntime.jsxs("section", {
                children: [
                  JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsxs("div", {
                                children: [
                                  JsxRuntime.jsx("p", {
                                        children: "Wine detail",
                                        className: "text-xs font-medium uppercase tracking-[0.25em] text-stone-500"
                                      }),
                                  JsxRuntime.jsx("h3", {
                                        children: wineLabel(selectedWine),
                                        className: "mt-2 text-2xl font-semibold text-stone-950"
                                      })
                                ]
                              }),
                          JsxRuntime.jsxs("div", {
                                children: [
                                  JsxRuntime.jsx("p", {
                                        children: "Occasions",
                                        className: "text-xs font-medium uppercase tracking-[0.2em] text-stone-500"
                                      }),
                                  JsxRuntime.jsx("p", {
                                        children: String(selectedWine.entryCount),
                                        className: "mt-1 text-lg font-semibold text-stone-950"
                                      })
                                ],
                                className: "rounded-2xl border border-stone-200 bg-white px-4 py-3 text-right"
                              })
                        ],
                        className: "flex flex-col gap-4 md:flex-row md:items-start md:justify-between"
                      }),
                  JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsxs("section", {
                                children: [
                                  JsxRuntime.jsx("h4", {
                                        children: "Identity",
                                        className: "text-sm font-semibold uppercase tracking-[0.2em] text-stone-600"
                                      }),
                                  JsxRuntime.jsxs("dl", {
                                        children: [
                                          JsxRuntime.jsxs("div", {
                                                children: [
                                                  JsxRuntime.jsx("dt", {
                                                        children: "Name",
                                                        className: "text-xs font-medium uppercase tracking-[0.2em] text-stone-500"
                                                      }),
                                                  JsxRuntime.jsx("dd", {
                                                        children: selectedWine.wine.name,
                                                        className: "mt-1 text-sm leading-6 text-stone-700"
                                                      })
                                                ]
                                              }),
                                          optionalDetailLine("Producer", selectedWine.wine.producer),
                                          optionalDetailLine("Grape", selectedWine.wine.grape),
                                          optionalDetailLine("Vintage", Belt_Option.map(selectedWine.wine.vintage, (function (prim) {
                                                      return String(prim);
                                                    })))
                                        ],
                                        className: "mt-4 grid gap-4"
                                      })
                                ],
                                className: "rounded-2xl border border-stone-200 bg-white p-5"
                              }),
                          JsxRuntime.jsxs("section", {
                                children: [
                                  JsxRuntime.jsx("h4", {
                                        children: "Memory",
                                        className: "text-sm font-semibold uppercase tracking-[0.2em] text-stone-600"
                                      }),
                                  JsxRuntime.jsx("dl", {
                                        children: JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx("dt", {
                                                      children: "Most recent",
                                                      className: "text-xs font-medium uppercase tracking-[0.2em] text-stone-500"
                                                    }),
                                                JsxRuntime.jsx("dd", {
                                                      children: selectedWine.lastConsumedAt,
                                                      className: "mt-1 text-sm leading-6 text-stone-700"
                                                    })
                                              ]
                                            }),
                                        className: "mt-4 grid gap-4"
                                      })
                                ],
                                className: "rounded-2xl border border-stone-200 bg-white p-5"
                              })
                        ],
                        className: "mt-6 grid gap-6 md:grid-cols-2"
                      }),
                  JsxRuntime.jsx("div", {
                        children: JsxRuntime.jsx(EntryHistory.make, {
                              status: props.entryStatus,
                              title: "Occasions for " + selectedWineLabel,
                              idleMessage: "Select a wine to browse its recorded occasions.",
                              loadingMessage: "Loading occasions for " + selectedWineLabel + "...",
                              emptyMessage: "No occasions recorded yet for " + selectedWineLabel + ".",
                              selectedEntryId: props.selectedEntryId,
                              onSelectEntry: props.onSelectEntry
                            }),
                        className: "mt-6"
                      }),
                  JsxRuntime.jsx("div", {
                        children: JsxRuntime.jsx(EntryDetail.make, {
                              entry: props.selectedEntry,
                              onEdit: props.onEditEntry
                            }),
                        className: "mt-6"
                      })
                ],
                className: "rounded-[1.75rem] border border-stone-900/10 bg-stone-50/80 p-6"
              });
  } else {
    return JsxRuntime.jsxs("section", {
                children: [
                  JsxRuntime.jsx("h3", {
                        children: "Wine detail",
                        className: "text-lg font-semibold text-stone-950"
                      }),
                  JsxRuntime.jsx("p", {
                        children: "Select a wine to browse its identity, remembered occasions, and entry details.",
                        className: "mt-2 text-sm leading-6 text-stone-600"
                      })
                ],
                className: "rounded-[1.75rem] border border-dashed border-stone-300 bg-stone-50/80 p-6"
              });
  }
}

var make = WineDetail;

export {
  optionalDetailLine ,
  wineLabel ,
  make ,
}
/* EntryDetail Not a pure module */
