// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TextField from "../ui/TextField.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function WineComposer(props) {
  var onClose = props.onClose;
  var onSubmit = props.onSubmit;
  var onWineFormChange = props.onWineFormChange;
  var wineForm = props.wineForm;
  var message = wineForm.error;
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("section", {
                    children: [
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("p", {
                                            children: "Add wine",
                                            className: "text-xs font-medium uppercase tracking-[0.25em] text-stone-500"
                                          }),
                                      JsxRuntime.jsx("h3", {
                                            children: "Remember a wine",
                                            className: "mt-2 text-2xl font-semibold text-stone-950"
                                          })
                                    ]
                                  }),
                              JsxRuntime.jsx("button", {
                                    children: "Close",
                                    className: "rounded-2xl border border-stone-300 px-4 py-2 text-sm font-medium text-stone-700 transition hover:border-stone-500 hover:text-stone-950",
                                    type: "button",
                                    onClick: (function (param) {
                                        onClose();
                                      })
                                  })
                            ],
                            className: "flex items-start justify-between gap-4"
                          }),
                      JsxRuntime.jsx("p", {
                            children: "Add a bottle you want to remember now, then attach occasions later when they happen.",
                            className: "mt-3 max-w-xl text-sm leading-6 text-stone-600"
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx(TextField.make, {
                                    label: "Wine name",
                                    value: wineForm.wineName,
                                    onChange: (function (value) {
                                        onWineFormChange("wineName", value);
                                      }),
                                    autoComplete: "off"
                                  }),
                              JsxRuntime.jsx(TextField.make, {
                                    label: "Producer",
                                    value: wineForm.producer,
                                    onChange: (function (value) {
                                        onWineFormChange("producer", value);
                                      }),
                                    autoComplete: "organization"
                                  }),
                              JsxRuntime.jsx(TextField.make, {
                                    label: "Style",
                                    value: wineForm.style,
                                    onChange: (function (value) {
                                        onWineFormChange("style", value);
                                      }),
                                    autoComplete: "off"
                                  }),
                              JsxRuntime.jsx(TextField.make, {
                                    label: "Grape",
                                    value: wineForm.grape,
                                    onChange: (function (value) {
                                        onWineFormChange("grape", value);
                                      }),
                                    autoComplete: "off"
                                  }),
                              JsxRuntime.jsx(TextField.make, {
                                    label: "Region",
                                    value: wineForm.region,
                                    onChange: (function (value) {
                                        onWineFormChange("region", value);
                                      }),
                                    autoComplete: "off"
                                  }),
                              JsxRuntime.jsx(TextField.make, {
                                    label: "Country",
                                    value: wineForm.country,
                                    onChange: (function (value) {
                                        onWineFormChange("country", value);
                                      }),
                                    autoComplete: "country-name"
                                  }),
                              JsxRuntime.jsx(TextField.make, {
                                    label: "Vintage",
                                    value: wineForm.vintage,
                                    onChange: (function (value) {
                                        onWineFormChange("vintage", value);
                                      }),
                                    autoComplete: "off",
                                    type_: "number"
                                  })
                            ],
                            className: "mt-6 grid gap-4 md:grid-cols-2"
                          }),
                      JsxRuntime.jsx("div", {
                            children: JsxRuntime.jsx("button", {
                                  children: wineForm.isSubmitting ? "Saving..." : "Save wine",
                                  className: "rounded-2xl bg-stone-950 px-5 py-3 text-sm font-semibold text-white transition hover:bg-stone-800 disabled:cursor-wait disabled:bg-stone-400",
                                  disabled: wineForm.isSubmitting,
                                  type: "button",
                                  onClick: (function (param) {
                                      onSubmit();
                                    })
                                }),
                            className: "mt-6 flex justify-end"
                          }),
                      message !== undefined ? JsxRuntime.jsx("div", {
                              children: message,
                              className: "mt-4 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700"
                            }) : null
                    ],
                    className: "mx-auto w-full max-w-2xl rounded-[2rem] border border-stone-900/10 bg-white p-6 shadow-[0_24px_80px_rgba(81,46,23,0.2)] md:p-8"
                  }),
              className: "fixed inset-0 z-50 overflow-y-auto bg-stone-950/40 px-4 py-4 md:px-6 md:py-10"
            });
}

var make = WineComposer;

export {
  make ,
}
/* TextField Not a pure module */
