// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as JsxRuntime from "react/jsx-runtime";

function wineLabel(summary) {
  var producer = summary.wine.producer;
  if (producer !== undefined) {
    return producer + " " + summary.wine.name;
  } else {
    return summary.wine.name;
  }
}

function wineMeta(summary) {
  var segments = Belt_Array.keepMap([
        summary.wine.grape,
        Belt_Option.map(summary.wine.vintage, (function (prim) {
                return String(prim);
              })),
        String(summary.entryCount) + " entries"
      ], (function (value) {
          return value;
        }));
  return segments.join(" · ");
}

function WineList(props) {
  var onSelectWine = props.onSelectWine;
  var selectedWineId = props.selectedWineId;
  var status = props.status;
  if (typeof status !== "object") {
    if (status === "Idle") {
      return JsxRuntime.jsxs("section", {
                  children: [
                    JsxRuntime.jsx("h3", {
                          children: "Wines",
                          className: "text-lg font-semibold text-stone-950"
                        }),
                    JsxRuntime.jsx("p", {
                          children: "Select a collection to browse the wines you have logged there.",
                          className: "mt-2 text-sm leading-6 text-stone-600"
                        })
                  ],
                  className: "rounded-[1.75rem] border border-dashed border-stone-300 bg-stone-50/80 p-6"
                });
    } else {
      return JsxRuntime.jsxs("section", {
                  children: [
                    JsxRuntime.jsx("h3", {
                          children: "Wines",
                          className: "text-lg font-semibold text-stone-950"
                        }),
                    JsxRuntime.jsx("p", {
                          children: "Loading collection wines...",
                          className: "mt-2 text-sm text-stone-600"
                        })
                  ],
                  className: "rounded-[1.75rem] border border-stone-900/10 bg-stone-50/80 p-6"
                });
    }
  }
  if (status.TAG !== "Ready") {
    return JsxRuntime.jsxs("section", {
                children: [
                  JsxRuntime.jsx("h3", {
                        children: "Wines",
                        className: "text-lg font-semibold text-rose-900"
                      }),
                  JsxRuntime.jsx("p", {
                        children: status._0,
                        className: "mt-2 text-sm text-rose-700"
                      })
                ],
                className: "rounded-[1.75rem] border border-rose-200 bg-rose-50 p-6"
              });
  }
  var wines = status._0;
  if (wines.length === 0) {
    return JsxRuntime.jsxs("section", {
                children: [
                  JsxRuntime.jsx("h3", {
                        children: "Wines",
                        className: "text-lg font-semibold text-stone-950"
                      }),
                  JsxRuntime.jsx("p", {
                        children: "No wines yet. Add the first bottle you want to remember in this collection.",
                        className: "mt-2 text-sm leading-6 text-stone-600"
                      })
                ],
                className: "rounded-[1.75rem] border border-dashed border-stone-300 bg-stone-50/80 p-6"
              });
  } else {
    return JsxRuntime.jsxs("section", {
                children: [
                  JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsx("h3", {
                                children: "Wines",
                                className: "text-lg font-semibold text-stone-950"
                              }),
                          JsxRuntime.jsx("span", {
                                children: String(wines.length) + " wines",
                                className: "rounded-full border border-stone-300 px-3 py-1 text-xs font-medium uppercase tracking-[0.2em] text-stone-600"
                              })
                        ],
                        className: "flex items-center justify-between gap-4"
                      }),
                  JsxRuntime.jsx("ul", {
                        children: Belt_Array.map(wines, (function (summary) {
                                var isSelected = selectedWineId !== undefined ? summary.wine.id === selectedWineId : false;
                                return JsxRuntime.jsx("li", {
                                            children: JsxRuntime.jsx("button", {
                                                  children: JsxRuntime.jsxs("div", {
                                                        children: [
                                                          JsxRuntime.jsxs("div", {
                                                                children: [
                                                                  JsxRuntime.jsx("p", {
                                                                        children: wineLabel(summary),
                                                                        className: isSelected ? "text-base font-semibold text-white" : "text-base font-semibold text-stone-950"
                                                                      }),
                                                                  JsxRuntime.jsx("p", {
                                                                        children: wineMeta(summary),
                                                                        className: isSelected ? "mt-1 text-sm text-stone-200" : "mt-1 text-sm text-stone-600"
                                                                      })
                                                                ]
                                                              }),
                                                          JsxRuntime.jsx("p", {
                                                                children: summary.lastConsumedAt,
                                                                className: isSelected ? "text-xs font-medium uppercase tracking-[0.2em] text-stone-300" : "text-xs font-medium uppercase tracking-[0.2em] text-stone-500"
                                                              })
                                                        ],
                                                        className: "flex items-start justify-between gap-4"
                                                      }),
                                                  className: "block w-full text-left",
                                                  type: "button",
                                                  onClick: (function (param) {
                                                      onSelectWine(summary.wine.id);
                                                    })
                                                }),
                                            className: isSelected ? "rounded-2xl border border-stone-950 bg-stone-950 p-4 shadow-sm text-white" : "rounded-2xl border border-stone-200 bg-white p-4 shadow-sm"
                                          }, String(summary.wine.id));
                              })),
                        className: "mt-4 space-y-3"
                      })
                ],
                className: "rounded-[1.75rem] border border-stone-900/10 bg-stone-50/80 p-6"
              });
  }
}

var make = WineList;

export {
  wineLabel ,
  wineMeta ,
  make ,
}
/* react/jsx-runtime Not a pure module */
