// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TextField from "../ui/TextField.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function WineComposer(props) {
  var onSubmit = props.onSubmit;
  var onWineFormChange = props.onWineFormChange;
  var wineForm = props.wineForm;
  var message = wineForm.error;
  return JsxRuntime.jsxs("section", {
              children: [
                JsxRuntime.jsx("p", {
                      children: "Add a bottle you want to remember now, then attach occasions later when they happen.",
                      className: "text-sm leading-6 text-stone-600"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx(TextField.make, {
                              label: "Wine name",
                              value: wineForm.wineName,
                              onChange: (function (value) {
                                  onWineFormChange("wineName", value);
                                }),
                              autoComplete: "off"
                            }),
                        JsxRuntime.jsx(TextField.make, {
                              label: "Producer",
                              value: wineForm.producer,
                              onChange: (function (value) {
                                  onWineFormChange("producer", value);
                                }),
                              autoComplete: "organization"
                            }),
                        JsxRuntime.jsx(TextField.make, {
                              label: "Style",
                              value: wineForm.style,
                              onChange: (function (value) {
                                  onWineFormChange("style", value);
                                }),
                              autoComplete: "off"
                            }),
                        JsxRuntime.jsx(TextField.make, {
                              label: "Grape",
                              value: wineForm.grape,
                              onChange: (function (value) {
                                  onWineFormChange("grape", value);
                                }),
                              autoComplete: "off"
                            }),
                        JsxRuntime.jsx(TextField.make, {
                              label: "Region",
                              value: wineForm.region,
                              onChange: (function (value) {
                                  onWineFormChange("region", value);
                                }),
                              autoComplete: "off"
                            }),
                        JsxRuntime.jsx(TextField.make, {
                              label: "Country",
                              value: wineForm.country,
                              onChange: (function (value) {
                                  onWineFormChange("country", value);
                                }),
                              autoComplete: "country-name"
                            }),
                        JsxRuntime.jsx(TextField.make, {
                              label: "Vintage",
                              value: wineForm.vintage,
                              onChange: (function (value) {
                                  onWineFormChange("vintage", value);
                                }),
                              autoComplete: "off",
                              type_: "number"
                            })
                      ],
                      className: "mt-6 grid gap-4 md:grid-cols-2"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("button", {
                            children: wineForm.isSubmitting ? "Saving..." : "Save wine",
                            className: "rounded-2xl bg-stone-950 px-5 py-3 text-sm font-semibold text-white transition hover:bg-stone-800 disabled:cursor-wait disabled:bg-stone-400",
                            disabled: wineForm.isSubmitting,
                            type: "button",
                            onClick: (function (param) {
                                onSubmit();
                              })
                          }),
                      className: "mt-6 flex justify-end"
                    }),
                message !== undefined ? JsxRuntime.jsx("div", {
                        children: message,
                        className: "mt-4 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700"
                      }) : null
              ],
              className: "rounded-3xl border border-stone-900/10 bg-white p-6 shadow-[0_24px_80px_rgba(81,46,23,0.12)] md:p-8"
            });
}

var make = WineComposer;

export {
  make ,
}
/* TextField Not a pure module */
