// Generated by ReScript, PLEASE EDIT WITH CARE

import * as WineApi from "./WineApi.bs.js";
import * as ApiClient from "../api/ApiClient.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Js_promise2 from "rescript/lib/es6/js_promise2.js";
import * as ResponseDecoder from "../api/ResponseDecoder.bs.js";

function initialStatus() {
  return "Idle";
}

function loadingStatus() {
  return "Loading";
}

function readyStatus(wines) {
  return {
          TAG: "Ready",
          _0: wines
        };
}

function errorStatus(message) {
  return {
          TAG: "Error",
          _0: message
        };
}

function wines(status) {
  if (typeof status !== "object") {
    return [];
  } else if (status.TAG === "Ready") {
    return status._0;
  } else {
    return [];
  }
}

function isReady(status) {
  if (typeof status !== "object" || status.TAG !== "Ready") {
    return false;
  } else {
    return true;
  }
}

function listWines(token, collectionId) {
  return Js_promise2.then(WineApi.listWines(token, collectionId), (function (response) {
                var wines = Belt_Option.flatMap(ResponseDecoder.parse(response), ResponseDecoder.wineSummaries);
                if (wines !== undefined) {
                  return Promise.resolve(wines);
                } else {
                  return Promise.reject(ApiClient.invalidResponse());
                }
              }));
}

export {
  initialStatus ,
  loadingStatus ,
  readyStatus ,
  errorStatus ,
  wines ,
  isReady ,
  listWines ,
}
/* WineApi Not a pure module */
