// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$String from "rescript/lib/es6/string.js";
import * as WineApi from "./WineApi.bs.js";
import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as ApiClient from "../api/ApiClient.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Js_promise2 from "rescript/lib/es6/js_promise2.js";
import * as ResponseDecoder from "../api/ResponseDecoder.bs.js";

function updateForm(form, field, value) {
  switch (field) {
    case "country" :
        return {
                wineName: form.wineName,
                producer: form.producer,
                style: form.style,
                grape: form.grape,
                region: form.region,
                country: value,
                vintage: form.vintage,
                isSubmitting: form.isSubmitting,
                error: undefined
              };
    case "grape" :
        return {
                wineName: form.wineName,
                producer: form.producer,
                style: form.style,
                grape: value,
                region: form.region,
                country: form.country,
                vintage: form.vintage,
                isSubmitting: form.isSubmitting,
                error: undefined
              };
    case "producer" :
        return {
                wineName: form.wineName,
                producer: value,
                style: form.style,
                grape: form.grape,
                region: form.region,
                country: form.country,
                vintage: form.vintage,
                isSubmitting: form.isSubmitting,
                error: undefined
              };
    case "region" :
        return {
                wineName: form.wineName,
                producer: form.producer,
                style: form.style,
                grape: form.grape,
                region: value,
                country: form.country,
                vintage: form.vintage,
                isSubmitting: form.isSubmitting,
                error: undefined
              };
    case "style" :
        return {
                wineName: form.wineName,
                producer: form.producer,
                style: value,
                grape: form.grape,
                region: form.region,
                country: form.country,
                vintage: form.vintage,
                isSubmitting: form.isSubmitting,
                error: undefined
              };
    case "vintage" :
        return {
                wineName: form.wineName,
                producer: form.producer,
                style: form.style,
                grape: form.grape,
                region: form.region,
                country: form.country,
                vintage: value,
                isSubmitting: form.isSubmitting,
                error: undefined
              };
    case "wineName" :
        return {
                wineName: value,
                producer: form.producer,
                style: form.style,
                grape: form.grape,
                region: form.region,
                country: form.country,
                vintage: form.vintage,
                isSubmitting: form.isSubmitting,
                error: undefined
              };
    default:
      return form;
  }
}

function startSubmitting(form) {
  return {
          wineName: form.wineName,
          producer: form.producer,
          style: form.style,
          grape: form.grape,
          region: form.region,
          country: form.country,
          vintage: form.vintage,
          isSubmitting: true,
          error: undefined
        };
}

function failForm(form, message) {
  return {
          wineName: form.wineName,
          producer: form.producer,
          style: form.style,
          grape: form.grape,
          region: form.region,
          country: form.country,
          vintage: form.vintage,
          isSubmitting: false,
          error: message
        };
}

function stringOption(value) {
  var trimmed = $$String.trim(value);
  if (trimmed === "") {
    return ;
  } else {
    return trimmed;
  }
}

function intOption(value, errorCode) {
  var trimmed = $$String.trim(value);
  if (trimmed === "") {
    return Promise.resolve(undefined);
  }
  var number = Belt_Int.fromString(trimmed);
  if (number !== undefined) {
    return Promise.resolve(number);
  } else {
    return Promise.reject(new Error(errorCode));
  }
}

function createWine(token, collectionId, form) {
  return Js_promise2.then(intOption(form.vintage, "invalid_wine_vintage"), (function (vintage) {
                var producer = stringOption(form.producer);
                var style = stringOption(form.style);
                var grape = stringOption(form.grape);
                var region = stringOption(form.region);
                var country = stringOption(form.country);
                return Js_promise2.then(WineApi.createWine(token, collectionId, producer, form.wineName, vintage, style, grape, region, country, undefined), (function (response) {
                              var summary = Belt_Option.flatMap(ResponseDecoder.parse(response), ResponseDecoder.wineSummary);
                              if (summary !== undefined) {
                                return Promise.resolve(summary);
                              } else {
                                return Promise.reject(ApiClient.invalidResponse());
                              }
                            }));
              }));
}

var initialForm = {
  wineName: "",
  producer: "",
  style: "",
  grape: "",
  region: "",
  country: "",
  vintage: "",
  isSubmitting: false,
  error: undefined
};

export {
  initialForm ,
  updateForm ,
  startSubmitting ,
  failForm ,
  stringOption ,
  intOption ,
  createWine ,
}
/* WineApi Not a pure module */
