// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$String from "rescript/lib/es6/string.js";
import * as WineApi from "./WineApi.bs.js";
import * as ApiClient from "../api/ApiClient.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Js_promise2 from "rescript/lib/es6/js_promise2.js";
import * as ResponseDecoder from "../api/ResponseDecoder.bs.js";

function initialStatus() {
  return "Idle";
}

function loadingStatus() {
  return "Loading";
}

function readyStatus(wines) {
  return {
          TAG: "Ready",
          _0: wines
        };
}

function errorStatus(message) {
  return {
          TAG: "Error",
          _0: message
        };
}

function wines(status) {
  if (typeof status !== "object") {
    return [];
  } else if (status.TAG === "Ready") {
    return status._0;
  } else {
    return [];
  }
}

function isReady(status) {
  if (typeof status !== "object" || status.TAG !== "Ready") {
    return false;
  } else {
    return true;
  }
}

function searchableText(summary) {
  return Belt_Array.keepMap([
                  summary.wine.name,
                  summary.wine.producer,
                  summary.wine.grape,
                  Belt_Option.map(summary.wine.vintage, (function (prim) {
                          return String(prim);
                        }))
                ], (function (value) {
                    return value;
                  })).join(" ").toLowerCase();
}

function matchesOccasionFilter(summary, occasionFilter) {
  switch (occasionFilter) {
    case "All" :
        return true;
    case "WithOccasions" :
        return summary.entryCount > 0;
    case "WithoutOccasions" :
        return summary.entryCount === 0;
    
  }
}

function filterWines(wines, query, occasionFilter) {
  var normalizedQuery = $$String.trim(query).toLowerCase();
  return Belt_Array.keep(wines, (function (summary) {
                var matchesQuery = normalizedQuery === "" ? true : searchableText(summary).includes(normalizedQuery);
                if (matchesQuery) {
                  return matchesOccasionFilter(summary, occasionFilter);
                } else {
                  return false;
                }
              }));
}

function filterStatus(status, query, occasionFilter) {
  if (typeof status !== "object") {
    if (status === "Idle") {
      return "Idle";
    } else {
      return "Loading";
    }
  } else if (status.TAG === "Ready") {
    return {
            TAG: "Ready",
            _0: filterWines(status._0, query, occasionFilter)
          };
  } else {
    return {
            TAG: "Error",
            _0: status._0
          };
  }
}

function listWines(token, collectionId) {
  return Js_promise2.then(WineApi.listWines(token, collectionId), (function (response) {
                var wines = Belt_Option.flatMap(ResponseDecoder.parse(response), ResponseDecoder.wineSummaries);
                if (wines !== undefined) {
                  return Promise.resolve(wines);
                } else {
                  return Promise.reject(ApiClient.invalidResponse());
                }
              }));
}

var initialOccasionFilter = "All";

export {
  initialStatus ,
  loadingStatus ,
  readyStatus ,
  errorStatus ,
  initialOccasionFilter ,
  wines ,
  isReady ,
  searchableText ,
  matchesOccasionFilter ,
  filterWines ,
  filterStatus ,
  listWines ,
}
/* WineApi Not a pure module */
