// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$String from "rescript/lib/es6/string.js";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Js_promise2 from "rescript/lib/es6/js_promise2.js";

var headers = {};

headers["content-type"] = "application/json";

function defaultApiBaseUrl() {
  var currentLocation = globalThis.location;
  if (currentLocation == null) {
    return "http://127.0.0.1:3000";
  }
  var currentHostname = currentLocation.hostname;
  var host = currentHostname === "frontend" ? "backend" : currentHostname;
  return currentLocation.protocol + "//" + host + ":3000";
}

var value = Belt_Option.map(Caml_option.nullable_to_opt(import.meta.env.VITE_API_BASE_URL), $$String.trim);

var apiBaseUrl = value !== undefined && value !== "" ? value : defaultApiBaseUrl();

function copyHeaders(headers) {
  var nextHeaders = {};
  Belt_Array.forEach(Js_dict.entries(headers), (function (param) {
          nextHeaders[param[0]] = param[1];
        }));
  return nextHeaders;
}

function invalidResponse() {
  return new Error("invalid_response");
}

function authHeaders(token, extraHeaders) {
  var headers = copyHeaders(extraHeaders);
  headers["authorization"] = "Bearer " + token;
  return headers;
}

function extractError(body) {
  try {
    var parsed = Js_json.decodeObject(JSON.parse(body));
    if (parsed === undefined) {
      return "request_failed";
    }
    var value = Js_dict.get(parsed, "error");
    if (value === undefined) {
      return "request_failed";
    }
    var error = Js_json.decodeString(value);
    if (error !== undefined) {
      return error;
    } else {
      return "request_failed";
    }
  }
  catch (exn){
    return "request_failed";
  }
}

function request(path, options) {
  return Js_promise2.then(fetch(apiBaseUrl + path, options), (function (response) {
                return Js_promise2.then(response.text(), (function (body) {
                              if (response.ok) {
                                return Promise.resolve(body);
                              } else {
                                return Promise.reject(new Error(extractError(body)));
                              }
                            }));
              }));
}

var jsonHeaders = headers;

export {
  jsonHeaders ,
  defaultApiBaseUrl ,
  apiBaseUrl ,
  copyHeaders ,
  invalidResponse ,
  authHeaders ,
  extractError ,
  request ,
}
/*  Not a pure module */
