// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ApiClient from "./ApiClient.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function stringify(value) {
  return Belt_Option.getExn(JSON.stringify(value));
}

function register(email, fullName, password) {
  return ApiClient.request("/api/auth/register", {
              method: "POST",
              headers: ApiClient.jsonHeaders,
              body: Belt_Option.getExn(JSON.stringify({
                        email: email,
                        full_name: fullName,
                        password: password
                      }))
            });
}

function login(email, password) {
  return ApiClient.request("/api/auth/login", {
              method: "POST",
              headers: ApiClient.jsonHeaders,
              body: Belt_Option.getExn(JSON.stringify({
                        email: email,
                        password: password
                      }))
            });
}

function me(token) {
  return ApiClient.request("/api/me", {
              headers: ApiClient.authHeaders(token, {})
            });
}

export {
  stringify ,
  register ,
  login ,
  me ,
}
/* ApiClient Not a pure module */
