// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ApiClient from "./ApiClient.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function stringify(value) {
  return Belt_Option.getExn(JSON.stringify(value));
}

function listCollections(token) {
  return ApiClient.request("/api/collections", {
              headers: ApiClient.authHeaders(token, {})
            });
}

function createCollection(token, name) {
  return ApiClient.request("/api/collections", {
              method: "POST",
              headers: ApiClient.authHeaders(token, ApiClient.jsonHeaders),
              body: Belt_Option.getExn(JSON.stringify({
                        name: name
                      }))
            });
}

export {
  stringify ,
  listCollections ,
  createCollection ,
}
/* ApiClient Not a pure module */
