// Generated by ReScript, PLEASE EDIT WITH CARE

import * as WineState from "../wines/WineState.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as I18nContext from "../i18n/I18nContext.bs.js";
import * as EntryComposer from "../entries/EntryComposer.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function EntryComposerScreen(props) {
  var onClose = props.onClose;
  var mode = props.mode;
  var id = mode._0;
  var selectedWine = Belt_Array.getBy(WineState.wines(props.wineStatus), (function (summary) {
          return summary.wine.id === id;
        }));
  var composerMode;
  composerMode = mode.TAG === "New" ? "Create" : "Edit";
  var t = I18nContext.useT();
  var title;
  title = mode.TAG === "New" ? t.entryComposerNewTitle : t.entryComposerEditTitle;
  return JsxRuntime.jsxs("section", {
              children: [
                JsxRuntime.jsxs("header", {
                      children: [
                        JsxRuntime.jsx("button", {
                              children: "‹",
                              "aria-label": t.entryComposerCancelAriaLabel,
                              className: "flex h-10 w-10 items-center justify-center rounded-full border border-stone-300 text-stone-700",
                              type: "button",
                              onClick: (function (param) {
                                  onClose();
                                })
                            }),
                        JsxRuntime.jsx("h2", {
                              children: title,
                              className: "flex-1 font-serif text-xl tracking-tight text-stone-950"
                            })
                      ],
                      className: "mb-4 flex items-center gap-3"
                    }),
                JsxRuntime.jsx(EntryComposer.make, {
                      mode: composerMode,
                      entryForm: props.entryForm,
                      selectedWine: selectedWine,
                      onEntryFormChange: props.onEntryFormChange,
                      onUseSelectedWine: props.onUseSelectedWineForEntry,
                      onUseNewWine: props.onUseNewWineForEntry,
                      onSubmit: props.onSubmit
                    })
              ],
              className: "w-full max-w-xl"
            });
}

var make = EntryComposerScreen;

export {
  make ,
}
/* WineState Not a pure module */
