// Generated by ReScript, PLEASE EDIT WITH CARE

import * as WineList from "../wines/WineList.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function WineListScreen(props) {
  return JsxRuntime.jsx(WineList.make, {
              status: props.wineStatus,
              wineQuery: props.wineQuery,
              occasionFilter: props.wineOccasionFilter,
              totalWineCount: props.totalWineCount,
              selectedWineId: props.selectedWineId,
              onSelectWine: props.onSelectWine,
              onSelectOccasionFilter: props.onSelectOccasionFilter,
              onWineQueryChange: props.onWineQueryChange
            });
}

var make = WineListScreen;

export {
  make ,
}
/* WineList Not a pure module */
