// Generated by ReScript, PLEASE EDIT WITH CARE

import * as WineState from "../wines/WineState.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as EntryState from "../entries/EntryState.bs.js";
import * as WineDetail from "../wines/WineDetail.bs.js";
import * as I18nContext from "../i18n/I18nContext.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function WineDetailScreen(props) {
  var onBack = props.onBack;
  var onAddEntry = props.onAddEntry;
  var entryStatus = props.entryStatus;
  var wineId = props.wineId;
  var t = I18nContext.useT();
  var onSelectEntry = function (param) {
    
  };
  var selectedWine = Belt_Array.getBy(WineState.wines(props.wineStatus), (function (summary) {
          return summary.wine.id === wineId;
        }));
  var filteredEntries = selectedWine !== undefined ? Belt_Array.keep(EntryState.entries(entryStatus), (function (entry) {
            return entry.wine.id === wineId;
          })) : [];
  var scopedEntryStatus;
  scopedEntryStatus = typeof entryStatus !== "object" ? (
      entryStatus === "Idle" ? "Idle" : "Loading"
    ) : (
      entryStatus.TAG === "Ready" ? ({
            TAG: "Ready",
            _0: filteredEntries
          }) : ({
            TAG: "Error",
            _0: entryStatus._0
          })
    );
  var tmp;
  if (selectedWine !== undefined) {
    var producer = selectedWine.wine.producer;
    tmp = producer !== undefined ? producer + " " + selectedWine.wine.name : selectedWine.wine.name;
  } else {
    tmp = t.wineDetailDefaultTitle;
  }
  return JsxRuntime.jsxs("section", {
              children: [
                JsxRuntime.jsxs("header", {
                      children: [
                        JsxRuntime.jsx("button", {
                              children: "‹",
                              "aria-label": t.wineDetailBackAriaLabel,
                              className: "flex h-10 w-10 items-center justify-center rounded-full border border-stone-300 text-stone-700",
                              type: "button",
                              onClick: (function (param) {
                                  onBack();
                                })
                            }),
                        JsxRuntime.jsx("h2", {
                              children: tmp,
                              className: "flex-1 truncate font-serif text-xl tracking-tight text-stone-950"
                            }),
                        JsxRuntime.jsx("button", {
                              children: t.wineDetailAddOccasion,
                              className: "rounded-full border border-stone-300 px-3 py-1 text-xs font-medium text-stone-700",
                              type: "button",
                              onClick: (function (param) {
                                  onAddEntry();
                                })
                            })
                      ],
                      className: "mb-4 flex items-center gap-3"
                    }),
                JsxRuntime.jsx(WineDetail.make, {
                      selectedWine: selectedWine,
                      entryStatus: scopedEntryStatus,
                      selectedEntry: undefined,
                      selectedEntryId: undefined,
                      onSelectEntry: onSelectEntry,
                      onEditEntry: props.onEditEntry
                    })
              ],
              className: "w-full max-w-3xl"
            });
}

var make = WineDetailScreen;

export {
  make ,
}
/* WineState Not a pure module */
