// Generated by ReScript, PLEASE EDIT WITH CARE

import * as WineComposer from "../wines/WineComposer.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function WineComposerScreen(props) {
  var onClose = props.onClose;
  return JsxRuntime.jsxs("section", {
              children: [
                JsxRuntime.jsxs("header", {
                      children: [
                        JsxRuntime.jsx("button", {
                              children: "‹",
                              "aria-label": "Cancel",
                              className: "flex h-10 w-10 items-center justify-center rounded-full border border-stone-300 text-stone-700",
                              type: "button",
                              onClick: (function (param) {
                                  onClose();
                                })
                            }),
                        JsxRuntime.jsx("h2", {
                              children: "New wine",
                              className: "flex-1 font-serif text-xl tracking-tight text-stone-950"
                            })
                      ],
                      className: "mb-4 flex items-center gap-3"
                    }),
                JsxRuntime.jsx(WineComposer.make, {
                      mode: "Create",
                      wineForm: props.wineForm,
                      onWineFormChange: props.onWineFormChange,
                      onSubmit: props.onSubmit,
                      onClose: onClose
                    })
              ],
              className: "w-full max-w-xl"
            });
}

var make = WineComposerScreen;

export {
  make ,
}
/* WineComposer Not a pure module */
