// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$String from "rescript/lib/es6/string.js";
import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as EntryApi from "./EntryApi.bs.js";
import * as ApiClient from "../api/ApiClient.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Js_promise2 from "rescript/lib/es6/js_promise2.js";
import * as ResponseDecoder from "../api/ResponseDecoder.bs.js";

function initialStatus() {
  return "Idle";
}

function loadingStatus() {
  return "Loading";
}

function emptyStatus() {
  return {
          TAG: "Ready",
          _0: []
        };
}

function readyStatus(entries) {
  return {
          TAG: "Ready",
          _0: entries
        };
}

function errorStatus(message) {
  return {
          TAG: "Error",
          _0: message
        };
}

function padTwo(value) {
  var text = String(value);
  if (value < 10) {
    return "0" + text;
  } else {
    return text;
  }
}

function todayDateString() {
  var now = new Date();
  return String(now.getFullYear()) + "-" + padTwo(now.getMonth() + 1 | 0) + "-" + padTwo(now.getDate());
}

function updateForm(form, field, value) {
  switch (field) {
    case "consumedAt" :
        var tmp = value === "" ? undefined : value;
        return {
                dateMode: form.dateMode,
                consumedAt: tmp,
                venueName: form.venueName,
                locationText: form.locationText,
                pairingNotes: form.pairingNotes,
                tastingNotes: form.tastingNotes,
                rating: form.rating,
                isSubmitting: form.isSubmitting,
                error: undefined,
                success: undefined
              };
    case "locationText" :
        return {
                dateMode: form.dateMode,
                consumedAt: form.consumedAt,
                venueName: form.venueName,
                locationText: value,
                pairingNotes: form.pairingNotes,
                tastingNotes: form.tastingNotes,
                rating: form.rating,
                isSubmitting: form.isSubmitting,
                error: undefined,
                success: undefined
              };
    case "pairingNotes" :
        return {
                dateMode: form.dateMode,
                consumedAt: form.consumedAt,
                venueName: form.venueName,
                locationText: form.locationText,
                pairingNotes: value,
                tastingNotes: form.tastingNotes,
                rating: form.rating,
                isSubmitting: form.isSubmitting,
                error: undefined,
                success: undefined
              };
    case "rating" :
        return {
                dateMode: form.dateMode,
                consumedAt: form.consumedAt,
                venueName: form.venueName,
                locationText: form.locationText,
                pairingNotes: form.pairingNotes,
                tastingNotes: form.tastingNotes,
                rating: value,
                isSubmitting: form.isSubmitting,
                error: undefined,
                success: undefined
              };
    case "tastingNotes" :
        return {
                dateMode: form.dateMode,
                consumedAt: form.consumedAt,
                venueName: form.venueName,
                locationText: form.locationText,
                pairingNotes: form.pairingNotes,
                tastingNotes: value,
                rating: form.rating,
                isSubmitting: form.isSubmitting,
                error: undefined,
                success: undefined
              };
    case "venueName" :
        return {
                dateMode: form.dateMode,
                consumedAt: form.consumedAt,
                venueName: value,
                locationText: form.locationText,
                pairingNotes: form.pairingNotes,
                tastingNotes: form.tastingNotes,
                rating: form.rating,
                isSubmitting: form.isSubmitting,
                error: undefined,
                success: undefined
              };
    default:
      return form;
  }
}

function toggleDateMode(form, enabled) {
  if (!enabled) {
    return {
            dateMode: false,
            consumedAt: undefined,
            venueName: form.venueName,
            locationText: form.locationText,
            pairingNotes: form.pairingNotes,
            tastingNotes: form.tastingNotes,
            rating: form.rating,
            isSubmitting: form.isSubmitting,
            error: undefined,
            success: undefined
          };
  }
  var existing = form.consumedAt;
  return {
          dateMode: true,
          consumedAt: existing !== undefined ? existing : todayDateString(),
          venueName: form.venueName,
          locationText: form.locationText,
          pairingNotes: form.pairingNotes,
          tastingNotes: form.tastingNotes,
          rating: form.rating,
          isSubmitting: form.isSubmitting,
          error: undefined,
          success: undefined
        };
}

function startSubmitting(form) {
  return {
          dateMode: form.dateMode,
          consumedAt: form.consumedAt,
          venueName: form.venueName,
          locationText: form.locationText,
          pairingNotes: form.pairingNotes,
          tastingNotes: form.tastingNotes,
          rating: form.rating,
          isSubmitting: true,
          error: undefined,
          success: undefined
        };
}

function failForm(form, message) {
  return {
          dateMode: form.dateMode,
          consumedAt: form.consumedAt,
          venueName: form.venueName,
          locationText: form.locationText,
          pairingNotes: form.pairingNotes,
          tastingNotes: form.tastingNotes,
          rating: form.rating,
          isSubmitting: false,
          error: message,
          success: undefined
        };
}

function succeedForm() {
  return {
          dateMode: false,
          consumedAt: undefined,
          venueName: "",
          locationText: "",
          pairingNotes: "",
          tastingNotes: "",
          rating: "",
          isSubmitting: false,
          error: undefined,
          success: "Entry saved."
        };
}

function formFromEntry(entry) {
  return {
          dateMode: Belt_Option.isSome(entry.consumedAt),
          consumedAt: entry.consumedAt,
          venueName: Belt_Option.getWithDefault(entry.venueName, ""),
          locationText: Belt_Option.getWithDefault(entry.locationText, ""),
          pairingNotes: Belt_Option.getWithDefault(entry.pairingNotes, ""),
          tastingNotes: Belt_Option.getWithDefault(entry.tastingNotes, ""),
          rating: Belt_Option.getWithDefault(Belt_Option.map(entry.rating, (function (prim) {
                      return String(prim);
                    })), ""),
          isSubmitting: false,
          error: undefined,
          success: undefined
        };
}

function entries(status) {
  if (typeof status !== "object") {
    return [];
  } else if (status.TAG === "Ready") {
    return status._0;
  } else {
    return [];
  }
}

function appendEntry(entries, entry) {
  return Belt_Array.concat([entry], entries);
}

function replaceEntry(entries, nextEntry) {
  return Belt_Array.map(entries, (function (entry) {
                if (entry.id === nextEntry.id) {
                  return nextEntry;
                } else {
                  return entry;
                }
              }));
}

function isReady(status) {
  if (typeof status !== "object" || status.TAG !== "Ready") {
    return false;
  } else {
    return true;
  }
}

function stringOption(value) {
  var trimmed = $$String.trim(value);
  if (trimmed === "") {
    return ;
  } else {
    return trimmed;
  }
}

function intOption(value, errorCode) {
  var trimmed = $$String.trim(value);
  if (trimmed === "") {
    return Promise.resolve(undefined);
  }
  var number = Belt_Int.fromString(trimmed);
  if (number !== undefined) {
    return Promise.resolve(number);
  } else {
    return Promise.reject(new Error(errorCode));
  }
}

function consumedAtForSubmit(form) {
  if (!form.dateMode) {
    return ;
  }
  var date = form.consumedAt;
  if (date !== undefined && $$String.trim(date) !== "") {
    return $$String.trim(date);
  }
  
}

function listEntries(token, collectionId) {
  return Js_promise2.then(EntryApi.listEntries(token, collectionId), (function (response) {
                var entries = Belt_Option.flatMap(ResponseDecoder.parse(response), ResponseDecoder.entries);
                if (entries !== undefined) {
                  return Promise.resolve(entries);
                } else {
                  return Promise.reject(ApiClient.invalidResponse());
                }
              }));
}

function createEntry(token, collectionId, wine, form) {
  return Js_promise2.then(intOption(form.rating, "invalid_rating"), (function (rating) {
                var consumedAt = consumedAtForSubmit(form);
                var venueName = stringOption(form.venueName);
                var locationText = stringOption(form.locationText);
                var pairingNotes = stringOption(form.pairingNotes);
                var tastingNotes = stringOption(form.tastingNotes);
                return Js_promise2.then(EntryApi.createEntry(token, collectionId, wine.producer, wine.name, wine.vintage, wine.style, wine.grape, wine.region, wine.country, consumedAt, venueName, locationText, pairingNotes, tastingNotes, rating, undefined), (function (response) {
                              var entry = Belt_Option.flatMap(ResponseDecoder.parse(response), ResponseDecoder.entry);
                              if (entry !== undefined) {
                                return Promise.resolve(entry);
                              } else {
                                return Promise.reject(ApiClient.invalidResponse());
                              }
                            }));
              }));
}

function updateEntry(token, collectionId, entryId, wine, form) {
  return Js_promise2.then(intOption(form.rating, "invalid_rating"), (function (rating) {
                var consumedAt = consumedAtForSubmit(form);
                var venueName = stringOption(form.venueName);
                var locationText = stringOption(form.locationText);
                var pairingNotes = stringOption(form.pairingNotes);
                var tastingNotes = stringOption(form.tastingNotes);
                return Js_promise2.then(EntryApi.updateEntry(token, collectionId, entryId, wine.producer, wine.name, wine.vintage, wine.style, wine.grape, wine.region, wine.country, consumedAt, venueName, locationText, pairingNotes, tastingNotes, rating, undefined), (function (response) {
                              var entry = Belt_Option.flatMap(ResponseDecoder.parse(response), ResponseDecoder.entry);
                              if (entry !== undefined) {
                                return Promise.resolve(entry);
                              } else {
                                return Promise.reject(ApiClient.invalidResponse());
                              }
                            }));
              }));
}

var initialForm = {
  dateMode: false,
  consumedAt: undefined,
  venueName: "",
  locationText: "",
  pairingNotes: "",
  tastingNotes: "",
  rating: "",
  isSubmitting: false,
  error: undefined,
  success: undefined
};

export {
  initialStatus ,
  loadingStatus ,
  emptyStatus ,
  readyStatus ,
  errorStatus ,
  initialForm ,
  padTwo ,
  todayDateString ,
  updateForm ,
  toggleDateMode ,
  startSubmitting ,
  failForm ,
  succeedForm ,
  formFromEntry ,
  entries ,
  appendEntry ,
  replaceEntry ,
  isReady ,
  stringOption ,
  intOption ,
  consumedAtForSubmit ,
  listEntries ,
  createEntry ,
  updateEntry ,
}
/* EntryApi Not a pure module */
