// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ApiClient from "../api/ApiClient.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function stringify(value) {
  return Belt_Option.getExn(JSON.stringify(value));
}

function listEntries(token, collectionId) {
  return ApiClient.request("/api/collections/" + String(collectionId) + "/entries", {
              headers: ApiClient.authHeaders(token, {})
            });
}

function createEntry(token, collectionId, producer, name, vintage, style, grape, region, country, consumedAt, venueName, locationText, pairingNotes, tastingNotes, rating, param) {
  return ApiClient.request("/api/collections/" + String(collectionId) + "/entries", {
              method: "POST",
              headers: ApiClient.authHeaders(token, ApiClient.jsonHeaders),
              body: Belt_Option.getExn(JSON.stringify({
                        wine: {
                          producer: producer,
                          name: name,
                          vintage: vintage,
                          style: style,
                          grape: grape,
                          region: region,
                          country: country
                        },
                        consumed_at: consumedAt,
                        venue_name: venueName,
                        location_text: locationText,
                        pairing_notes: pairingNotes,
                        tasting_notes: tastingNotes,
                        rating: rating
                      }))
            });
}

function updateEntry(token, collectionId, entryId, producer, name, vintage, style, grape, region, country, consumedAt, venueName, locationText, pairingNotes, tastingNotes, rating, param) {
  return ApiClient.request("/api/collections/" + String(collectionId) + "/entries/" + String(entryId), {
              method: "PATCH",
              headers: ApiClient.authHeaders(token, ApiClient.jsonHeaders),
              body: Belt_Option.getExn(JSON.stringify({
                        wine: {
                          producer: producer,
                          name: name,
                          vintage: vintage,
                          style: style,
                          grape: grape,
                          region: region,
                          country: country
                        },
                        consumed_at: consumedAt,
                        venue_name: venueName,
                        location_text: locationText,
                        pairing_notes: pairingNotes,
                        tasting_notes: tastingNotes,
                        rating: rating
                      }))
            });
}

export {
  stringify ,
  listEntries ,
  createEntry ,
  updateEntry ,
}
/* ApiClient Not a pure module */
