// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TextField from "../ui/TextField.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as I18nContext from "../i18n/I18nContext.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function EntryComposer(props) {
  var onSubmit = props.onSubmit;
  var onToggleDateMode = props.onToggleDateMode;
  var onEntryFormChange = props.onEntryFormChange;
  var entryForm = props.entryForm;
  var t = I18nContext.useT();
  var match;
  match = props.mode === "Create" ? [
      t.entryComposerSaveCreate,
      t.entryComposerSavingLabel
    ] : [
      t.entryComposerSaveEdit,
      t.entryComposerSavingLabel
    ];
  var message = entryForm.error;
  var message$1 = entryForm.success;
  return JsxRuntime.jsxs("section", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("label", {
                              children: [
                                JsxRuntime.jsx("span", {
                                      children: t.entryComposerPairingNotesLabel,
                                      className: "mb-2 block text-sm font-medium text-stone-700"
                                    }),
                                JsxRuntime.jsx("textarea", {
                                      className: "w-full rounded-2xl border border-stone-300 bg-white px-4 py-3 text-base text-stone-950 outline-none transition focus:border-stone-500",
                                      rows: 3,
                                      value: entryForm.pairingNotes,
                                      onChange: (function ($$event) {
                                          onEntryFormChange("pairingNotes", $$event.target.value);
                                        })
                                    })
                              ],
                              className: "block"
                            }),
                        JsxRuntime.jsxs("label", {
                              children: [
                                JsxRuntime.jsx("span", {
                                      children: t.entryComposerTastingNotesLabel,
                                      className: "mb-2 block text-sm font-medium text-stone-700"
                                    }),
                                JsxRuntime.jsx("textarea", {
                                      className: "w-full rounded-2xl border border-stone-300 bg-white px-4 py-3 text-base text-stone-950 outline-none transition focus:border-stone-500",
                                      rows: 4,
                                      value: entryForm.tastingNotes,
                                      onChange: (function ($$event) {
                                          onEntryFormChange("tastingNotes", $$event.target.value);
                                        })
                                    })
                              ],
                              className: "block"
                            }),
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsx(TextField.make, {
                                    label: t.entryComposerRatingLabel,
                                    value: entryForm.rating,
                                    onChange: (function (value) {
                                        onEntryFormChange("rating", value);
                                      }),
                                    autoComplete: "off",
                                    type_: "number"
                                  }),
                              className: "md:w-40"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("label", {
                                      children: [
                                        JsxRuntime.jsx("input", {
                                              checked: entryForm.dateMode,
                                              type: "checkbox",
                                              onChange: (function ($$event) {
                                                  onToggleDateMode($$event.target.checked);
                                                })
                                            }),
                                        t.entryComposerSpecifyDate
                                      ],
                                      className: "flex items-center gap-2 text-sm font-medium text-stone-700"
                                    }),
                                entryForm.dateMode ? JsxRuntime.jsx("div", {
                                        children: JsxRuntime.jsx(TextField.make, {
                                              label: t.entryComposerConsumedAtLabel,
                                              value: Belt_Option.getWithDefault(entryForm.consumedAt, ""),
                                              onChange: (function (value) {
                                                  onEntryFormChange("consumedAt", value);
                                                }),
                                              autoComplete: "off",
                                              type_: "date"
                                            }),
                                        className: "mt-2"
                                      }) : null
                              ]
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(TextField.make, {
                                      label: t.entryComposerVenueLabel,
                                      value: entryForm.venueName,
                                      onChange: (function (value) {
                                          onEntryFormChange("venueName", value);
                                        }),
                                      autoComplete: "off"
                                    }),
                                JsxRuntime.jsx(TextField.make, {
                                      label: t.entryComposerLocationLabel,
                                      value: entryForm.locationText,
                                      onChange: (function (value) {
                                          onEntryFormChange("locationText", value);
                                        }),
                                      autoComplete: "street-address"
                                    })
                              ],
                              className: "grid gap-4 md:grid-cols-2"
                            })
                      ],
                      className: "grid gap-4"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("button", {
                            children: entryForm.isSubmitting ? match[1] : match[0],
                            className: "rounded-2xl bg-stone-950 px-5 py-3 text-sm font-semibold text-white transition hover:bg-stone-800 disabled:cursor-wait disabled:bg-stone-400",
                            disabled: entryForm.isSubmitting,
                            type: "button",
                            onClick: (function (param) {
                                onSubmit();
                              })
                          }),
                      className: "mt-4 flex justify-end"
                    }),
                message !== undefined ? JsxRuntime.jsx("div", {
                        children: message,
                        className: "mt-4 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700"
                      }) : null,
                message$1 !== undefined ? JsxRuntime.jsx("div", {
                        children: message$1,
                        className: "mt-4 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700"
                      }) : null
              ],
              className: "rounded-3xl border border-stone-900/10 bg-white p-6 shadow-[0_24px_80px_rgba(81,46,23,0.12)] md:p-8"
            });
}

var make = EntryComposer;

export {
  make ,
}
/* TextField Not a pure module */
