// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TextField from "../ui/TextField.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as JsxRuntime from "react/jsx-runtime";

function wineLabel(wine) {
  var producer = wine.producer;
  if (producer !== undefined) {
    return producer + " " + wine.name;
  } else {
    return wine.name;
  }
}

function EntryComposer(props) {
  var onClose = props.onClose;
  var onSubmit = props.onSubmit;
  var onUseNewWine = props.onUseNewWine;
  var onUseSelectedWine = props.onUseSelectedWine;
  var onEntryFormChange = props.onEntryFormChange;
  var entryForm = props.entryForm;
  var mode = props.mode;
  var match;
  match = mode === "Create" ? [
      "Add entry",
      "Capture a wine",
      "Save entry",
      "Saving..."
    ] : [
      "Edit entry",
      "Update this memory",
      "Save changes",
      "Saving..."
    ];
  var tmp;
  if (mode === "Create" && props.selectedWine !== undefined) {
    var match$1 = entryForm.wineSource;
    var tmp$1;
    tmp$1 = typeof match$1 !== "object" ? "rounded-2xl border border-stone-300 px-4 py-3 text-sm font-medium text-stone-700 transition hover:border-stone-500 hover:text-stone-950" : "rounded-2xl bg-stone-950 px-4 py-3 text-sm font-semibold text-white";
    var match$2 = entryForm.wineSource;
    var tmp$2;
    tmp$2 = typeof match$2 !== "object" ? "rounded-2xl bg-stone-950 px-4 py-3 text-sm font-semibold text-white" : "rounded-2xl border border-stone-300 px-4 py-3 text-sm font-medium text-stone-700 transition hover:border-stone-500 hover:text-stone-950";
    var wine = entryForm.wineSource;
    var tmp$3;
    if (typeof wine !== "object") {
      tmp$3 = null;
    } else {
      var wine$1 = wine._0;
      tmp$3 = JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("p", {
                    children: "Using",
                    className: "text-xs font-medium uppercase tracking-[0.2em] text-stone-500"
                  }),
              JsxRuntime.jsx("p", {
                    children: wineLabel(wine$1),
                    className: "mt-2 text-base font-semibold text-stone-950"
                  }),
              JsxRuntime.jsx("p", {
                    children: Belt_Array.keepMap([
                            wine$1.grape,
                            Belt_Option.map(wine$1.vintage, (function (prim) {
                                    return String(prim);
                                  })),
                            wine$1.region,
                            wine$1.country
                          ], (function (value) {
                              return value;
                            })).join(" · "),
                    className: "mt-1 text-sm text-stone-600"
                  })
            ],
            className: "mt-4 rounded-2xl border border-stone-200 bg-stone-50 px-4 py-4"
          });
    }
    tmp = JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsx("button", {
                          children: "Selected wine",
                          className: tmp$1,
                          type: "button",
                          onClick: (function (param) {
                              onUseSelectedWine();
                            })
                        }),
                    JsxRuntime.jsx("button", {
                          children: "Different wine",
                          className: tmp$2,
                          type: "button",
                          onClick: (function (param) {
                              onUseNewWine();
                            })
                        })
                  ],
                  className: "flex flex-wrap gap-3"
                }),
            tmp$3
          ],
          className: "md:col-span-2"
        });
  } else {
    tmp = null;
  }
  var match$3 = entryForm.wineSource;
  var tmp$4;
  tmp$4 = typeof match$3 !== "object" ? JsxRuntime.jsxs(JsxRuntime.Fragment, {
          children: [
            JsxRuntime.jsx(TextField.make, {
                  label: "Wine name",
                  value: entryForm.wineName,
                  onChange: (function (value) {
                      onEntryFormChange("wineName", value);
                    }),
                  autoComplete: "off"
                }),
            JsxRuntime.jsx(TextField.make, {
                  label: "Producer",
                  value: entryForm.producer,
                  onChange: (function (value) {
                      onEntryFormChange("producer", value);
                    }),
                  autoComplete: "organization"
                }),
            JsxRuntime.jsx(TextField.make, {
                  label: "Style",
                  value: entryForm.style,
                  onChange: (function (value) {
                      onEntryFormChange("style", value);
                    }),
                  autoComplete: "off"
                }),
            JsxRuntime.jsx(TextField.make, {
                  label: "Grape",
                  value: entryForm.grape,
                  onChange: (function (value) {
                      onEntryFormChange("grape", value);
                    }),
                  autoComplete: "off"
                }),
            JsxRuntime.jsx(TextField.make, {
                  label: "Region",
                  value: entryForm.region,
                  onChange: (function (value) {
                      onEntryFormChange("region", value);
                    }),
                  autoComplete: "off"
                }),
            JsxRuntime.jsx(TextField.make, {
                  label: "Country",
                  value: entryForm.country,
                  onChange: (function (value) {
                      onEntryFormChange("country", value);
                    }),
                  autoComplete: "country-name"
                }),
            JsxRuntime.jsx(TextField.make, {
                  label: "Vintage",
                  value: entryForm.vintage,
                  onChange: (function (value) {
                      onEntryFormChange("vintage", value);
                    }),
                  autoComplete: "off",
                  type_: "number"
                })
          ]
        }) : (
      mode === "Create" ? null : JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(TextField.make, {
                      label: "Wine name",
                      value: entryForm.wineName,
                      onChange: (function (value) {
                          onEntryFormChange("wineName", value);
                        }),
                      autoComplete: "off"
                    }),
                JsxRuntime.jsx(TextField.make, {
                      label: "Producer",
                      value: entryForm.producer,
                      onChange: (function (value) {
                          onEntryFormChange("producer", value);
                        }),
                      autoComplete: "organization"
                    }),
                JsxRuntime.jsx(TextField.make, {
                      label: "Style",
                      value: entryForm.style,
                      onChange: (function (value) {
                          onEntryFormChange("style", value);
                        }),
                      autoComplete: "off"
                    }),
                JsxRuntime.jsx(TextField.make, {
                      label: "Grape",
                      value: entryForm.grape,
                      onChange: (function (value) {
                          onEntryFormChange("grape", value);
                        }),
                      autoComplete: "off"
                    }),
                JsxRuntime.jsx(TextField.make, {
                      label: "Region",
                      value: entryForm.region,
                      onChange: (function (value) {
                          onEntryFormChange("region", value);
                        }),
                      autoComplete: "off"
                    }),
                JsxRuntime.jsx(TextField.make, {
                      label: "Country",
                      value: entryForm.country,
                      onChange: (function (value) {
                          onEntryFormChange("country", value);
                        }),
                      autoComplete: "country-name"
                    }),
                JsxRuntime.jsx(TextField.make, {
                      label: "Vintage",
                      value: entryForm.vintage,
                      onChange: (function (value) {
                          onEntryFormChange("vintage", value);
                        }),
                      autoComplete: "off",
                      type_: "number"
                    })
              ]
            })
    );
  var message = entryForm.error;
  var message$1 = entryForm.success;
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("section", {
                    children: [
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("p", {
                                            children: match[0],
                                            className: "text-xs font-medium uppercase tracking-[0.25em] text-stone-500"
                                          }),
                                      JsxRuntime.jsx("h3", {
                                            children: match[1],
                                            className: "mt-2 text-2xl font-semibold text-stone-950"
                                          })
                                    ]
                                  }),
                              JsxRuntime.jsx("button", {
                                    children: "Close",
                                    className: "rounded-2xl border border-stone-300 px-4 py-2 text-sm font-medium text-stone-700 transition hover:border-stone-500 hover:text-stone-950",
                                    type: "button",
                                    onClick: (function (param) {
                                        onClose();
                                      })
                                  })
                            ],
                            className: "flex items-start justify-between gap-4"
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              tmp,
                              tmp$4,
                              JsxRuntime.jsx(TextField.make, {
                                    label: "Consumed at",
                                    value: entryForm.consumedAt,
                                    onChange: (function (value) {
                                        onEntryFormChange("consumedAt", value);
                                      }),
                                    autoComplete: "off",
                                    type_: "datetime-local"
                                  }),
                              JsxRuntime.jsx(TextField.make, {
                                    label: "Venue",
                                    value: entryForm.venueName,
                                    onChange: (function (value) {
                                        onEntryFormChange("venueName", value);
                                      }),
                                    autoComplete: "off"
                                  }),
                              JsxRuntime.jsx(TextField.make, {
                                    label: "Location",
                                    value: entryForm.locationText,
                                    onChange: (function (value) {
                                        onEntryFormChange("locationText", value);
                                      }),
                                    autoComplete: "street-address"
                                  })
                            ],
                            className: "mt-6 grid gap-4 md:grid-cols-2"
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsxs("label", {
                                    children: [
                                      JsxRuntime.jsx("span", {
                                            children: "Pairing notes",
                                            className: "mb-2 block text-sm font-medium text-stone-700"
                                          }),
                                      JsxRuntime.jsx("textarea", {
                                            className: "w-full rounded-2xl border border-stone-300 bg-white px-4 py-3 text-base text-stone-950 outline-none transition focus:border-stone-500",
                                            rows: 3,
                                            value: entryForm.pairingNotes,
                                            onChange: (function ($$event) {
                                                onEntryFormChange("pairingNotes", $$event.target.value);
                                              })
                                          })
                                    ],
                                    className: "block"
                                  }),
                              JsxRuntime.jsxs("label", {
                                    children: [
                                      JsxRuntime.jsx("span", {
                                            children: "Tasting notes",
                                            className: "mb-2 block text-sm font-medium text-stone-700"
                                          }),
                                      JsxRuntime.jsx("textarea", {
                                            className: "w-full rounded-2xl border border-stone-300 bg-white px-4 py-3 text-base text-stone-950 outline-none transition focus:border-stone-500",
                                            rows: 4,
                                            value: entryForm.tastingNotes,
                                            onChange: (function ($$event) {
                                                onEntryFormChange("tastingNotes", $$event.target.value);
                                              })
                                          })
                                    ],
                                    className: "block"
                                  })
                            ],
                            className: "mt-4 grid gap-4"
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("div", {
                                    children: JsxRuntime.jsx(TextField.make, {
                                          label: "Rating",
                                          value: entryForm.rating,
                                          onChange: (function (value) {
                                              onEntryFormChange("rating", value);
                                            }),
                                          autoComplete: "off",
                                          type_: "number"
                                        }),
                                    className: "md:w-40"
                                  }),
                              JsxRuntime.jsx("button", {
                                    children: entryForm.isSubmitting ? match[3] : match[2],
                                    className: "rounded-2xl bg-stone-950 px-5 py-3 text-sm font-semibold text-white transition hover:bg-stone-800 disabled:cursor-wait disabled:bg-stone-400",
                                    disabled: entryForm.isSubmitting,
                                    type: "button",
                                    onClick: (function (param) {
                                        onSubmit();
                                      })
                                  })
                            ],
                            className: "mt-4 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"
                          }),
                      message !== undefined ? JsxRuntime.jsx("div", {
                              children: message,
                              className: "mt-4 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700"
                            }) : null,
                      message$1 !== undefined ? JsxRuntime.jsx("div", {
                              children: message$1,
                              className: "mt-4 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700"
                            }) : null
                    ],
                    className: "mx-auto w-full max-w-2xl rounded-[2rem] border border-stone-900/10 bg-white p-6 shadow-[0_24px_80px_rgba(81,46,23,0.2)] md:p-8"
                  }),
              className: "fixed inset-0 z-50 overflow-y-auto bg-stone-950/40 px-4 py-4 md:px-6 md:py-10"
            });
}

var make = EntryComposer;

export {
  wineLabel ,
  make ,
}
/* TextField Not a pure module */
