// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";

function detailLine(label, value) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("dt", {
                      children: label,
                      className: "text-xs font-medium uppercase tracking-[0.2em] text-stone-500"
                    }),
                JsxRuntime.jsx("dd", {
                      children: value,
                      className: "mt-1 text-sm leading-6 text-stone-700"
                    })
              ]
            });
}

function optionalDetailLine(label, value) {
  if (value !== undefined) {
    return Caml_option.some(detailLine(label, value));
  }
  
}

function wineSummary(entry) {
  var parts = Belt_Array.keepMap([
        entry.wine.producer,
        entry.wine.name,
        Belt_Option.map(entry.wine.vintage, (function (prim) {
                return String(prim);
              }))
      ], (function (value) {
          return value;
        }));
  return parts.join(" · ");
}

function EntryDetail(props) {
  var entry = props.entry;
  if (entry === undefined) {
    return JsxRuntime.jsxs("section", {
                children: [
                  JsxRuntime.jsx("h3", {
                        children: "Entry detail",
                        className: "text-lg font-semibold text-stone-950"
                      }),
                  JsxRuntime.jsx("p", {
                        children: "Select an entry from history to inspect the wine and occasion details.",
                        className: "mt-2 text-sm leading-6 text-stone-600"
                      })
                ],
                className: "rounded-[1.75rem] border border-dashed border-stone-300 bg-stone-50/80 p-6"
              });
  }
  var rating = entry.rating;
  return JsxRuntime.jsxs("section", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("p", {
                                      children: "Entry detail",
                                      className: "text-xs font-medium uppercase tracking-[0.25em] text-stone-500"
                                    }),
                                JsxRuntime.jsx("h3", {
                                      children: wineSummary(entry),
                                      className: "mt-2 text-2xl font-semibold text-stone-950"
                                    })
                              ]
                            }),
                        rating !== undefined ? JsxRuntime.jsx("span", {
                                children: "Rating " + String(rating) + "/5",
                                className: "rounded-full border border-amber-300 bg-amber-50 px-3 py-1 text-xs font-semibold uppercase tracking-[0.2em] text-amber-800"
                              }) : null
                      ],
                      className: "flex flex-col gap-4 md:flex-row md:items-start md:justify-between"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("section", {
                              children: [
                                JsxRuntime.jsx("h4", {
                                      children: "Wine",
                                      className: "text-sm font-semibold uppercase tracking-[0.2em] text-stone-600"
                                    }),
                                JsxRuntime.jsxs("dl", {
                                      children: [
                                        detailLine("Name", entry.wine.name),
                                        Belt_Option.getWithDefault(optionalDetailLine("Producer", entry.wine.producer), null),
                                        Belt_Option.getWithDefault(optionalDetailLine("Vintage", Belt_Option.map(entry.wine.vintage, (function (prim) {
                                                        return String(prim);
                                                      }))), null),
                                        Belt_Option.getWithDefault(optionalDetailLine("Style", entry.wine.style), null),
                                        Belt_Option.getWithDefault(optionalDetailLine("Grape", entry.wine.grape), null),
                                        Belt_Option.getWithDefault(optionalDetailLine("Region", entry.wine.region), null),
                                        Belt_Option.getWithDefault(optionalDetailLine("Country", entry.wine.country), null)
                                      ],
                                      className: "mt-4 grid gap-4"
                                    })
                              ],
                              className: "rounded-2xl border border-stone-200 bg-white p-5"
                            }),
                        JsxRuntime.jsxs("section", {
                              children: [
                                JsxRuntime.jsx("h4", {
                                      children: "Occasion",
                                      className: "text-sm font-semibold uppercase tracking-[0.2em] text-stone-600"
                                    }),
                                JsxRuntime.jsxs("dl", {
                                      children: [
                                        detailLine("Consumed at", entry.consumedAt),
                                        Belt_Option.getWithDefault(optionalDetailLine("Venue", entry.venueName), null),
                                        Belt_Option.getWithDefault(optionalDetailLine("Location", entry.locationText), null),
                                        Belt_Option.getWithDefault(optionalDetailLine("Pairing notes", entry.pairingNotes), null),
                                        Belt_Option.getWithDefault(optionalDetailLine("Tasting notes", entry.tastingNotes), null)
                                      ],
                                      className: "mt-4 grid gap-4"
                                    })
                              ],
                              className: "rounded-2xl border border-stone-200 bg-white p-5"
                            })
                      ],
                      className: "mt-6 grid gap-6 md:grid-cols-2"
                    })
              ],
              className: "rounded-[1.75rem] border border-stone-900/10 bg-stone-50/80 p-6"
            });
}

var make = EntryDetail;

export {
  detailLine ,
  optionalDetailLine ,
  wineSummary ,
  make ,
}
/* react/jsx-runtime Not a pure module */
