// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as I18nContext from "../i18n/I18nContext.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function wineLabel(entry) {
  var producer = entry.wine.producer;
  if (producer !== undefined) {
    return producer + " " + entry.wine.name;
  } else {
    return entry.wine.name;
  }
}

function wineMeta(entry) {
  var segments = Belt_Array.keepMap([
        Belt_Option.map(entry.wine.vintage, (function (prim) {
                return String(prim);
              })),
        entry.locationText,
        entry.venueName
      ], (function (value) {
          return value;
        }));
  if (segments.length === 0) {
    return ;
  } else {
    return segments.join(" · ");
  }
}

function EntryHistory(props) {
  var wineId = props.wineId;
  var onSelectEntry = props.onSelectEntry;
  var selectedEntryId = props.selectedEntryId;
  var __emptyMessage = props.emptyMessage;
  var __loadingMessage = props.loadingMessage;
  var __idleMessage = props.idleMessage;
  var __title = props.title;
  var status = props.status;
  var title = __title !== undefined ? __title : "Entry history";
  var idleMessage = __idleMessage !== undefined ? __idleMessage : "Select a collection to browse its entries.";
  var loadingMessage = __loadingMessage !== undefined ? __loadingMessage : "Loading collection history...";
  var emptyMessage = __emptyMessage !== undefined ? __emptyMessage : "No entries yet. Your latest bottles and notes will show up here.";
  var t = I18nContext.useT();
  if (typeof status !== "object") {
    if (status === "Idle") {
      return JsxRuntime.jsxs("section", {
                  children: [
                    JsxRuntime.jsx("h3", {
                          children: title,
                          className: "text-lg font-semibold text-stone-950"
                        }),
                    JsxRuntime.jsx("p", {
                          children: idleMessage,
                          className: "mt-2 text-sm leading-6 text-stone-600"
                        })
                  ],
                  className: "rounded-[1.75rem] border border-dashed border-stone-300 bg-stone-50/80 p-6"
                });
    } else {
      return JsxRuntime.jsxs("section", {
                  children: [
                    JsxRuntime.jsx("h3", {
                          children: title,
                          className: "text-lg font-semibold text-stone-950"
                        }),
                    JsxRuntime.jsx("p", {
                          children: loadingMessage,
                          className: "mt-2 text-sm text-stone-600"
                        })
                  ],
                  className: "rounded-[1.75rem] border border-stone-900/10 bg-stone-50/80 p-6"
                });
    }
  }
  if (status.TAG !== "Ready") {
    return JsxRuntime.jsxs("section", {
                children: [
                  JsxRuntime.jsx("h3", {
                        children: title,
                        className: "text-lg font-semibold text-rose-900"
                      }),
                  JsxRuntime.jsx("p", {
                        children: status._0,
                        className: "mt-2 text-sm text-rose-700"
                      })
                ],
                className: "rounded-[1.75rem] border border-rose-200 bg-rose-50 p-6"
              });
  }
  var entries = status._0;
  var visibleEntries = wineId !== undefined ? Belt_Array.keep(entries, (function (entry) {
            return entry.wine.id === wineId;
          })) : entries;
  if (visibleEntries.length === 0) {
    return JsxRuntime.jsxs("section", {
                children: [
                  JsxRuntime.jsx("h3", {
                        children: title,
                        className: "text-lg font-semibold text-stone-950"
                      }),
                  JsxRuntime.jsx("p", {
                        children: emptyMessage,
                        className: "mt-2 text-sm leading-6 text-stone-600"
                      })
                ],
                className: "rounded-[1.75rem] border border-dashed border-stone-300 bg-stone-50/80 p-6"
              });
  } else {
    return JsxRuntime.jsxs("section", {
                children: [
                  JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsx("h3", {
                                children: title,
                                className: "text-lg font-semibold text-stone-950"
                              }),
                          JsxRuntime.jsx("span", {
                                children: t.entryCount(visibleEntries.length),
                                className: "rounded-full border border-stone-300 px-3 py-1 text-xs font-medium uppercase tracking-[0.2em] text-stone-600"
                              })
                        ],
                        className: "flex items-center justify-between gap-4"
                      }),
                  JsxRuntime.jsx("ul", {
                        children: Belt_Array.map(visibleEntries, (function (entry) {
                                var isSelected = selectedEntryId !== undefined ? entry.id === selectedEntryId : false;
                                var meta = wineMeta(entry);
                                var rating = entry.rating;
                                var value = entry.consumedAt;
                                var notes = entry.tastingNotes;
                                var notes$1 = entry.pairingNotes;
                                return JsxRuntime.jsx("li", {
                                            children: JsxRuntime.jsxs("button", {
                                                  children: [
                                                    JsxRuntime.jsxs("div", {
                                                          children: [
                                                            JsxRuntime.jsxs("div", {
                                                                  children: [
                                                                    JsxRuntime.jsx("p", {
                                                                          children: wineLabel(entry),
                                                                          className: isSelected ? "text-base font-semibold text-white" : "text-base font-semibold text-stone-950"
                                                                        }),
                                                                    meta !== undefined ? JsxRuntime.jsx("p", {
                                                                            children: meta,
                                                                            className: isSelected ? "mt-1 text-sm text-stone-200" : "mt-1 text-sm text-stone-600"
                                                                          }) : null
                                                                  ]
                                                                }),
                                                            rating !== undefined ? JsxRuntime.jsx("span", {
                                                                    children: t.rating(rating),
                                                                    className: isSelected ? "rounded-full border border-white/20 bg-white/10 px-3 py-1 text-xs font-semibold uppercase tracking-[0.2em] text-white" : "rounded-full border border-amber-300 bg-amber-50 px-3 py-1 text-xs font-semibold uppercase tracking-[0.2em] text-amber-800"
                                                                  }) : null
                                                          ],
                                                          className: "flex items-start justify-between gap-4"
                                                        }),
                                                    value !== undefined ? JsxRuntime.jsx("p", {
                                                            children: value,
                                                            className: isSelected ? "mt-3 text-xs font-medium uppercase tracking-[0.2em] text-stone-300" : "mt-3 text-xs font-medium uppercase tracking-[0.2em] text-stone-500"
                                                          }) : null,
                                                    notes !== undefined ? JsxRuntime.jsx("p", {
                                                            children: notes,
                                                            className: isSelected ? "mt-3 text-sm leading-6 text-stone-100" : "mt-3 text-sm leading-6 text-stone-700"
                                                          }) : null,
                                                    notes$1 !== undefined ? JsxRuntime.jsxs("p", {
                                                            children: [
                                                              JsxRuntime.jsx("span", {
                                                                    children: t.entryHistoryPairingPrefix,
                                                                    className: isSelected ? "font-medium text-white" : "font-medium text-stone-800"
                                                                  }),
                                                              notes$1
                                                            ],
                                                            className: isSelected ? "mt-2 text-sm leading-6 text-stone-200" : "mt-2 text-sm leading-6 text-stone-600"
                                                          }) : null
                                                  ],
                                                  className: "block w-full text-left",
                                                  type: "button",
                                                  onClick: (function (param) {
                                                      onSelectEntry(entry.id);
                                                    })
                                                }),
                                            className: isSelected ? "rounded-2xl border border-stone-950 bg-stone-950 p-4 shadow-sm text-white" : "rounded-2xl border border-stone-200 bg-white p-4 shadow-sm"
                                          }, String(entry.id));
                              })),
                        className: "mt-4 space-y-3"
                      })
                ],
                className: "rounded-[1.75rem] border border-stone-900/10 bg-stone-50/80 p-6"
              });
  }
}

var make = EntryHistory;

export {
  wineLabel ,
  wineMeta ,
  make ,
}
/* I18nContext Not a pure module */
