// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$String from "rescript/lib/es6/string.js";
import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as EntryApi from "./EntryApi.bs.js";
import * as ApiClient from "../api/ApiClient.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_array from "rescript/lib/es6/caml_array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Js_promise2 from "rescript/lib/es6/js_promise2.js";
import * as ResponseDecoder from "../api/ResponseDecoder.bs.js";

function initialStatus() {
  return "Idle";
}

function loadingStatus() {
  return "Loading";
}

function emptyStatus() {
  return {
          TAG: "Ready",
          _0: []
        };
}

function readyStatus(entries) {
  return {
          TAG: "Ready",
          _0: entries
        };
}

function errorStatus(message) {
  return {
          TAG: "Error",
          _0: message
        };
}

function updateForm(form, field, value) {
  switch (field) {
    case "consumedAt" :
        return {
                wineSource: form.wineSource,
                wineName: form.wineName,
                producer: form.producer,
                style: form.style,
                grape: form.grape,
                region: form.region,
                country: form.country,
                vintage: form.vintage,
                consumedAt: value,
                venueName: form.venueName,
                locationText: form.locationText,
                pairingNotes: form.pairingNotes,
                tastingNotes: form.tastingNotes,
                rating: form.rating,
                isSubmitting: form.isSubmitting,
                error: undefined,
                success: undefined
              };
    case "country" :
        return {
                wineSource: form.wineSource,
                wineName: form.wineName,
                producer: form.producer,
                style: form.style,
                grape: form.grape,
                region: form.region,
                country: value,
                vintage: form.vintage,
                consumedAt: form.consumedAt,
                venueName: form.venueName,
                locationText: form.locationText,
                pairingNotes: form.pairingNotes,
                tastingNotes: form.tastingNotes,
                rating: form.rating,
                isSubmitting: form.isSubmitting,
                error: undefined,
                success: undefined
              };
    case "grape" :
        return {
                wineSource: form.wineSource,
                wineName: form.wineName,
                producer: form.producer,
                style: form.style,
                grape: value,
                region: form.region,
                country: form.country,
                vintage: form.vintage,
                consumedAt: form.consumedAt,
                venueName: form.venueName,
                locationText: form.locationText,
                pairingNotes: form.pairingNotes,
                tastingNotes: form.tastingNotes,
                rating: form.rating,
                isSubmitting: form.isSubmitting,
                error: undefined,
                success: undefined
              };
    case "locationText" :
        return {
                wineSource: form.wineSource,
                wineName: form.wineName,
                producer: form.producer,
                style: form.style,
                grape: form.grape,
                region: form.region,
                country: form.country,
                vintage: form.vintage,
                consumedAt: form.consumedAt,
                venueName: form.venueName,
                locationText: value,
                pairingNotes: form.pairingNotes,
                tastingNotes: form.tastingNotes,
                rating: form.rating,
                isSubmitting: form.isSubmitting,
                error: undefined,
                success: undefined
              };
    case "pairingNotes" :
        return {
                wineSource: form.wineSource,
                wineName: form.wineName,
                producer: form.producer,
                style: form.style,
                grape: form.grape,
                region: form.region,
                country: form.country,
                vintage: form.vintage,
                consumedAt: form.consumedAt,
                venueName: form.venueName,
                locationText: form.locationText,
                pairingNotes: value,
                tastingNotes: form.tastingNotes,
                rating: form.rating,
                isSubmitting: form.isSubmitting,
                error: undefined,
                success: undefined
              };
    case "producer" :
        return {
                wineSource: form.wineSource,
                wineName: form.wineName,
                producer: value,
                style: form.style,
                grape: form.grape,
                region: form.region,
                country: form.country,
                vintage: form.vintage,
                consumedAt: form.consumedAt,
                venueName: form.venueName,
                locationText: form.locationText,
                pairingNotes: form.pairingNotes,
                tastingNotes: form.tastingNotes,
                rating: form.rating,
                isSubmitting: form.isSubmitting,
                error: undefined,
                success: undefined
              };
    case "rating" :
        return {
                wineSource: form.wineSource,
                wineName: form.wineName,
                producer: form.producer,
                style: form.style,
                grape: form.grape,
                region: form.region,
                country: form.country,
                vintage: form.vintage,
                consumedAt: form.consumedAt,
                venueName: form.venueName,
                locationText: form.locationText,
                pairingNotes: form.pairingNotes,
                tastingNotes: form.tastingNotes,
                rating: value,
                isSubmitting: form.isSubmitting,
                error: undefined,
                success: undefined
              };
    case "region" :
        return {
                wineSource: form.wineSource,
                wineName: form.wineName,
                producer: form.producer,
                style: form.style,
                grape: form.grape,
                region: value,
                country: form.country,
                vintage: form.vintage,
                consumedAt: form.consumedAt,
                venueName: form.venueName,
                locationText: form.locationText,
                pairingNotes: form.pairingNotes,
                tastingNotes: form.tastingNotes,
                rating: form.rating,
                isSubmitting: form.isSubmitting,
                error: undefined,
                success: undefined
              };
    case "style" :
        return {
                wineSource: form.wineSource,
                wineName: form.wineName,
                producer: form.producer,
                style: value,
                grape: form.grape,
                region: form.region,
                country: form.country,
                vintage: form.vintage,
                consumedAt: form.consumedAt,
                venueName: form.venueName,
                locationText: form.locationText,
                pairingNotes: form.pairingNotes,
                tastingNotes: form.tastingNotes,
                rating: form.rating,
                isSubmitting: form.isSubmitting,
                error: undefined,
                success: undefined
              };
    case "tastingNotes" :
        return {
                wineSource: form.wineSource,
                wineName: form.wineName,
                producer: form.producer,
                style: form.style,
                grape: form.grape,
                region: form.region,
                country: form.country,
                vintage: form.vintage,
                consumedAt: form.consumedAt,
                venueName: form.venueName,
                locationText: form.locationText,
                pairingNotes: form.pairingNotes,
                tastingNotes: value,
                rating: form.rating,
                isSubmitting: form.isSubmitting,
                error: undefined,
                success: undefined
              };
    case "venueName" :
        return {
                wineSource: form.wineSource,
                wineName: form.wineName,
                producer: form.producer,
                style: form.style,
                grape: form.grape,
                region: form.region,
                country: form.country,
                vintage: form.vintage,
                consumedAt: form.consumedAt,
                venueName: value,
                locationText: form.locationText,
                pairingNotes: form.pairingNotes,
                tastingNotes: form.tastingNotes,
                rating: form.rating,
                isSubmitting: form.isSubmitting,
                error: undefined,
                success: undefined
              };
    case "vintage" :
        return {
                wineSource: form.wineSource,
                wineName: form.wineName,
                producer: form.producer,
                style: form.style,
                grape: form.grape,
                region: form.region,
                country: form.country,
                vintage: value,
                consumedAt: form.consumedAt,
                venueName: form.venueName,
                locationText: form.locationText,
                pairingNotes: form.pairingNotes,
                tastingNotes: form.tastingNotes,
                rating: form.rating,
                isSubmitting: form.isSubmitting,
                error: undefined,
                success: undefined
              };
    case "wineName" :
        return {
                wineSource: form.wineSource,
                wineName: value,
                producer: form.producer,
                style: form.style,
                grape: form.grape,
                region: form.region,
                country: form.country,
                vintage: form.vintage,
                consumedAt: form.consumedAt,
                venueName: form.venueName,
                locationText: form.locationText,
                pairingNotes: form.pairingNotes,
                tastingNotes: form.tastingNotes,
                rating: form.rating,
                isSubmitting: form.isSubmitting,
                error: undefined,
                success: undefined
              };
    default:
      return form;
  }
}

function startSubmitting(form) {
  return {
          wineSource: form.wineSource,
          wineName: form.wineName,
          producer: form.producer,
          style: form.style,
          grape: form.grape,
          region: form.region,
          country: form.country,
          vintage: form.vintage,
          consumedAt: form.consumedAt,
          venueName: form.venueName,
          locationText: form.locationText,
          pairingNotes: form.pairingNotes,
          tastingNotes: form.tastingNotes,
          rating: form.rating,
          isSubmitting: true,
          error: undefined,
          success: undefined
        };
}

function failForm(form, message) {
  return {
          wineSource: form.wineSource,
          wineName: form.wineName,
          producer: form.producer,
          style: form.style,
          grape: form.grape,
          region: form.region,
          country: form.country,
          vintage: form.vintage,
          consumedAt: form.consumedAt,
          venueName: form.venueName,
          locationText: form.locationText,
          pairingNotes: form.pairingNotes,
          tastingNotes: form.tastingNotes,
          rating: form.rating,
          isSubmitting: false,
          error: message,
          success: undefined
        };
}

function succeedForm() {
  return {
          wineSource: "NewWine",
          wineName: "",
          producer: "",
          style: "",
          grape: "",
          region: "",
          country: "",
          vintage: "",
          consumedAt: "",
          venueName: "",
          locationText: "",
          pairingNotes: "",
          tastingNotes: "",
          rating: "",
          isSubmitting: false,
          error: undefined,
          success: "Entry saved."
        };
}

function padTwo(value) {
  var text = String(value);
  if (value < 10) {
    return "0" + text;
  } else {
    return text;
  }
}

function toDateTimeLocalValue(consumedAt) {
  var date = new Date(consumedAt);
  if (Number.isNaN(date.getTime())) {
    return "";
  } else {
    return String(date.getFullYear()) + "-" + padTwo(date.getMonth() + 1 | 0) + "-" + padTwo(date.getDate()) + "T" + padTwo(date.getHours()) + ":" + padTwo(date.getMinutes());
  }
}

function formFromEntry(entry) {
  return {
          wineSource: "NewWine",
          wineName: entry.wine.name,
          producer: Belt_Option.getWithDefault(entry.wine.producer, ""),
          style: Belt_Option.getWithDefault(entry.wine.style, ""),
          grape: Belt_Option.getWithDefault(entry.wine.grape, ""),
          region: Belt_Option.getWithDefault(entry.wine.region, ""),
          country: Belt_Option.getWithDefault(entry.wine.country, ""),
          vintage: Belt_Option.getWithDefault(Belt_Option.map(entry.wine.vintage, (function (prim) {
                      return String(prim);
                    })), ""),
          consumedAt: toDateTimeLocalValue(entry.consumedAt),
          venueName: Belt_Option.getWithDefault(entry.venueName, ""),
          locationText: Belt_Option.getWithDefault(entry.locationText, ""),
          pairingNotes: Belt_Option.getWithDefault(entry.pairingNotes, ""),
          tastingNotes: Belt_Option.getWithDefault(entry.tastingNotes, ""),
          rating: Belt_Option.getWithDefault(Belt_Option.map(entry.rating, (function (prim) {
                      return String(prim);
                    })), ""),
          isSubmitting: false,
          error: undefined,
          success: undefined
        };
}

function formFromWineSummary(summary) {
  return {
          wineSource: {
            TAG: "ExistingWine",
            _0: summary.wine
          },
          wineName: summary.wine.name,
          producer: Belt_Option.getWithDefault(summary.wine.producer, ""),
          style: Belt_Option.getWithDefault(summary.wine.style, ""),
          grape: Belt_Option.getWithDefault(summary.wine.grape, ""),
          region: Belt_Option.getWithDefault(summary.wine.region, ""),
          country: Belt_Option.getWithDefault(summary.wine.country, ""),
          vintage: Belt_Option.getWithDefault(Belt_Option.map(summary.wine.vintage, (function (prim) {
                      return String(prim);
                    })), ""),
          consumedAt: "",
          venueName: "",
          locationText: "",
          pairingNotes: "",
          tastingNotes: "",
          rating: "",
          isSubmitting: false,
          error: undefined,
          success: undefined
        };
}

function useNewWine(form) {
  return {
          wineSource: "NewWine",
          wineName: "",
          producer: "",
          style: "",
          grape: "",
          region: "",
          country: "",
          vintage: "",
          consumedAt: form.consumedAt,
          venueName: form.venueName,
          locationText: form.locationText,
          pairingNotes: form.pairingNotes,
          tastingNotes: form.tastingNotes,
          rating: form.rating,
          isSubmitting: false,
          error: undefined,
          success: undefined
        };
}

function useExistingWine(form, wine) {
  return {
          wineSource: {
            TAG: "ExistingWine",
            _0: wine
          },
          wineName: wine.name,
          producer: Belt_Option.getWithDefault(wine.producer, ""),
          style: Belt_Option.getWithDefault(wine.style, ""),
          grape: Belt_Option.getWithDefault(wine.grape, ""),
          region: Belt_Option.getWithDefault(wine.region, ""),
          country: Belt_Option.getWithDefault(wine.country, ""),
          vintage: Belt_Option.getWithDefault(Belt_Option.map(wine.vintage, (function (prim) {
                      return String(prim);
                    })), ""),
          consumedAt: form.consumedAt,
          venueName: form.venueName,
          locationText: form.locationText,
          pairingNotes: form.pairingNotes,
          tastingNotes: form.tastingNotes,
          rating: form.rating,
          isSubmitting: false,
          error: undefined,
          success: undefined
        };
}

function entries(status) {
  if (typeof status !== "object") {
    return [];
  } else if (status.TAG === "Ready") {
    return status._0;
  } else {
    return [];
  }
}

function selectedEntry(entries, selectedEntryId) {
  if (selectedEntryId !== undefined) {
    return Belt_Array.getBy(entries, (function (entry) {
                  return entry.id === selectedEntryId;
                }));
  }
  
}

function resolveSelectedEntryId(entries, selectedEntryId) {
  if (entries.length === 0) {
    return ;
  }
  var match = selectedEntry(entries, selectedEntryId);
  if (match !== undefined) {
    return selectedEntryId;
  } else {
    return Caml_array.get(entries, 0).id;
  }
}

function appendEntry(entries, entry) {
  return Belt_Array.concat([entry], entries);
}

function replaceEntry(entries, nextEntry) {
  return Belt_Array.map(entries, (function (entry) {
                if (entry.id === nextEntry.id) {
                  return nextEntry;
                } else {
                  return entry;
                }
              }));
}

function isReady(status) {
  if (typeof status !== "object" || status.TAG !== "Ready") {
    return false;
  } else {
    return true;
  }
}

function stringOption(value) {
  var trimmed = $$String.trim(value);
  if (trimmed === "") {
    return ;
  } else {
    return trimmed;
  }
}

function intOption(value, errorCode) {
  var trimmed = $$String.trim(value);
  if (trimmed === "") {
    return Promise.resolve(undefined);
  }
  var number = Belt_Int.fromString(trimmed);
  if (number !== undefined) {
    return Promise.resolve(number);
  } else {
    return Promise.reject(new Error(errorCode));
  }
}

function normalizeConsumedAt(value) {
  var trimmed = $$String.trim(value);
  if (trimmed === "") {
    return Promise.reject(new Error("invalid_consumed_at"));
  }
  var date = new Date(trimmed);
  if (Number.isNaN(date.getTime())) {
    return Promise.reject(new Error("invalid_consumed_at"));
  } else {
    return Promise.resolve(date.toISOString());
  }
}

function listEntries(token, collectionId) {
  return Js_promise2.then(EntryApi.listEntries(token, collectionId), (function (response) {
                var entries = Belt_Option.flatMap(ResponseDecoder.parse(response), ResponseDecoder.entries);
                if (entries !== undefined) {
                  return Promise.resolve(entries);
                } else {
                  return Promise.reject(ApiClient.invalidResponse());
                }
              }));
}

function createEntry(token, collectionId, form) {
  return Js_promise2.then(normalizeConsumedAt(form.consumedAt), (function (consumedAt) {
                return Js_promise2.then(intOption(form.vintage, "invalid_wine_vintage"), (function (vintage) {
                              return Js_promise2.then(intOption(form.rating, "invalid_rating"), (function (rating) {
                                            var wine = form.wineSource;
                                            var match;
                                            if (typeof wine !== "object") {
                                              match = [
                                                stringOption(form.producer),
                                                form.wineName,
                                                vintage,
                                                stringOption(form.style),
                                                stringOption(form.grape),
                                                stringOption(form.region),
                                                stringOption(form.country)
                                              ];
                                            } else {
                                              var wine$1 = wine._0;
                                              match = [
                                                wine$1.producer,
                                                wine$1.name,
                                                wine$1.vintage,
                                                wine$1.style,
                                                wine$1.grape,
                                                wine$1.region,
                                                wine$1.country
                                              ];
                                            }
                                            var venueName = stringOption(form.venueName);
                                            var locationText = stringOption(form.locationText);
                                            var pairingNotes = stringOption(form.pairingNotes);
                                            var tastingNotes = stringOption(form.tastingNotes);
                                            return Js_promise2.then(EntryApi.createEntry(token, collectionId, match[0], match[1], match[2], match[3], match[4], match[5], match[6], consumedAt, venueName, locationText, pairingNotes, tastingNotes, rating, undefined), (function (response) {
                                                          var entry = Belt_Option.flatMap(ResponseDecoder.parse(response), ResponseDecoder.entry);
                                                          if (entry !== undefined) {
                                                            return Promise.resolve(entry);
                                                          } else {
                                                            return Promise.reject(ApiClient.invalidResponse());
                                                          }
                                                        }));
                                          }));
                            }));
              }));
}

function updateEntry(token, collectionId, entryId, form) {
  return Js_promise2.then(normalizeConsumedAt(form.consumedAt), (function (consumedAt) {
                return Js_promise2.then(intOption(form.vintage, "invalid_wine_vintage"), (function (vintage) {
                              return Js_promise2.then(intOption(form.rating, "invalid_rating"), (function (rating) {
                                            var producer = stringOption(form.producer);
                                            var style = stringOption(form.style);
                                            var grape = stringOption(form.grape);
                                            var region = stringOption(form.region);
                                            var country = stringOption(form.country);
                                            var venueName = stringOption(form.venueName);
                                            var locationText = stringOption(form.locationText);
                                            var pairingNotes = stringOption(form.pairingNotes);
                                            var tastingNotes = stringOption(form.tastingNotes);
                                            return Js_promise2.then(EntryApi.updateEntry(token, collectionId, entryId, producer, form.wineName, vintage, style, grape, region, country, consumedAt, venueName, locationText, pairingNotes, tastingNotes, rating, undefined), (function (response) {
                                                          var entry = Belt_Option.flatMap(ResponseDecoder.parse(response), ResponseDecoder.entry);
                                                          if (entry !== undefined) {
                                                            return Promise.resolve(entry);
                                                          } else {
                                                            return Promise.reject(ApiClient.invalidResponse());
                                                          }
                                                        }));
                                          }));
                            }));
              }));
}

var initialForm = {
  wineSource: "NewWine",
  wineName: "",
  producer: "",
  style: "",
  grape: "",
  region: "",
  country: "",
  vintage: "",
  consumedAt: "",
  venueName: "",
  locationText: "",
  pairingNotes: "",
  tastingNotes: "",
  rating: "",
  isSubmitting: false,
  error: undefined,
  success: undefined
};

export {
  initialStatus ,
  loadingStatus ,
  emptyStatus ,
  readyStatus ,
  errorStatus ,
  initialForm ,
  updateForm ,
  startSubmitting ,
  failForm ,
  succeedForm ,
  padTwo ,
  toDateTimeLocalValue ,
  formFromEntry ,
  formFromWineSummary ,
  useNewWine ,
  useExistingWine ,
  entries ,
  selectedEntry ,
  resolveSelectedEntryId ,
  appendEntry ,
  replaceEntry ,
  isReady ,
  stringOption ,
  intOption ,
  normalizeConsumedAt ,
  listEntries ,
  createEntry ,
  updateEntry ,
}
/* EntryApi Not a pure module */
