// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as I18nContext from "../i18n/I18nContext.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function detailLine(label, value) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("dt", {
                      children: label,
                      className: "text-xs font-medium uppercase tracking-[0.2em] text-stone-500"
                    }),
                JsxRuntime.jsx("dd", {
                      children: value,
                      className: "mt-1 text-sm leading-6 text-stone-700"
                    })
              ]
            });
}

function optionalDetailLine(label, value) {
  if (value !== undefined) {
    return Caml_option.some(detailLine(label, value));
  }
  
}

function wineSummary(entry) {
  var parts = Belt_Array.keepMap([
        entry.wine.producer,
        entry.wine.name,
        Belt_Option.map(entry.wine.vintage, (function (prim) {
                return String(prim);
              }))
      ], (function (value) {
          return value;
        }));
  return parts.join(" · ");
}

function EntryDetail(props) {
  var onEdit = props.onEdit;
  var entry = props.entry;
  var t = I18nContext.useT();
  if (entry === undefined) {
    return JsxRuntime.jsxs("section", {
                children: [
                  JsxRuntime.jsx("h3", {
                        children: t.entryDetailHeading,
                        className: "text-lg font-semibold text-stone-950"
                      }),
                  JsxRuntime.jsx("p", {
                        children: t.entryDetailEmptyBody,
                        className: "mt-2 text-sm leading-6 text-stone-600"
                      })
                ],
                className: "rounded-[1.75rem] border border-dashed border-stone-300 bg-stone-50/80 p-6"
              });
  }
  var rating = entry.rating;
  var value = entry.consumedAt;
  return JsxRuntime.jsxs("section", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("p", {
                                      children: t.entryDetailHeading,
                                      className: "text-xs font-medium uppercase tracking-[0.25em] text-stone-500"
                                    }),
                                JsxRuntime.jsx("h3", {
                                      children: wineSummary(entry),
                                      className: "mt-2 text-2xl font-semibold text-stone-950"
                                    })
                              ]
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                rating !== undefined ? JsxRuntime.jsx("span", {
                                        children: t.rating(rating),
                                        className: "rounded-full border border-amber-300 bg-amber-50 px-3 py-1 text-xs font-semibold uppercase tracking-[0.2em] text-amber-800"
                                      }) : null,
                                JsxRuntime.jsx("button", {
                                      children: t.entryDetailEditEntry,
                                      className: "rounded-2xl border border-stone-300 px-4 py-2 text-sm font-medium text-stone-700 transition hover:border-stone-500 hover:text-stone-950",
                                      type: "button",
                                      onClick: (function (param) {
                                          onEdit();
                                        })
                                    })
                              ],
                              className: "flex flex-col items-start gap-3 md:items-end"
                            })
                      ],
                      className: "flex flex-col gap-4 md:flex-row md:items-start md:justify-between"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("section", {
                              children: [
                                JsxRuntime.jsx("h4", {
                                      children: t.entryDetailWineLabel,
                                      className: "text-sm font-semibold uppercase tracking-[0.2em] text-stone-600"
                                    }),
                                JsxRuntime.jsxs("dl", {
                                      children: [
                                        detailLine(t.wineDetailNameLabel, entry.wine.name),
                                        Belt_Option.getWithDefault(optionalDetailLine(t.wineComposerProducerLabel, entry.wine.producer), null),
                                        Belt_Option.getWithDefault(optionalDetailLine(t.wineComposerVintageLabel, Belt_Option.map(entry.wine.vintage, (function (prim) {
                                                        return String(prim);
                                                      }))), null),
                                        Belt_Option.getWithDefault(optionalDetailLine(t.wineComposerStyleLabel, entry.wine.style), null),
                                        Belt_Option.getWithDefault(optionalDetailLine(t.wineComposerGrapeLabel, entry.wine.grape), null),
                                        Belt_Option.getWithDefault(optionalDetailLine(t.wineComposerRegionLabel, entry.wine.region), null),
                                        Belt_Option.getWithDefault(optionalDetailLine(t.wineComposerCountryLabel, entry.wine.country), null)
                                      ],
                                      className: "mt-4 grid gap-4"
                                    })
                              ],
                              className: "rounded-2xl border border-stone-200 bg-white p-5"
                            }),
                        JsxRuntime.jsxs("section", {
                              children: [
                                JsxRuntime.jsx("h4", {
                                      children: t.entryDetailOccasionLabel,
                                      className: "text-sm font-semibold uppercase tracking-[0.2em] text-stone-600"
                                    }),
                                JsxRuntime.jsxs("dl", {
                                      children: [
                                        value !== undefined ? detailLine(t.entryComposerConsumedAtLabel, value.slice(0, 10)) : null,
                                        Belt_Option.getWithDefault(optionalDetailLine(t.entryComposerVenueLabel, entry.venueName), null),
                                        Belt_Option.getWithDefault(optionalDetailLine(t.entryComposerLocationLabel, entry.locationText), null),
                                        Belt_Option.getWithDefault(optionalDetailLine(t.entryComposerPairingNotesLabel, entry.pairingNotes), null),
                                        Belt_Option.getWithDefault(optionalDetailLine(t.entryComposerTastingNotesLabel, entry.tastingNotes), null)
                                      ],
                                      className: "mt-4 grid gap-4"
                                    })
                              ],
                              className: "rounded-2xl border border-stone-200 bg-white p-5"
                            })
                      ],
                      className: "mt-6 grid gap-6 md:grid-cols-2"
                    })
              ],
              className: "rounded-[1.75rem] border border-stone-900/10 bg-stone-50/80 p-6"
            });
}

var make = EntryDetail;

export {
  detailLine ,
  optionalDetailLine ,
  wineSummary ,
  make ,
}
/* I18nContext Not a pure module */
