// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as JsxRuntime from "react/jsx-runtime";

function wineLabel(entry) {
  var producer = entry.wine.producer;
  if (producer !== undefined) {
    return producer + " " + entry.wine.name;
  } else {
    return entry.wine.name;
  }
}

function wineMeta(entry) {
  var segments = Belt_Array.keepMap([
        Belt_Option.map(entry.wine.vintage, (function (prim) {
                return String(prim);
              })),
        entry.locationText,
        entry.venueName
      ], (function (value) {
          return value;
        }));
  if (segments.length === 0) {
    return ;
  } else {
    return segments.join(" · ");
  }
}

function EntryHistory(props) {
  var status = props.status;
  if (typeof status !== "object") {
    if (status === "Idle") {
      return JsxRuntime.jsxs("section", {
                  children: [
                    JsxRuntime.jsx("h3", {
                          children: "Entry history",
                          className: "text-lg font-semibold text-stone-950"
                        }),
                    JsxRuntime.jsx("p", {
                          children: "Select a collection to browse its entries.",
                          className: "mt-2 text-sm leading-6 text-stone-600"
                        })
                  ],
                  className: "rounded-[1.75rem] border border-dashed border-stone-300 bg-stone-50/80 p-6"
                });
    } else {
      return JsxRuntime.jsxs("section", {
                  children: [
                    JsxRuntime.jsx("h3", {
                          children: "Entry history",
                          className: "text-lg font-semibold text-stone-950"
                        }),
                    JsxRuntime.jsx("p", {
                          children: "Loading collection history...",
                          className: "mt-2 text-sm text-stone-600"
                        })
                  ],
                  className: "rounded-[1.75rem] border border-stone-900/10 bg-stone-50/80 p-6"
                });
    }
  }
  if (status.TAG !== "Ready") {
    return JsxRuntime.jsxs("section", {
                children: [
                  JsxRuntime.jsx("h3", {
                        children: "Entry history",
                        className: "text-lg font-semibold text-rose-900"
                      }),
                  JsxRuntime.jsx("p", {
                        children: status._0,
                        className: "mt-2 text-sm text-rose-700"
                      })
                ],
                className: "rounded-[1.75rem] border border-rose-200 bg-rose-50 p-6"
              });
  }
  var entries = status._0;
  if (entries.length === 0) {
    return JsxRuntime.jsxs("section", {
                children: [
                  JsxRuntime.jsx("h3", {
                        children: "Entry history",
                        className: "text-lg font-semibold text-stone-950"
                      }),
                  JsxRuntime.jsx("p", {
                        children: "No entries yet. Your latest bottles and notes will show up here.",
                        className: "mt-2 text-sm leading-6 text-stone-600"
                      })
                ],
                className: "rounded-[1.75rem] border border-dashed border-stone-300 bg-stone-50/80 p-6"
              });
  } else {
    return JsxRuntime.jsxs("section", {
                children: [
                  JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsx("h3", {
                                children: "Entry history",
                                className: "text-lg font-semibold text-stone-950"
                              }),
                          JsxRuntime.jsx("span", {
                                children: String(entries.length) + " entries",
                                className: "rounded-full border border-stone-300 px-3 py-1 text-xs font-medium uppercase tracking-[0.2em] text-stone-600"
                              })
                        ],
                        className: "flex items-center justify-between gap-4"
                      }),
                  JsxRuntime.jsx("ul", {
                        children: Belt_Array.map(entries, (function (entry) {
                                var meta = wineMeta(entry);
                                var rating = entry.rating;
                                var notes = entry.tastingNotes;
                                var notes$1 = entry.pairingNotes;
                                return JsxRuntime.jsxs("li", {
                                            children: [
                                              JsxRuntime.jsxs("div", {
                                                    children: [
                                                      JsxRuntime.jsxs("div", {
                                                            children: [
                                                              JsxRuntime.jsx("p", {
                                                                    children: wineLabel(entry),
                                                                    className: "text-base font-semibold text-stone-950"
                                                                  }),
                                                              meta !== undefined ? JsxRuntime.jsx("p", {
                                                                      children: meta,
                                                                      className: "mt-1 text-sm text-stone-600"
                                                                    }) : null
                                                            ]
                                                          }),
                                                      rating !== undefined ? JsxRuntime.jsx("span", {
                                                              children: String(rating) + "/5",
                                                              className: "rounded-full border border-amber-300 bg-amber-50 px-3 py-1 text-xs font-semibold uppercase tracking-[0.2em] text-amber-800"
                                                            }) : null
                                                    ],
                                                    className: "flex items-start justify-between gap-4"
                                                  }),
                                              JsxRuntime.jsx("p", {
                                                    children: entry.consumedAt,
                                                    className: "mt-3 text-xs font-medium uppercase tracking-[0.2em] text-stone-500"
                                                  }),
                                              notes !== undefined ? JsxRuntime.jsx("p", {
                                                      children: notes,
                                                      className: "mt-3 text-sm leading-6 text-stone-700"
                                                    }) : null,
                                              notes$1 !== undefined ? JsxRuntime.jsxs("p", {
                                                      children: [
                                                        JsxRuntime.jsx("span", {
                                                              children: "Pairing: ",
                                                              className: "font-medium text-stone-800"
                                                            }),
                                                        notes$1
                                                      ],
                                                      className: "mt-2 text-sm leading-6 text-stone-600"
                                                    }) : null
                                            ],
                                            className: "rounded-2xl border border-stone-200 bg-white p-4 shadow-sm"
                                          }, String(entry.id));
                              })),
                        className: "mt-4 space-y-3"
                      })
                ],
                className: "rounded-[1.75rem] border border-stone-900/10 bg-stone-50/80 p-6"
              });
  }
}

var make = EntryHistory;

export {
  wineLabel ,
  wineMeta ,
  make ,
}
/* react/jsx-runtime Not a pure module */
