// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ApiClient from "../api/ApiClient.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function stringify(value) {
  return Belt_Option.getExn(JSON.stringify(value));
}

function buildEntryBody(wine, consumedAt, venueName, locationText, pairingNotes, tastingNotes, rating) {
  var payload = {};
  payload["wine"] = wine;
  payload["consumed_at"] = Belt_Option.mapWithDefault(consumedAt, null, (function (prim) {
          return prim;
        }));
  payload["venue_name"] = Belt_Option.mapWithDefault(venueName, null, (function (prim) {
          return prim;
        }));
  payload["location_text"] = Belt_Option.mapWithDefault(locationText, null, (function (prim) {
          return prim;
        }));
  payload["pairing_notes"] = Belt_Option.mapWithDefault(pairingNotes, null, (function (prim) {
          return prim;
        }));
  payload["tasting_notes"] = Belt_Option.mapWithDefault(tastingNotes, null, (function (prim) {
          return prim;
        }));
  payload["rating"] = Belt_Option.mapWithDefault(rating, null, (function (n) {
          return n;
        }));
  return Belt_Option.getExn(JSON.stringify(payload));
}

function listEntries(token, collectionId) {
  return ApiClient.request("/api/collections/" + String(collectionId) + "/entries", {
              headers: ApiClient.authHeaders(token, {})
            });
}

function createEntry(token, collectionId, producer, name, vintage, style, grape, region, country, consumedAt, venueName, locationText, pairingNotes, tastingNotes, rating, param) {
  return ApiClient.request("/api/collections/" + String(collectionId) + "/entries", {
              method: "POST",
              headers: ApiClient.authHeaders(token, ApiClient.jsonHeaders),
              body: buildEntryBody({
                    producer: producer,
                    name: name,
                    vintage: vintage,
                    style: style,
                    grape: grape,
                    region: region,
                    country: country
                  }, consumedAt, venueName, locationText, pairingNotes, tastingNotes, rating)
            });
}

function updateEntry(token, collectionId, entryId, producer, name, vintage, style, grape, region, country, consumedAt, venueName, locationText, pairingNotes, tastingNotes, rating, param) {
  return ApiClient.request("/api/collections/" + String(collectionId) + "/entries/" + String(entryId), {
              method: "PATCH",
              headers: ApiClient.authHeaders(token, ApiClient.jsonHeaders),
              body: buildEntryBody({
                    producer: producer,
                    name: name,
                    vintage: vintage,
                    style: style,
                    grape: grape,
                    region: region,
                    country: country
                  }, consumedAt, venueName, locationText, pairingNotes, tastingNotes, rating)
            });
}

export {
  stringify ,
  buildEntryBody ,
  listEntries ,
  createEntry ,
  updateEntry ,
}
/* ApiClient Not a pure module */
