// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Router from "./router/Router.bs.js";
import * as AppShell from "./AppShell.bs.js";
import * as AuthCard from "./auth/AuthCard.bs.js";
import * as AuthForm from "./auth/AuthForm.bs.js";
import * as WineState from "./wines/WineState.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as EntryState from "./entries/EntryState.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Js_promise2 from "rescript/lib/es6/js_promise2.js";
import * as WineCapture from "./wines/WineCapture.bs.js";
import * as AuthAppSupport from "./auth/AuthAppSupport.bs.js";
import * as SessionStorage from "./auth/SessionStorage.bs.js";
import * as SessionBootstrap from "./auth/SessionBootstrap.bs.js";
import * as Js_null_undefined from "rescript/lib/es6/js_null_undefined.js";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var route = Router.useRoute();
  var match = React.useState(function () {
        return AuthForm.loginMode;
      });
  var setMode = match[1];
  var mode = match[0];
  var match$1 = React.useState(function () {
        return AuthForm.initialForm;
      });
  var setForm = match$1[1];
  var form = match$1[0];
  var match$2 = React.useState(function () {
        
      });
  var setCurrentUser = match$2[1];
  var currentUser = match$2[0];
  var match$3 = React.useState(function () {
        
      });
  var setSessionToken = match$3[1];
  var sessionToken = match$3[0];
  var match$4 = React.useState(function () {
        return true;
      });
  var setIsInitializing = match$4[1];
  var match$5 = React.useState(function () {
        return false;
      });
  var setIsSubmitting = match$5[1];
  var match$6 = React.useState(function () {
        
      });
  var setError = match$6[1];
  var match$7 = React.useState(function () {
        return WineState.initialStatus();
      });
  var setWineStatus = match$7[1];
  var wineStatus = match$7[0];
  var match$8 = React.useState(function () {
        return WineCapture.initialForm;
      });
  var setWineForm = match$8[1];
  var wineForm = match$8[0];
  var match$9 = React.useState(function () {
        return WineState.initialOccasionFilter;
      });
  var setWineOccasionFilter = match$9[1];
  var wineOccasionFilter = match$9[0];
  var match$10 = React.useState(function () {
        return "";
      });
  var setWineQuery = match$10[1];
  var wineQuery = match$10[0];
  var match$11 = React.useState(function () {
        return EntryState.initialStatus();
      });
  var setEntryStatus = match$11[1];
  var match$12 = React.useState(function () {
        return EntryState.initialForm;
      });
  var setEntryForm = match$12[1];
  var entryForm = match$12[0];
  var defaultCollectionId = Belt_Option.map(currentUser, (function (user) {
          return user.defaultCollectionId;
        }));
  React.useEffect((function () {
          var restoredToken = SessionBootstrap.loadSessionToken();
          if (restoredToken !== undefined) {
            Js_promise2.$$catch(Js_promise2.then(SessionBootstrap.restoreSession(restoredToken), (function (restoredSession) {
                        setSessionToken(function (param) {
                              return restoredSession.sessionToken;
                            });
                        setCurrentUser(function (param) {
                              return restoredSession.user;
                            });
                        setIsInitializing(function (param) {
                              return false;
                            });
                        return Promise.resolve();
                      })), (function (param) {
                    SessionStorage.clearSessionToken();
                    setSessionToken(function (param) {
                          
                        });
                    setCurrentUser(function (param) {
                          
                        });
                    setIsInitializing(function (param) {
                          return false;
                        });
                    return Promise.resolve();
                  }));
          } else {
            setIsInitializing(function (param) {
                  return false;
                });
          }
        }), []);
  React.useEffect((function () {
          var exit = 0;
          if (sessionToken !== undefined && defaultCollectionId !== undefined) {
            setWineStatus(function (param) {
                  return WineState.loadingStatus();
                });
            Js_promise2.$$catch(Js_promise2.then(WineState.listWines(sessionToken, defaultCollectionId), (function (wines) {
                        setWineStatus(function (param) {
                              return WineState.readyStatus(wines);
                            });
                        return Promise.resolve();
                      })), (function (param) {
                    setWineStatus(function (param) {
                          return WineState.errorStatus(AuthAppSupport.describeEntryHistoryError());
                        });
                    return Promise.resolve();
                  }));
            setEntryStatus(function (param) {
                  return EntryState.loadingStatus();
                });
            Js_promise2.$$catch(Js_promise2.then(EntryState.listEntries(sessionToken, defaultCollectionId), (function (entries) {
                        setEntryStatus(function (param) {
                              return EntryState.readyStatus(entries);
                            });
                        return Promise.resolve();
                      })), (function (param) {
                    setEntryStatus(function (param) {
                          return EntryState.errorStatus(AuthAppSupport.describeEntryHistoryError());
                        });
                    return Promise.resolve();
                  }));
          } else {
            exit = 1;
          }
          if (exit === 1) {
            setWineStatus(function (param) {
                  return WineState.initialStatus();
                });
            setEntryStatus(function (param) {
                  return EntryState.initialStatus();
                });
          }
          
        }), [
        sessionToken,
        defaultCollectionId
      ]);
  var updateForm = function (field, value) {
    setForm(function (current) {
          return AuthForm.updateForm(current, field, value);
        });
    setError(function (param) {
          
        });
  };
  var handleModeChange = function (nextMode) {
    setMode(function (param) {
          return nextMode;
        });
    setError(function (param) {
          
        });
  };
  var updateEntryForm = function (field, value) {
    setEntryForm(function (current) {
          return EntryState.updateForm(current, field, value);
        });
  };
  var updateWineForm = function (field, value) {
    setWineForm(function (current) {
          return WineCapture.updateForm(current, field, value);
        });
  };
  var handleSubmit = function ($$event) {
    $$event.preventDefault();
    setIsSubmitting(function (param) {
          return true;
        });
    setError(function (param) {
          
        });
    Js_promise2.$$catch(Js_promise2.then(AuthForm.submit(mode, form), (function (payload) {
                SessionStorage.saveSessionToken(payload.token);
                setSessionToken(function (param) {
                      return payload.token;
                    });
                setCurrentUser(function (param) {
                      return payload.user;
                    });
                setForm(function (param) {
                      return AuthForm.initialForm;
                    });
                setIsSubmitting(function (param) {
                      return false;
                    });
                return Promise.resolve();
              })), (function (reason) {
            setError(function (param) {
                  return AuthAppSupport.describeError(reason);
                });
            setIsSubmitting(function (param) {
                  return false;
                });
            return Promise.resolve();
          }));
  };
  var handleLogout = function () {
    SessionStorage.clearSessionToken();
    setSessionToken(function (param) {
          
        });
    setCurrentUser(function (param) {
          
        });
    setWineStatus(function (param) {
          return WineState.initialStatus();
        });
    setWineForm(function (param) {
          return WineCapture.initialForm;
        });
    setEntryStatus(function (param) {
          return EntryState.initialStatus();
        });
    setEntryForm(function (param) {
          return EntryState.initialForm;
        });
    setError(function (param) {
          
        });
    setMode(function (param) {
          return AuthForm.loginMode;
        });
    Router.navigate("Home");
  };
  var useSelectedWineForEntry = function () {
    if (typeof route !== "object") {
      return ;
    }
    switch (route.TAG) {
      case "NewEntry" :
      case "EditEntry" :
          break;
      default:
        return ;
    }
    var wineId = route._0;
    var summary = Belt_Array.getBy(WineState.wines(wineStatus), (function (summary) {
            return summary.wine.id === wineId;
          }));
    if (summary !== undefined) {
      return setEntryForm(function (current) {
                  return EntryState.useExistingWine(current, summary.wine);
                });
    }
    
  };
  var useNewWineForEntry = function () {
    setEntryForm(function (current) {
          return EntryState.useNewWine(current);
        });
  };
  var handleCreateWine = function () {
    if (sessionToken !== undefined && defaultCollectionId !== undefined && !wineForm.isSubmitting) {
      setWineForm(function (current) {
            return WineCapture.startSubmitting(current);
          });
      Js_promise2.$$catch(Js_promise2.then(WineCapture.createWine(sessionToken, defaultCollectionId, wineForm), (function (summary) {
                  Js_promise2.then(WineState.listWines(sessionToken, defaultCollectionId), (function (wines) {
                          setWineStatus(function (param) {
                                return WineState.readyStatus(wines);
                              });
                          return Promise.resolve();
                        }));
                  setWineForm(function (param) {
                        return WineCapture.initialForm;
                      });
                  Router.navigate({
                        TAG: "Wine",
                        _0: summary.wine.id
                      });
                  return Promise.resolve();
                })), (function (reason) {
              setWineForm(function (current) {
                    return WineCapture.failForm(current, AuthAppSupport.describeWineError(reason));
                  });
              return Promise.resolve();
            }));
      return ;
    }
    
  };
  var handleCreateEntry = function () {
    if (sessionToken === undefined) {
      return ;
    }
    if (defaultCollectionId === undefined) {
      return ;
    }
    if (typeof route !== "object") {
      return ;
    }
    switch (route.TAG) {
      case "NewEntry" :
          if (entryForm.isSubmitting) {
            return ;
          }
          var wineId = route._0;
          setEntryForm(function (current) {
                return EntryState.startSubmitting(current);
              });
          Js_promise2.$$catch(Js_promise2.then(EntryState.createEntry(sessionToken, defaultCollectionId, entryForm), (function (entry) {
                      Js_promise2.then(WineState.listWines(sessionToken, defaultCollectionId), (function (wines) {
                              setWineStatus(function (param) {
                                    return WineState.readyStatus(wines);
                                  });
                              return Promise.resolve();
                            }));
                      setEntryStatus(function (current) {
                            if (EntryState.isReady(current)) {
                              return EntryState.readyStatus(EntryState.appendEntry(EntryState.entries(current), entry));
                            } else {
                              return current;
                            }
                          });
                      setEntryForm(function (param) {
                            return EntryState.succeedForm();
                          });
                      Router.navigate({
                            TAG: "Wine",
                            _0: wineId
                          });
                      return Promise.resolve();
                    })), (function (reason) {
                  setEntryForm(function (current) {
                        return EntryState.failForm(current, AuthAppSupport.describeEntryError(reason));
                      });
                  return Promise.resolve();
                }));
          return ;
      case "EditEntry" :
          if (entryForm.isSubmitting) {
            return ;
          }
          var wineId$1 = route._0;
          setEntryForm(function (current) {
                return EntryState.startSubmitting(current);
              });
          Js_promise2.$$catch(Js_promise2.then(EntryState.updateEntry(sessionToken, defaultCollectionId, route._1, entryForm), (function (entry) {
                      Js_promise2.then(WineState.listWines(sessionToken, defaultCollectionId), (function (wines) {
                              setWineStatus(function (param) {
                                    return WineState.readyStatus(wines);
                                  });
                              return Promise.resolve();
                            }));
                      setEntryStatus(function (current) {
                            if (EntryState.isReady(current)) {
                              return EntryState.readyStatus(EntryState.replaceEntry(EntryState.entries(current), entry));
                            } else {
                              return current;
                            }
                          });
                      setEntryForm(function (param) {
                            return EntryState.succeedForm();
                          });
                      Router.navigate({
                            TAG: "Wine",
                            _0: wineId$1
                          });
                      return Promise.resolve();
                    })), (function (reason) {
                  setEntryForm(function (current) {
                        return EntryState.failForm(current, AuthAppSupport.describeEntryError(reason));
                      });
                  return Promise.resolve();
                }));
          return ;
      default:
        return ;
    }
  };
  var openEntryEditor = function () {
    
  };
  var visibleWineStatus = WineState.filterStatus(wineStatus, wineQuery, wineOccasionFilter);
  return JsxRuntime.jsx("main", {
              children: JsxRuntime.jsx("div", {
                    children: match$4[0] ? JsxRuntime.jsx("section", {
                            children: "Checking your session...",
                            className: "w-full max-w-md rounded-3xl border border-stone-900/10 bg-white/80 p-8 text-sm text-stone-600 shadow-xl backdrop-blur"
                          }) : (
                        currentUser !== undefined ? JsxRuntime.jsx(AppShell.make, {
                                user: currentUser,
                                route: route,
                                wineStatus: visibleWineStatus,
                                wineForm: wineForm,
                                wineOccasionFilter: wineOccasionFilter,
                                wineQuery: wineQuery,
                                totalWineCount: WineState.wines(wineStatus).length,
                                entryStatus: match$11[0],
                                entryForm: entryForm,
                                onEntryFormChange: updateEntryForm,
                                onUseSelectedWineForEntry: useSelectedWineForEntry,
                                onUseNewWineForEntry: useNewWineForEntry,
                                onWineFormChange: updateWineForm,
                                onCreateWine: handleCreateWine,
                                onCreateEntry: handleCreateEntry,
                                onEditEntry: openEntryEditor,
                                onWineQueryChange: (function (query) {
                                    setWineQuery(function (param) {
                                          return query;
                                        });
                                  }),
                                onSelectOccasionFilter: (function (filter) {
                                    setWineOccasionFilter(function (param) {
                                          return filter;
                                        });
                                  }),
                                onLogout: handleLogout
                              }) : JsxRuntime.jsx(AuthCard.make, {
                                mode: mode,
                                onModeChange: handleModeChange,
                                form: form,
                                onFormChange: updateForm,
                                onSubmit: handleSubmit,
                                isSubmitting: match$5[0],
                                error: Js_null_undefined.fromOption(match$6[0])
                              })
                      ),
                    className: "mx-auto flex min-h-[calc(100vh-6rem)] max-w-5xl items-center justify-center"
                  }),
              className: "min-h-screen bg-[radial-gradient(circle_at_top,_rgba(234,214,196,0.9),_transparent_45%),linear-gradient(180deg,_#f7efe7_0%,_#ead9ca_100%)] px-6 py-12 text-stone-950"
            });
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
