// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsx("main", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("p", {
                            children: "Wine",
                            className: "eyebrow"
                          }),
                      JsxRuntime.jsx("h1", {
                            children: "Scaffold is wired up."
                          }),
                      JsxRuntime.jsx("p", {
                            children: "Backend health endpoint: http://127.0.0.1:3000/api/health",
                            className: "body"
                          })
                    ],
                    className: "hero"
                  }),
              className: "app-shell"
            });
}

var make = App;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
