// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as AppShell from "./AppShell.bs.js";
import * as AuthCard from "./auth/AuthCard.bs.js";
import * as AuthForm from "./auth/AuthForm.bs.js";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as EntryState from "./entries/EntryState.bs.js";
import * as Js_promise2 from "rescript/lib/es6/js_promise2.js";
import * as AuthAppSupport from "./auth/AuthAppSupport.bs.js";
import * as SessionStorage from "./auth/SessionStorage.bs.js";
import * as CollectionModel from "./collections/CollectionModel.bs.js";
import * as CollectionState from "./collections/CollectionState.bs.js";
import * as CollectionInvite from "./collections/CollectionInvite.bs.js";
import * as SessionBootstrap from "./auth/SessionBootstrap.bs.js";
import * as Js_null_undefined from "rescript/lib/es6/js_null_undefined.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as CollectionSelectionStorage from "./collections/CollectionSelectionStorage.bs.js";

function App(props) {
  var match = React.useState(function () {
        return AuthForm.loginMode;
      });
  var setMode = match[1];
  var mode = match[0];
  var match$1 = React.useState(function () {
        return AuthForm.initialForm;
      });
  var setForm = match$1[1];
  var form = match$1[0];
  var match$2 = React.useState(function () {
        
      });
  var setCurrentUser = match$2[1];
  var currentUser = match$2[0];
  var match$3 = React.useState(function () {
        
      });
  var setSessionToken = match$3[1];
  var sessionToken = match$3[0];
  var match$4 = React.useState(function () {
        return true;
      });
  var setIsInitializing = match$4[1];
  var match$5 = React.useState(function () {
        return false;
      });
  var setIsSubmitting = match$5[1];
  var match$6 = React.useState(function () {
        
      });
  var setError = match$6[1];
  var match$7 = React.useState(function () {
        return CollectionState.initialCollectionStatus();
      });
  var setCollectionStatus = match$7[1];
  var collectionStatus = match$7[0];
  var match$8 = React.useState(function () {
        
      });
  var setSelectedCollectionId = match$8[1];
  var selectedCollectionId = match$8[0];
  var match$9 = React.useState(function () {
        return CollectionState.initialCollectionForm;
      });
  var setCollectionForm = match$9[1];
  var collectionForm = match$9[0];
  var match$10 = React.useState(function () {
        return CollectionInvite.initialForm;
      });
  var setInviteForm = match$10[1];
  var inviteForm = match$10[0];
  var match$11 = React.useState(function () {
        return EntryState.initialStatus();
      });
  var setEntryStatus = match$11[1];
  var entryStatus = match$11[0];
  var match$12 = React.useState(function () {
        return EntryState.initialForm;
      });
  var setEntryForm = match$12[1];
  var entryForm = match$12[0];
  var match$13 = React.useState(function () {
        
      });
  var setSelectedEntryId = match$13[1];
  var selectedEntryId = match$13[0];
  var match$14 = React.useState(function () {
        
      });
  var setEntryComposerMode = match$14[1];
  var entryComposerMode = match$14[0];
  React.useEffect((function () {
          var restoredToken = SessionBootstrap.loadSessionToken();
          if (restoredToken !== undefined) {
            Js_promise2.$$catch(Js_promise2.then(SessionBootstrap.restoreSession(restoredToken), (function (restoredSession) {
                        setSessionToken(function (param) {
                              return restoredSession.sessionToken;
                            });
                        setCurrentUser(function (param) {
                              return restoredSession.user;
                            });
                        setIsInitializing(function (param) {
                              return false;
                            });
                        return Promise.resolve();
                      })), (function (param) {
                    SessionStorage.clearSessionToken();
                    setSessionToken(function (param) {
                          
                        });
                    setCurrentUser(function (param) {
                          
                        });
                    setCollectionStatus(function (param) {
                          return CollectionState.emptyCollectionStatus();
                        });
                    setSelectedCollectionId(function (param) {
                          
                        });
                    setEntryStatus(function (param) {
                          return EntryState.initialStatus();
                        });
                    setEntryForm(function (param) {
                          return EntryState.initialForm;
                        });
                    setSelectedEntryId(function (param) {
                          
                        });
                    setEntryComposerMode(function (param) {
                          
                        });
                    setIsInitializing(function (param) {
                          return false;
                        });
                    return Promise.resolve();
                  }));
          } else {
            setSessionToken(function (param) {
                  
                });
            setCollectionStatus(function (param) {
                  return CollectionState.emptyCollectionStatus();
                });
            setSelectedCollectionId(function (param) {
                  
                });
            setEntryStatus(function (param) {
                  return EntryState.initialStatus();
                });
            setEntryForm(function (param) {
                  return EntryState.initialForm;
                });
            setSelectedEntryId(function (param) {
                  
                });
            setEntryComposerMode(function (param) {
                  
                });
            setIsInitializing(function (param) {
                  return false;
                });
          }
        }), []);
  React.useEffect((function () {
          var exit = 0;
          if (currentUser !== undefined && sessionToken !== undefined) {
            setCollectionStatus(function (param) {
                  return CollectionState.loadingCollectionStatus();
                });
            Js_promise2.$$catch(Js_promise2.then(CollectionState.listCollections(sessionToken), (function (collections) {
                        setCollectionStatus(function (param) {
                              return CollectionState.readyCollectionStatus(collections);
                            });
                        return Promise.resolve();
                      })), (function (param) {
                    setCollectionStatus(function (param) {
                          return CollectionState.errorCollectionStatus(AuthAppSupport.describeCollectionError());
                        });
                    return Promise.resolve();
                  }));
          } else {
            exit = 1;
          }
          if (exit === 1) {
            setCollectionStatus(function (param) {
                  return CollectionState.emptyCollectionStatus();
                });
            setSelectedCollectionId(function (param) {
                  
                });
            setEntryStatus(function (param) {
                  return EntryState.initialStatus();
                });
            setSelectedEntryId(function (param) {
                  
                });
            setEntryComposerMode(function (param) {
                  
                });
          }
          
        }), [
        currentUser,
        sessionToken
      ]);
  React.useEffect((function () {
          if (CollectionState.isReady(collectionStatus)) {
            var collections = CollectionState.collections(collectionStatus);
            if (collections.length === 0) {
              setSelectedCollectionId(function (param) {
                    
                  });
              CollectionSelectionStorage.clearSelectedCollectionId();
            } else {
              var nextSelectedCollectionId = CollectionState.resolveSelectedCollectionId(collections, selectedCollectionId, CollectionSelectionStorage.loadSelectedCollectionId());
              if (Caml_obj.notequal(nextSelectedCollectionId, selectedCollectionId)) {
                setSelectedCollectionId(function (param) {
                      return nextSelectedCollectionId;
                    });
                if (nextSelectedCollectionId !== undefined) {
                  CollectionSelectionStorage.saveSelectedCollectionId(nextSelectedCollectionId);
                } else {
                  CollectionSelectionStorage.clearSelectedCollectionId();
                }
              }
              
            }
          }
          
        }), [
        collectionStatus,
        selectedCollectionId
      ]);
  var updateForm = function (field, value) {
    setForm(function (current) {
          return AuthForm.updateForm(current, field, value);
        });
    setError(function (param) {
          
        });
  };
  var handleModeChange = function (nextMode) {
    setMode(function (param) {
          return nextMode;
        });
    setError(function (param) {
          
        });
  };
  var updateCollectionForm = function (value) {
    setCollectionForm(function (current) {
          return CollectionState.updateCollectionForm(current, value);
        });
  };
  var updateInviteForm = function (value) {
    setInviteForm(function (current) {
          return CollectionInvite.updateForm(current, value);
        });
  };
  var updateEntryForm = function (field, value) {
    setEntryForm(function (current) {
          return EntryState.updateForm(current, field, value);
        });
  };
  var handleSubmit = function ($$event) {
    $$event.preventDefault();
    setIsSubmitting(function (param) {
          return true;
        });
    setError(function (param) {
          
        });
    Js_promise2.$$catch(Js_promise2.then(AuthForm.submit(mode, form), (function (payload) {
                var nextSessionToken = payload.token;
                SessionStorage.saveSessionToken(nextSessionToken);
                setSessionToken(function (param) {
                      return nextSessionToken;
                    });
                setCurrentUser(function (param) {
                      return payload.user;
                    });
                setCollectionForm(function (param) {
                      return CollectionState.finishCollectionForm();
                    });
                setInviteForm(function (param) {
                      return CollectionInvite.initialForm;
                    });
                setEntryForm(function (param) {
                      return EntryState.initialForm;
                    });
                setForm(function (param) {
                      return AuthForm.initialForm;
                    });
                setIsSubmitting(function (param) {
                      return false;
                    });
                return Promise.resolve();
              })), (function (reason) {
            setError(function (param) {
                  return AuthAppSupport.describeError(reason);
                });
            setIsSubmitting(function (param) {
                  return false;
                });
            return Promise.resolve();
          }));
  };
  var handleLogout = function () {
    SessionStorage.clearSessionToken();
    setSessionToken(function (param) {
          
        });
    setCurrentUser(function (param) {
          
        });
    setCollectionStatus(function (param) {
          return CollectionState.emptyCollectionStatus();
        });
    setSelectedCollectionId(function (param) {
          
        });
    CollectionSelectionStorage.clearSelectedCollectionId();
    setCollectionForm(function (param) {
          return CollectionState.finishCollectionForm();
        });
    setInviteForm(function (param) {
          return CollectionInvite.initialForm;
        });
    setEntryStatus(function (param) {
          return EntryState.initialStatus();
        });
    setEntryForm(function (param) {
          return EntryState.initialForm;
        });
    setSelectedEntryId(function (param) {
          
        });
    setEntryComposerMode(function (param) {
          
        });
    setError(function (param) {
          
        });
    setMode(function (param) {
          return AuthForm.loginMode;
        });
  };
  var handleCreateCollection = function () {
    if (sessionToken !== undefined && !collectionForm.isSubmitting) {
      setCollectionForm(function (current) {
            return CollectionState.startSubmittingCollectionForm(current);
          });
      Js_promise2.$$catch(Js_promise2.then(CollectionState.createCollection(sessionToken, collectionForm.name), (function (collection) {
                  var nextSelectedCollectionId = collection.id;
                  setSelectedCollectionId(function (param) {
                        return nextSelectedCollectionId;
                      });
                  CollectionSelectionStorage.saveSelectedCollectionId(collection.id);
                  setInviteForm(function (param) {
                        return CollectionInvite.initialForm;
                      });
                  setEntryForm(function (param) {
                        return EntryState.initialForm;
                      });
                  setSelectedEntryId(function (param) {
                        
                      });
                  setEntryComposerMode(function (param) {
                        
                      });
                  setCollectionStatus(function (current) {
                        var collections = CollectionState.isReady(current) ? CollectionState.collections(current) : [];
                        return CollectionState.readyCollectionStatus(CollectionState.appendCollection(collections, collection));
                      });
                  setCollectionForm(function (param) {
                        return CollectionState.finishCollectionForm();
                      });
                  return Promise.resolve();
                })), (function (reason) {
              setCollectionForm(function (current) {
                    return CollectionState.failCollectionForm(current, AuthAppSupport.describeCreateCollectionError(reason));
                  });
              return Promise.resolve();
            }));
      return ;
    }
    
  };
  var handleSelectCollection = function (collectionId) {
    var nextSelectedCollectionId = collectionId;
    setSelectedCollectionId(function (param) {
          return nextSelectedCollectionId;
        });
    CollectionSelectionStorage.saveSelectedCollectionId(collectionId);
    setInviteForm(function (param) {
          return CollectionInvite.initialForm;
        });
    setEntryForm(function (param) {
          return EntryState.initialForm;
        });
    setSelectedEntryId(function (param) {
          
        });
    setEntryComposerMode(function (param) {
          
        });
  };
  var selectedCollection = CollectionState.selectedCollection(CollectionState.collections(collectionStatus), selectedCollectionId);
  var selectedEntry = EntryState.selectedEntry(EntryState.entries(entryStatus), selectedEntryId);
  React.useEffect((function () {
          var exit = 0;
          if (sessionToken !== undefined && selectedCollection !== undefined) {
            setEntryStatus(function (param) {
                  return EntryState.loadingStatus();
                });
            Js_promise2.$$catch(Js_promise2.then(EntryState.listEntries(sessionToken, selectedCollection.id), (function (entries) {
                        setEntryStatus(function (param) {
                              return EntryState.readyStatus(entries);
                            });
                        setSelectedEntryId(function (current) {
                              return EntryState.resolveSelectedEntryId(entries, current);
                            });
                        return Promise.resolve();
                      })), (function (param) {
                    setEntryStatus(function (param) {
                          return EntryState.errorStatus(AuthAppSupport.describeEntryHistoryError());
                        });
                    setSelectedEntryId(function (param) {
                          
                        });
                    return Promise.resolve();
                  }));
          } else {
            exit = 1;
          }
          if (exit === 1) {
            setEntryStatus(function (param) {
                  return EntryState.initialStatus();
                });
            setEntryForm(function (param) {
                  return EntryState.initialForm;
                });
            setSelectedEntryId(function (param) {
                  
                });
            setEntryComposerMode(function (param) {
                  
                });
          }
          
        }), [
        sessionToken,
        collectionStatus,
        selectedCollectionId
      ]);
  var handleInvite = function () {
    if (sessionToken !== undefined && selectedCollection !== undefined && CollectionModel.isOwner(selectedCollection) && !inviteForm.isSubmitting) {
      setInviteForm(function (current) {
            return CollectionInvite.startSubmitting(current);
          });
      Js_promise2.$$catch(Js_promise2.then(CollectionInvite.invite(sessionToken, selectedCollection.id, inviteForm.email), (function (invitedMember) {
                  setInviteForm(function (param) {
                        return CollectionInvite.succeedForm(invitedMember);
                      });
                  return Promise.resolve();
                })), (function (reason) {
              setInviteForm(function (current) {
                    return CollectionInvite.failForm(current, AuthAppSupport.describeInviteError(reason));
                  });
              return Promise.resolve();
            }));
      return ;
    }
    
  };
  var handleCreateEntry = function () {
    if (sessionToken === undefined) {
      return ;
    }
    if (selectedCollection === undefined) {
      return ;
    }
    if (entryComposerMode !== undefined && typeof entryComposerMode === "object" && !entryForm.isSubmitting) {
      setEntryForm(function (current) {
            return EntryState.startSubmitting(current);
          });
      Js_promise2.$$catch(Js_promise2.then(EntryState.updateEntry(sessionToken, selectedCollection.id, entryComposerMode._0, entryForm), (function (entry) {
                  setEntryStatus(function (current) {
                        var entries = EntryState.isReady(current) ? EntryState.entries(current) : [];
                        return EntryState.readyStatus(EntryState.replaceEntry(entries, entry));
                      });
                  setSelectedEntryId(function (param) {
                        return entry.id;
                      });
                  setEntryForm(function (param) {
                        return EntryState.succeedForm();
                      });
                  setEntryComposerMode(function (param) {
                        
                      });
                  return Promise.resolve();
                })), (function (reason) {
              setEntryForm(function (current) {
                    return EntryState.failForm(current, AuthAppSupport.describeEntryError(reason));
                  });
              return Promise.resolve();
            }));
      return ;
    }
    if (!entryForm.isSubmitting) {
      setEntryForm(function (current) {
            return EntryState.startSubmitting(current);
          });
      Js_promise2.$$catch(Js_promise2.then(EntryState.createEntry(sessionToken, selectedCollection.id, entryForm), (function (entry) {
                  setEntryStatus(function (current) {
                        var entries = EntryState.isReady(current) ? EntryState.entries(current) : [];
                        return EntryState.readyStatus(EntryState.appendEntry(entries, entry));
                      });
                  setSelectedEntryId(function (param) {
                        return entry.id;
                      });
                  setEntryForm(function (param) {
                        return EntryState.succeedForm();
                      });
                  setEntryComposerMode(function (param) {
                        
                      });
                  return Promise.resolve();
                })), (function (reason) {
              setEntryForm(function (current) {
                    return EntryState.failForm(current, AuthAppSupport.describeEntryError(reason));
                  });
              return Promise.resolve();
            }));
      return ;
    }
    
  };
  var handleSelectEntry = function (entryId) {
    setSelectedEntryId(function (param) {
          return entryId;
        });
  };
  var openEntryComposer = function () {
    setEntryForm(function (param) {
          return EntryState.initialForm;
        });
    setEntryComposerMode(function (param) {
          return "CreateEntry";
        });
  };
  var openEntryEditor = function () {
    if (selectedEntry !== undefined) {
      setEntryForm(function (param) {
            return EntryState.formFromEntry(selectedEntry);
          });
      return setEntryComposerMode(function (param) {
                  return {
                          TAG: "EditEntry",
                          _0: selectedEntry.id
                        };
                });
    }
    
  };
  var closeEntryComposer = function () {
    setEntryForm(function (param) {
          return EntryState.initialForm;
        });
    setEntryComposerMode(function (param) {
          
        });
  };
  var tmp;
  if (match$4[0]) {
    tmp = JsxRuntime.jsx("section", {
          children: "Checking your session...",
          className: "w-full max-w-md rounded-[2rem] border border-stone-900/10 bg-white/80 p-8 text-sm text-stone-600 shadow-[0_24px_80px_rgba(81,46,23,0.12)] backdrop-blur"
        });
  } else if (currentUser !== undefined) {
    var tmp$1;
    tmp$1 = entryComposerMode !== undefined ? (
        typeof entryComposerMode !== "object" ? "Create" : "Edit"
      ) : undefined;
    tmp = JsxRuntime.jsx(AppShell.make, {
          user: currentUser,
          collectionStatus: collectionStatus,
          collectionForm: collectionForm,
          selectedCollection: selectedCollection,
          selectedCollectionId: selectedCollectionId,
          inviteForm: inviteForm,
          entryStatus: entryStatus,
          entryForm: entryForm,
          entryComposerMode: tmp$1,
          selectedEntry: selectedEntry,
          selectedEntryId: selectedEntryId,
          onCollectionFormChange: updateCollectionForm,
          onCreateCollection: handleCreateCollection,
          onInviteFormChange: updateInviteForm,
          onInvite: handleInvite,
          onEntryFormChange: updateEntryForm,
          onCreateEntry: handleCreateEntry,
          onEditEntry: openEntryEditor,
          onOpenEntryComposer: openEntryComposer,
          onCloseEntryComposer: closeEntryComposer,
          onSelectEntry: handleSelectEntry,
          onSelectCollection: handleSelectCollection,
          onLogout: handleLogout
        });
  } else {
    tmp = JsxRuntime.jsx(AuthCard.make, {
          mode: mode,
          onModeChange: handleModeChange,
          form: form,
          onFormChange: updateForm,
          onSubmit: handleSubmit,
          isSubmitting: match$5[0],
          error: Js_null_undefined.fromOption(match$6[0])
        });
  }
  return JsxRuntime.jsx("main", {
              children: JsxRuntime.jsx("div", {
                    children: tmp,
                    className: "mx-auto flex min-h-[calc(100vh-6rem)] max-w-5xl items-center justify-center"
                  }),
              className: "min-h-screen bg-[radial-gradient(circle_at_top,_rgba(234,214,196,0.9),_transparent_45%),linear-gradient(180deg,_#f7efe7_0%,_#ead9ca_100%)] px-6 py-12 text-stone-950"
            });
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
