// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Router from "./router/Router.bs.js";
import * as TextField from "./ui/TextField.bs.js";
import * as WineListScreen from "./screens/WineListScreen.bs.js";
import * as WineDetailScreen from "./screens/WineDetailScreen.bs.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as WineComposerScreen from "./screens/WineComposerScreen.bs.js";
import * as EntryComposerScreen from "./screens/EntryComposerScreen.bs.js";

function AppShell(props) {
  var onLogout = props.onLogout;
  var onSelectOccasionFilter = props.onSelectOccasionFilter;
  var onCreateEntry = props.onCreateEntry;
  var onUseNewWineForEntry = props.onUseNewWineForEntry;
  var onUseSelectedWineForEntry = props.onUseSelectedWineForEntry;
  var onEntryFormChange = props.onEntryFormChange;
  var entryForm = props.entryForm;
  var wineQuery = props.wineQuery;
  var wineOccasionFilter = props.wineOccasionFilter;
  var wineStatus = props.wineStatus;
  var route = props.route;
  var match = React.useState(function () {
        return false;
      });
  var setIsMenuOpen = match[1];
  var match$1 = React.useState(function () {
        return false;
      });
  var setIsSearchOpen = match$1[1];
  var isSearchOpen = match$1[0];
  var match$2 = React.useState(function () {
        return false;
      });
  var setIsFilterOpen = match$2[1];
  var isFilterOpen = match$2[0];
  var goWine = function (wineId) {
    Router.navigate({
          TAG: "Wine",
          _0: wineId
        });
  };
  var header;
  header = typeof route !== "object" && route === "Home" ? JsxRuntime.jsxs("header", {
          children: [
            JsxRuntime.jsx("h1", {
                  children: "Wines",
                  className: "font-serif text-2xl tracking-tight text-stone-950"
                }),
            JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsx("button", {
                          children: isSearchOpen ? "×" : "⌕",
                          "aria-label": isSearchOpen ? "Close search" : "Search wines",
                          className: "flex h-10 w-10 items-center justify-center rounded-full border border-stone-300 text-stone-700",
                          type: "button",
                          onClick: (function (param) {
                              setIsSearchOpen(function (open_) {
                                    return !open_;
                                  });
                              setIsFilterOpen(function (param) {
                                    return false;
                                  });
                            })
                        }),
                    JsxRuntime.jsx("button", {
                          children: isFilterOpen ? "×" : "⚙",
                          "aria-label": isFilterOpen ? "Close filter" : "Filter wines",
                          className: "flex h-10 w-10 items-center justify-center rounded-full border border-stone-300 text-stone-700",
                          type: "button",
                          onClick: (function (param) {
                              setIsFilterOpen(function (open_) {
                                    return !open_;
                                  });
                              setIsSearchOpen(function (param) {
                                    return false;
                                  });
                            })
                        }),
                    JsxRuntime.jsx("button", {
                          children: "≡",
                          "aria-label": "Open menu",
                          className: "flex h-10 w-10 items-center justify-center rounded-full border border-stone-300 text-stone-700",
                          type: "button",
                          onClick: (function (param) {
                              setIsMenuOpen(function (open_) {
                                    return !open_;
                                  });
                            })
                        })
                  ],
                  className: "flex items-center gap-1"
                })
          ],
          className: "mb-4 flex items-center justify-between gap-2"
        }) : null;
  var searchPanel = isSearchOpen && route === "Home" ? JsxRuntime.jsx("div", {
          children: JsxRuntime.jsx(TextField.make, {
                label: "Search wines",
                value: wineQuery,
                onChange: props.onWineQueryChange,
                autoComplete: "off"
              }),
          className: "mb-4"
        }) : null;
  var filterPanel;
  if (isFilterOpen && route === "Home") {
    var tmp;
    switch (wineOccasionFilter) {
      case "All" :
          tmp = "rounded-full bg-stone-950 px-3 py-1 text-xs text-white";
          break;
      case "WithOccasions" :
      case "WithoutOccasions" :
          tmp = "rounded-full border border-stone-300 px-3 py-1 text-xs text-stone-700";
          break;
      
    }
    var tmp$1;
    switch (wineOccasionFilter) {
      case "WithOccasions" :
          tmp$1 = "rounded-full bg-stone-950 px-3 py-1 text-xs text-white";
          break;
      case "All" :
      case "WithoutOccasions" :
          tmp$1 = "rounded-full border border-stone-300 px-3 py-1 text-xs text-stone-700";
          break;
      
    }
    var tmp$2;
    switch (wineOccasionFilter) {
      case "All" :
      case "WithOccasions" :
          tmp$2 = "rounded-full border border-stone-300 px-3 py-1 text-xs text-stone-700";
          break;
      case "WithoutOccasions" :
          tmp$2 = "rounded-full bg-stone-950 px-3 py-1 text-xs text-white";
          break;
      
    }
    filterPanel = JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("button", {
                  children: "All wines",
                  className: tmp,
                  type: "button",
                  onClick: (function (param) {
                      onSelectOccasionFilter("All");
                    })
                }),
            JsxRuntime.jsx("button", {
                  children: "With occasions",
                  className: tmp$1,
                  type: "button",
                  onClick: (function (param) {
                      onSelectOccasionFilter("WithOccasions");
                    })
                }),
            JsxRuntime.jsx("button", {
                  children: "No occasions yet",
                  className: tmp$2,
                  type: "button",
                  onClick: (function (param) {
                      onSelectOccasionFilter("WithoutOccasions");
                    })
                })
          ],
          className: "mb-4 flex flex-wrap gap-2 rounded-2xl border border-stone-200 bg-white/70 p-3"
        });
  } else {
    filterPanel = null;
  }
  var menu = match[0] ? JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsx("p", {
                          children: "Signed in",
                          className: "text-xs font-medium uppercase tracking-widest text-stone-500"
                        }),
                    JsxRuntime.jsx("p", {
                          children: props.user.email,
                          className: "mt-1 text-sm font-medium text-stone-900"
                        })
                  ],
                  className: "rounded-xl border border-stone-200 bg-stone-50 px-4 py-3"
                }),
            JsxRuntime.jsx("button", {
                  children: "Log out",
                  className: "mt-2 w-full rounded-xl px-4 py-3 text-left text-sm font-medium text-stone-700 hover:bg-stone-50",
                  type: "button",
                  onClick: (function (param) {
                      setIsMenuOpen(function (param) {
                            return false;
                          });
                      onLogout();
                    })
                })
          ],
          className: "absolute right-6 top-20 z-20 w-64 rounded-2xl border border-stone-200 bg-white p-2 shadow-xl"
        }) : null;
  var body;
  if (typeof route !== "object") {
    body = route === "Home" ? JsxRuntime.jsxs(JsxRuntime.Fragment, {
            children: [
              searchPanel,
              filterPanel,
              JsxRuntime.jsx(WineListScreen.make, {
                    wineStatus: wineStatus,
                    wineQuery: wineQuery,
                    wineOccasionFilter: wineOccasionFilter,
                    totalWineCount: props.totalWineCount,
                    selectedWineId: undefined,
                    onSelectWine: goWine
                  }),
              JsxRuntime.jsx("button", {
                    children: "+",
                    "aria-label": "Add wine",
                    className: "fixed bottom-6 right-6 flex h-14 w-14 items-center justify-center rounded-full bg-stone-950 text-2xl font-semibold text-white shadow-lg",
                    type: "button",
                    onClick: (function (param) {
                        Router.navigate("NewWine");
                      })
                  })
            ]
          }) : JsxRuntime.jsx(WineComposerScreen.make, {
            wineForm: props.wineForm,
            onWineFormChange: props.onWineFormChange,
            onSubmit: props.onCreateWine,
            onClose: (function () {
                Router.navigate("Home");
              })
          });
  } else {
    switch (route.TAG) {
      case "Wine" :
          var wineId = route._0;
          body = JsxRuntime.jsx(WineDetailScreen.make, {
                wineStatus: wineStatus,
                wineId: wineId,
                entryStatus: props.entryStatus,
                onEditEntry: props.onEditEntry,
                onAddEntry: (function () {
                    Router.navigate({
                          TAG: "NewEntry",
                          _0: wineId
                        });
                  }),
                onBack: (function () {
                    Router.navigate("Home");
                  })
              });
          break;
      case "NewEntry" :
          var wineId$1 = route._0;
          body = JsxRuntime.jsx(EntryComposerScreen.make, {
                mode: {
                  TAG: "New",
                  _0: wineId$1
                },
                wineStatus: wineStatus,
                entryForm: entryForm,
                onEntryFormChange: onEntryFormChange,
                onUseSelectedWineForEntry: onUseSelectedWineForEntry,
                onUseNewWineForEntry: onUseNewWineForEntry,
                onSubmit: onCreateEntry,
                onClose: (function () {
                    Router.navigate({
                          TAG: "Wine",
                          _0: wineId$1
                        });
                  })
              });
          break;
      case "EditEntry" :
          var wineId$2 = route._0;
          body = JsxRuntime.jsx(EntryComposerScreen.make, {
                mode: {
                  TAG: "Edit",
                  _0: wineId$2,
                  _1: route._1
                },
                wineStatus: wineStatus,
                entryForm: entryForm,
                onEntryFormChange: onEntryFormChange,
                onUseSelectedWineForEntry: onUseSelectedWineForEntry,
                onUseNewWineForEntry: onUseNewWineForEntry,
                onSubmit: onCreateEntry,
                onClose: (function () {
                    Router.navigate({
                          TAG: "Wine",
                          _0: wineId$2
                        });
                  })
              });
          break;
      
    }
  }
  return JsxRuntime.jsxs("section", {
              children: [
                header,
                menu,
                body
              ],
              className: "relative w-full max-w-3xl rounded-3xl border border-stone-900/10 bg-white/80 p-6 shadow-xl backdrop-blur md:p-10"
            });
}

var make = AppShell;

export {
  make ,
}
/* react Not a pure module */
