// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TextField from "./ui/TextField.bs.js";
import * as EntryHistory from "./entries/EntryHistory.bs.js";
import * as CollectionList from "./collections/CollectionList.bs.js";
import * as CollectionModel from "./collections/CollectionModel.bs.js";
import * as Js_null_undefined from "rescript/lib/es6/js_null_undefined.js";
import * as JsxRuntime from "react/jsx-runtime";

function AppShell(props) {
  var onLogout = props.onLogout;
  var onCreateEntry = props.onCreateEntry;
  var onEntryFormChange = props.onEntryFormChange;
  var onInvite = props.onInvite;
  var onCreateCollection = props.onCreateCollection;
  var entryForm = props.entryForm;
  var inviteForm = props.inviteForm;
  var selectedCollection = props.selectedCollection;
  var collectionForm = props.collectionForm;
  var message = collectionForm.error;
  var tmp;
  if (selectedCollection !== undefined) {
    var tmp$1;
    if (CollectionModel.isOwner(selectedCollection)) {
      var message$1 = inviteForm.error;
      var message$2 = inviteForm.success;
      tmp$1 = JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("div", {
                            children: JsxRuntime.jsx(TextField.make, {
                                  label: "Invite by email",
                                  value: inviteForm.email,
                                  onChange: props.onInviteFormChange,
                                  autoComplete: "email",
                                  type_: "email"
                                }),
                            className: "flex-1"
                          }),
                      JsxRuntime.jsx("button", {
                            children: inviteForm.isSubmitting ? "Inviting..." : "Invite",
                            className: "rounded-2xl bg-stone-950 px-5 py-3 text-sm font-semibold text-white transition hover:bg-stone-800 disabled:cursor-wait disabled:bg-stone-400",
                            disabled: inviteForm.isSubmitting,
                            type: "button",
                            onClick: (function (param) {
                                onInvite();
                              })
                          })
                    ],
                    className: "flex flex-col gap-4 md:flex-row md:items-end"
                  }),
              message$1 !== undefined ? JsxRuntime.jsx("div", {
                      children: message$1,
                      className: "mt-4 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700"
                    }) : null,
              message$2 !== undefined ? JsxRuntime.jsx("div", {
                      children: message$2,
                      className: "mt-4 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700"
                    }) : null
            ],
            className: "mt-6 border-t border-stone-200 pt-6"
          });
    } else {
      tmp$1 = null;
    }
    var message$3 = entryForm.error;
    var message$4 = entryForm.success;
    tmp = JsxRuntime.jsxs("section", {
          children: [
            JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsx("p", {
                                  children: "Selected collection",
                                  className: "text-xs font-medium uppercase tracking-[0.25em] text-stone-500"
                                }),
                            JsxRuntime.jsx("h2", {
                                  children: selectedCollection.name,
                                  className: "mt-2 text-2xl font-semibold text-stone-950"
                                }),
                            JsxRuntime.jsx("p", {
                                  children: CollectionModel.isOwner(selectedCollection) ? "You can invite another account into this collection." : "You currently have member access to this collection.",
                                  className: "mt-2 text-sm text-stone-600"
                                })
                          ]
                        }),
                    JsxRuntime.jsx("span", {
                          children: selectedCollection.role,
                          className: "rounded-full border border-stone-300 px-3 py-1 text-xs font-medium uppercase tracking-[0.2em] text-stone-600"
                        })
                  ],
                  className: "flex flex-col gap-3 md:flex-row md:items-start md:justify-between"
                }),
            tmp$1,
            JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsx("h3", {
                          children: "New entry",
                          className: "text-lg font-semibold text-stone-950"
                        }),
                    JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsx(TextField.make, {
                                  label: "Wine name",
                                  value: entryForm.wineName,
                                  onChange: (function (value) {
                                      onEntryFormChange("wineName", value);
                                    }),
                                  autoComplete: "off"
                                }),
                            JsxRuntime.jsx(TextField.make, {
                                  label: "Producer",
                                  value: entryForm.producer,
                                  onChange: (function (value) {
                                      onEntryFormChange("producer", value);
                                    }),
                                  autoComplete: "organization"
                                }),
                            JsxRuntime.jsx(TextField.make, {
                                  label: "Vintage",
                                  value: entryForm.vintage,
                                  onChange: (function (value) {
                                      onEntryFormChange("vintage", value);
                                    }),
                                  autoComplete: "off",
                                  type_: "number"
                                }),
                            JsxRuntime.jsx(TextField.make, {
                                  label: "Consumed at",
                                  value: entryForm.consumedAt,
                                  onChange: (function (value) {
                                      onEntryFormChange("consumedAt", value);
                                    }),
                                  autoComplete: "off",
                                  type_: "datetime-local"
                                }),
                            JsxRuntime.jsx(TextField.make, {
                                  label: "Venue",
                                  value: entryForm.venueName,
                                  onChange: (function (value) {
                                      onEntryFormChange("venueName", value);
                                    }),
                                  autoComplete: "off"
                                }),
                            JsxRuntime.jsx(TextField.make, {
                                  label: "Location",
                                  value: entryForm.locationText,
                                  onChange: (function (value) {
                                      onEntryFormChange("locationText", value);
                                    }),
                                  autoComplete: "street-address"
                                })
                          ],
                          className: "mt-4 grid gap-4 md:grid-cols-2"
                        }),
                    JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsxs("label", {
                                  children: [
                                    JsxRuntime.jsx("span", {
                                          children: "Pairing notes",
                                          className: "mb-2 block text-sm font-medium text-stone-700"
                                        }),
                                    JsxRuntime.jsx("textarea", {
                                          className: "w-full rounded-2xl border border-stone-300 bg-white px-4 py-3 text-base text-stone-950 outline-none transition focus:border-stone-500",
                                          rows: 3,
                                          value: entryForm.pairingNotes,
                                          onChange: (function ($$event) {
                                              onEntryFormChange("pairingNotes", $$event.target.value);
                                            })
                                        })
                                  ],
                                  className: "block"
                                }),
                            JsxRuntime.jsxs("label", {
                                  children: [
                                    JsxRuntime.jsx("span", {
                                          children: "Tasting notes",
                                          className: "mb-2 block text-sm font-medium text-stone-700"
                                        }),
                                    JsxRuntime.jsx("textarea", {
                                          className: "w-full rounded-2xl border border-stone-300 bg-white px-4 py-3 text-base text-stone-950 outline-none transition focus:border-stone-500",
                                          rows: 4,
                                          value: entryForm.tastingNotes,
                                          onChange: (function ($$event) {
                                              onEntryFormChange("tastingNotes", $$event.target.value);
                                            })
                                        })
                                  ],
                                  className: "block"
                                })
                          ],
                          className: "mt-4 grid gap-4"
                        }),
                    JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsx("div", {
                                  children: JsxRuntime.jsx(TextField.make, {
                                        label: "Rating",
                                        value: entryForm.rating,
                                        onChange: (function (value) {
                                            onEntryFormChange("rating", value);
                                          }),
                                        autoComplete: "off",
                                        type_: "number"
                                      }),
                                  className: "md:w-40"
                                }),
                            JsxRuntime.jsx("button", {
                                  children: entryForm.isSubmitting ? "Saving..." : "Save entry",
                                  className: "rounded-2xl bg-stone-950 px-5 py-3 text-sm font-semibold text-white transition hover:bg-stone-800 disabled:cursor-wait disabled:bg-stone-400",
                                  disabled: entryForm.isSubmitting,
                                  type: "button",
                                  onClick: (function (param) {
                                      onCreateEntry();
                                    })
                                })
                          ],
                          className: "mt-4 flex flex-col gap-4 md:flex-row md:items-end"
                        }),
                    message$3 !== undefined ? JsxRuntime.jsx("div", {
                            children: message$3,
                            className: "mt-4 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700"
                          }) : null,
                    message$4 !== undefined ? JsxRuntime.jsx("div", {
                            children: message$4,
                            className: "mt-4 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700"
                          }) : null
                  ],
                  className: "mt-6 border-t border-stone-200 pt-6"
                })
          ],
          className: "mb-6 rounded-[1.75rem] border border-stone-900/10 bg-stone-50/80 p-6"
        });
  } else {
    tmp = null;
  }
  return JsxRuntime.jsxs("section", {
              children: [
                JsxRuntime.jsx("p", {
                      children: "Wine",
                      className: "mb-3 font-mono text-xs uppercase tracking-[0.35em] text-stone-600"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("h1", {
                                      children: "Collections are ready for your first entries.",
                                      className: "max-w-xl font-serif text-5xl leading-none tracking-[-0.04em] text-stone-950 md:text-6xl"
                                    }),
                                JsxRuntime.jsxs("p", {
                                      children: [
                                        "Signed in as ",
                                        JsxRuntime.jsx("span", {
                                              children: props.user.email,
                                              className: "font-semibold text-stone-900"
                                            }),
                                        ". Capture bottles and notes inside each collection."
                                      ],
                                      className: "mt-6 max-w-xl text-base leading-7 text-stone-700 md:text-lg"
                                    })
                              ]
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Log out",
                              className: "rounded-2xl border border-stone-300 px-4 py-3 text-sm font-medium text-stone-700 transition hover:border-stone-500 hover:text-stone-950",
                              type: "button",
                              onClick: (function (param) {
                                  onLogout();
                                })
                            })
                      ],
                      className: "flex flex-col gap-6 md:flex-row md:items-start md:justify-between"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("section", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("div", {
                                              children: JsxRuntime.jsx(TextField.make, {
                                                    label: "New collection",
                                                    value: collectionForm.name,
                                                    onChange: props.onCollectionFormChange,
                                                    autoComplete: "off"
                                                  }),
                                              className: "flex-1"
                                            }),
                                        JsxRuntime.jsx("button", {
                                              children: collectionForm.isSubmitting ? "Creating..." : "Create collection",
                                              className: "rounded-2xl bg-stone-950 px-5 py-3 text-sm font-semibold text-white transition hover:bg-stone-800 disabled:cursor-wait disabled:bg-stone-400",
                                              disabled: collectionForm.isSubmitting,
                                              type: "button",
                                              onClick: (function (param) {
                                                  onCreateCollection();
                                                })
                                            })
                                      ],
                                      className: "flex flex-col gap-4 md:flex-row md:items-end"
                                    }),
                                message !== undefined ? JsxRuntime.jsx("div", {
                                        children: message,
                                        className: "mt-4 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700"
                                      }) : null
                              ],
                              className: "mb-6 rounded-[1.75rem] border border-stone-900/10 bg-stone-50/80 p-6"
                            }),
                        tmp,
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsx(EntryHistory.make, {
                                    status: props.entryStatus
                                  }),
                              className: "mb-6"
                            }),
                        JsxRuntime.jsx(CollectionList.make, {
                              status: props.collectionStatus,
                              selectedCollectionId: Js_null_undefined.fromOption(props.selectedCollectionId),
                              onSelectCollection: props.onSelectCollection
                            })
                      ],
                      className: "mt-8"
                    })
              ],
              className: "w-full max-w-3xl rounded-[2rem] border border-stone-900/10 bg-white/80 p-8 shadow-[0_24px_80px_rgba(81,46,23,0.12)] backdrop-blur md:p-12"
            });
}

var make = AppShell;

export {
  make ,
}
/* TextField Not a pure module */
