// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as WineList from "./wines/WineList.bs.js";
import * as TextField from "./ui/TextField.bs.js";
import * as WineDetail from "./wines/WineDetail.bs.js";
import * as WineComposer from "./wines/WineComposer.bs.js";
import * as EntryComposer from "./entries/EntryComposer.bs.js";
import * as CollectionList from "./collections/CollectionList.bs.js";
import * as CollectionModel from "./collections/CollectionModel.bs.js";
import * as Js_null_undefined from "rescript/lib/es6/js_null_undefined.js";
import * as JsxRuntime from "react/jsx-runtime";

function AppShell(props) {
  var onLogout = props.onLogout;
  var onOpenEntryComposer = props.onOpenEntryComposer;
  var onOpenWineComposer = props.onOpenWineComposer;
  var onInvite = props.onInvite;
  var onCreateCollection = props.onCreateCollection;
  var wineComposerMode = props.wineComposerMode;
  var entryComposerMode = props.entryComposerMode;
  var inviteForm = props.inviteForm;
  var selectedCollection = props.selectedCollection;
  var collectionForm = props.collectionForm;
  var match = React.useState(function () {
        return false;
      });
  var setIsShareOpen = match[1];
  var isShareOpen = match[0];
  var message = collectionForm.error;
  var tmp;
  if (selectedCollection !== undefined) {
    var tmp$1;
    if (CollectionModel.isOwner(selectedCollection) && isShareOpen) {
      var message$1 = inviteForm.error;
      var message$2 = inviteForm.success;
      tmp$1 = JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("div", {
                            children: JsxRuntime.jsx(TextField.make, {
                                  label: "Invite by email",
                                  value: inviteForm.email,
                                  onChange: props.onInviteFormChange,
                                  autoComplete: "email",
                                  type_: "email"
                                }),
                            className: "flex-1"
                          }),
                      JsxRuntime.jsx("button", {
                            children: inviteForm.isSubmitting ? "Inviting..." : "Invite",
                            className: "rounded-2xl bg-stone-950 px-5 py-3 text-sm font-semibold text-white transition hover:bg-stone-800 disabled:cursor-wait disabled:bg-stone-400",
                            disabled: inviteForm.isSubmitting,
                            type: "button",
                            onClick: (function (param) {
                                onInvite();
                              })
                          })
                    ],
                    className: "flex flex-col gap-4 md:flex-row md:items-end"
                  }),
              message$1 !== undefined ? JsxRuntime.jsx("div", {
                      children: message$1,
                      className: "mt-4 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700"
                    }) : null,
              message$2 !== undefined ? JsxRuntime.jsx("div", {
                      children: message$2,
                      className: "mt-4 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700"
                    }) : null
            ],
            className: "mt-5 border-t border-stone-200 pt-5"
          });
    } else {
      tmp$1 = null;
    }
    tmp = JsxRuntime.jsxs("section", {
          children: [
            JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsx("p", {
                                  children: "Collection",
                                  className: "text-xs font-medium uppercase tracking-[0.25em] text-stone-500"
                                }),
                            JsxRuntime.jsxs("div", {
                                  children: [
                                    JsxRuntime.jsx("h2", {
                                          children: selectedCollection.name,
                                          className: "text-xl font-semibold text-stone-950"
                                        }),
                                    JsxRuntime.jsx("span", {
                                          children: selectedCollection.role,
                                          className: "rounded-full border border-stone-300 px-3 py-1 text-xs font-medium uppercase tracking-[0.2em] text-stone-600"
                                        })
                                  ],
                                  className: "mt-2 flex flex-wrap items-center gap-3"
                                })
                          ]
                        }),
                    JsxRuntime.jsxs("div", {
                          children: [
                            CollectionModel.isOwner(selectedCollection) ? JsxRuntime.jsx("button", {
                                    children: isShareOpen ? "Close share" : "Share",
                                    className: "rounded-2xl border border-stone-300 px-4 py-3 text-sm font-medium text-stone-700 transition hover:border-stone-500 hover:text-stone-950",
                                    type: "button",
                                    onClick: (function (param) {
                                        setIsShareOpen(function (current) {
                                              return !current;
                                            });
                                      })
                                  }) : null,
                            JsxRuntime.jsx("button", {
                                  children: "Add wine",
                                  className: "rounded-2xl border border-stone-300 px-4 py-3 text-sm font-medium text-stone-700 transition hover:border-stone-500 hover:text-stone-950",
                                  type: "button",
                                  onClick: (function (param) {
                                      onOpenWineComposer();
                                    })
                                }),
                            JsxRuntime.jsx("button", {
                                  children: "Add entry",
                                  className: "rounded-2xl bg-stone-950 px-5 py-3 text-sm font-semibold text-white transition hover:bg-stone-800",
                                  type: "button",
                                  onClick: (function (param) {
                                      onOpenEntryComposer();
                                    })
                                })
                          ],
                          className: "flex flex-wrap gap-3"
                        })
                  ],
                  className: "flex flex-col gap-4 md:flex-row md:items-center md:justify-between"
                }),
            tmp$1
          ],
          className: "rounded-[1.75rem] border border-stone-900/10 bg-stone-50/80 p-5"
        });
  } else {
    tmp = null;
  }
  return JsxRuntime.jsxs("section", {
              children: [
                JsxRuntime.jsx("p", {
                      children: "Wine",
                      className: "mb-3 font-mono text-xs uppercase tracking-[0.35em] text-stone-600"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("h1", {
                                      children: "Remember the bottles worth coming back to.",
                                      className: "max-w-xl font-serif text-5xl leading-none tracking-[-0.04em] text-stone-950 md:text-6xl"
                                    }),
                                JsxRuntime.jsxs("p", {
                                      children: [
                                        "Signed in as ",
                                        JsxRuntime.jsx("span", {
                                              children: props.user.email,
                                              className: "font-semibold text-stone-900"
                                            }),
                                        ". Browse the wines you know first, then open the occasions behind them when you need more context."
                                      ],
                                      className: "mt-6 max-w-xl text-base leading-7 text-stone-700 md:text-lg"
                                    })
                              ]
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Log out",
                              className: "rounded-2xl border border-stone-300 px-4 py-3 text-sm font-medium text-stone-700 transition hover:border-stone-500 hover:text-stone-950",
                              type: "button",
                              onClick: (function (param) {
                                  onLogout();
                                })
                            })
                      ],
                      className: "flex flex-col gap-6 md:flex-row md:items-start md:justify-between"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("section", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("div", {
                                              children: JsxRuntime.jsx(TextField.make, {
                                                    label: "New collection",
                                                    value: collectionForm.name,
                                                    onChange: props.onCollectionFormChange,
                                                    autoComplete: "off"
                                                  }),
                                              className: "flex-1"
                                            }),
                                        JsxRuntime.jsx("button", {
                                              children: collectionForm.isSubmitting ? "Creating..." : "Create collection",
                                              className: "rounded-2xl bg-stone-950 px-5 py-3 text-sm font-semibold text-white transition hover:bg-stone-800 disabled:cursor-wait disabled:bg-stone-400",
                                              disabled: collectionForm.isSubmitting,
                                              type: "button",
                                              onClick: (function (param) {
                                                  onCreateCollection();
                                                })
                                            })
                                      ],
                                      className: "flex flex-col gap-4 md:flex-row md:items-end"
                                    }),
                                message !== undefined ? JsxRuntime.jsx("div", {
                                        children: message,
                                        className: "mt-4 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700"
                                      }) : null
                              ],
                              className: "mb-6 rounded-[1.75rem] border border-stone-900/10 bg-stone-50/80 p-6"
                            }),
                        JsxRuntime.jsx("div", {
                              children: tmp,
                              className: "mb-6"
                            }),
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsx(WineList.make, {
                                    status: props.wineStatus,
                                    wineQuery: props.wineQuery,
                                    totalWineCount: props.totalWineCount,
                                    selectedWineId: props.selectedWineId,
                                    onSelectWine: props.onSelectWine,
                                    onWineQueryChange: props.onWineQueryChange
                                  }),
                              className: "mb-6"
                            }),
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsx(WineDetail.make, {
                                    selectedWine: props.selectedWine,
                                    entryStatus: props.entryStatus,
                                    selectedEntry: props.selectedEntry,
                                    selectedEntryId: props.selectedEntryId,
                                    onSelectEntry: props.onSelectEntry,
                                    onEditEntry: props.onEditEntry
                                  }),
                              className: "mb-6"
                            }),
                        JsxRuntime.jsx(CollectionList.make, {
                              status: props.collectionStatus,
                              selectedCollectionId: Js_null_undefined.fromOption(props.selectedCollectionId),
                              onSelectCollection: props.onSelectCollection
                            }),
                        entryComposerMode !== undefined ? JsxRuntime.jsx(EntryComposer.make, {
                                mode: entryComposerMode,
                                entryForm: props.entryForm,
                                onEntryFormChange: props.onEntryFormChange,
                                onSubmit: props.onCreateEntry,
                                onClose: props.onCloseEntryComposer
                              }) : null,
                        wineComposerMode !== undefined ? JsxRuntime.jsx(WineComposer.make, {
                                mode: wineComposerMode,
                                wineForm: props.wineForm,
                                onWineFormChange: props.onWineFormChange,
                                onSubmit: props.onCreateWine,
                                onClose: props.onCloseWineComposer
                              }) : null
                      ],
                      className: "mt-8"
                    })
              ],
              className: "w-full max-w-3xl rounded-[2rem] border border-stone-900/10 bg-white/80 p-8 shadow-[0_24px_80px_rgba(81,46,23,0.12)] backdrop-blur md:p-12"
            });
}

var make = AppShell;

export {
  make ,
}
/* react Not a pure module */
