// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as ApiClientJs from "./apiClient.js";

function requestWithPost(prim0, prim1) {
  return ApiClientJs.request(prim0, prim1);
}

function requestWithGet(prim0, prim1) {
  return ApiClientJs.request(prim0, prim1);
}

function authHeaders(prim0, prim1) {
  return ApiClientJs.authHeaders(prim0, prim1);
}

var jsonHeaders = ApiClientJs.jsonHeaders;

function stringify(value) {
  return Belt_Option.getExn(JSON.stringify(value));
}

function register(email, fullName, password) {
  return ApiClientJs.request("/api/auth/register", {
              method: "POST",
              headers: jsonHeaders,
              body: Belt_Option.getExn(JSON.stringify({
                        email: email,
                        full_name: fullName,
                        password: password
                      }))
            });
}

function login(email, password) {
  return ApiClientJs.request("/api/auth/login", {
              method: "POST",
              headers: jsonHeaders,
              body: Belt_Option.getExn(JSON.stringify({
                        email: email,
                        password: password
                      }))
            });
}

function me(token) {
  return ApiClientJs.request("/api/me", {
              headers: ApiClientJs.authHeaders(token, {})
            });
}

export {
  requestWithPost ,
  requestWithGet ,
  authHeaders ,
  jsonHeaders ,
  stringify ,
  register ,
  login ,
  me ,
}
/* jsonHeaders Not a pure module */
