// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_json from "rescript/lib/es6/js_json.js";

var parseJson = Js_json.deserializeUnsafe;

function describeError(error) {
  var match = error.message;
  switch (match) {
    case "email_taken" :
        return "That email address is already registered.";
    case "invalid_credentials" :
        return "The email or password was not accepted.";
    case "invalid_email" :
        return "Enter a valid email address.";
    case "password_too_short" :
        return "Use a password with at least 8 characters.";
    default:
      return "Something went wrong. Try again.";
  }
}

function describeCollectionError() {
  return "Could not load your collections. Try refreshing.";
}

function describeCreateCollectionError(error) {
  var match = error.message;
  if (match === "invalid_collection_name") {
    return "Enter a name for the collection.";
  } else {
    return "Could not create the collection. Try again.";
  }
}

export {
  parseJson ,
  describeError ,
  describeCollectionError ,
  describeCreateCollectionError ,
}
/* No side effect */
