// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function AuthField(props) {
  var __type_ = props.type_;
  var onChange = props.onChange;
  var type_ = __type_ !== undefined ? __type_ : "text";
  return JsxRuntime.jsxs("label", {
              children: [
                JsxRuntime.jsx("span", {
                      children: props.label,
                      className: "mb-2 block text-sm font-medium text-stone-700"
                    }),
                JsxRuntime.jsx("input", {
                      className: "w-full rounded-2xl border border-stone-300 bg-white px-4 py-3 text-base text-stone-950 outline-none transition focus:border-stone-500",
                      autoComplete: props.autoComplete,
                      type: type_,
                      value: props.value,
                      onChange: (function ($$event) {
                          onChange($$event.target.value);
                        })
                    })
              ],
              className: "block"
            });
}

var make = AuthField;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
