// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AuthApi from "./api/AuthApi.bs.js";
import * as ApiClient from "./api/ApiClient.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Js_promise2 from "rescript/lib/es6/js_promise2.js";
import * as ResponseDecoder from "./api/ResponseDecoder.bs.js";

var registerMode = "register";

function isRegisterMode(mode) {
  return mode === registerMode;
}

function updateForm(form, field, value) {
  switch (field) {
    case "email" :
        return {
                email: value,
                fullName: form.fullName,
                password: form.password
              };
    case "fullName" :
        return {
                email: form.email,
                fullName: value,
                password: form.password
              };
    case "password" :
        return {
                email: form.email,
                fullName: form.fullName,
                password: value
              };
    default:
      return form;
  }
}

function submit(mode, form) {
  var request = mode === registerMode ? AuthApi.register(form.email, form.fullName, form.password) : AuthApi.login(form.email, form.password);
  return Js_promise2.then(request, (function (response) {
                var payload = Belt_Option.flatMap(ResponseDecoder.parse(response), ResponseDecoder.authPayload);
                if (payload !== undefined) {
                  return Promise.resolve(payload);
                } else {
                  return Promise.reject(ApiClient.invalidResponse());
                }
              }));
}

var loginMode = "login";

var initialForm = {
  email: "",
  fullName: "",
  password: ""
};

export {
  loginMode ,
  registerMode ,
  initialForm ,
  isRegisterMode ,
  updateForm ,
  submit ,
}
/* AuthApi Not a pure module */
