// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ApiClient from "./api/ApiClient.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_array from "rescript/lib/es6/caml_array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Js_promise2 from "rescript/lib/es6/js_promise2.js";
import * as CollectionApi from "./api/CollectionApi.bs.js";
import * as ResponseDecoder from "./api/ResponseDecoder.bs.js";

function initialCollectionStatus() {
  return "Loading";
}

function emptyCollectionStatus() {
  return {
          TAG: "Ready",
          _0: []
        };
}

function loadingCollectionStatus() {
  return "Loading";
}

function readyCollectionStatus(collections) {
  return {
          TAG: "Ready",
          _0: collections
        };
}

function errorCollectionStatus(message) {
  return {
          TAG: "Error",
          _0: message
        };
}

var initialCollectionForm = {
  name: "",
  isSubmitting: false,
  error: undefined
};

function updateCollectionForm(form, value) {
  return {
          name: value,
          isSubmitting: form.isSubmitting,
          error: undefined
        };
}

function startSubmittingCollectionForm(form) {
  return {
          name: form.name,
          isSubmitting: true,
          error: undefined
        };
}

function resetCollectionForm() {
  return initialCollectionForm;
}

function failCollectionForm(form, message) {
  return {
          name: form.name,
          isSubmitting: false,
          error: message
        };
}

function finishCollectionForm() {
  return initialCollectionForm;
}

function listCollections(token) {
  return Js_promise2.then(CollectionApi.listCollections(token), (function (response) {
                var collections = Belt_Option.flatMap(ResponseDecoder.parse(response), ResponseDecoder.collections);
                if (collections !== undefined) {
                  return Promise.resolve(collections);
                } else {
                  return Promise.reject(ApiClient.invalidResponse());
                }
              }));
}

function createCollection(token, name) {
  return Js_promise2.then(CollectionApi.createCollection(token, name), (function (response) {
                var collection = Belt_Option.flatMap(ResponseDecoder.parse(response), ResponseDecoder.collection);
                if (collection !== undefined) {
                  return Promise.resolve(collection);
                } else {
                  return Promise.reject(ApiClient.invalidResponse());
                }
              }));
}

function appendCollection(collections, collection) {
  return Belt_Array.concat(collections, [collection]);
}

function isReady(status) {
  if (typeof status !== "object" || status.TAG !== "Ready") {
    return false;
  } else {
    return true;
  }
}

function collections(status) {
  if (typeof status !== "object") {
    return [];
  } else if (status.TAG === "Ready") {
    return status._0;
  } else {
    return [];
  }
}

function errorMessage(status) {
  if (typeof status !== "object" || status.TAG === "Ready") {
    return ;
  } else {
    return status._0;
  }
}

function resolveSelectedCollectionId(collections, selectedCollectionId, persistedCollectionId) {
  if (collections.length === 0) {
    return ;
  }
  var currentSelectionStillExists = Belt_Array.some(collections, (function (collection) {
          if (selectedCollectionId !== undefined) {
            return collection.id === selectedCollectionId;
          } else {
            return false;
          }
        }));
  if (currentSelectionStillExists) {
    return selectedCollectionId;
  }
  var persistedSelectionStillExists = Belt_Array.some(collections, (function (collection) {
          if (persistedCollectionId !== undefined) {
            return collection.id === persistedCollectionId;
          } else {
            return false;
          }
        }));
  if (persistedSelectionStillExists) {
    return persistedCollectionId;
  } else {
    return Caml_array.get(collections, 0).id;
  }
}

export {
  initialCollectionStatus ,
  emptyCollectionStatus ,
  loadingCollectionStatus ,
  readyCollectionStatus ,
  errorCollectionStatus ,
  initialCollectionForm ,
  updateCollectionForm ,
  startSubmittingCollectionForm ,
  resetCollectionForm ,
  failCollectionForm ,
  finishCollectionForm ,
  listCollections ,
  createCollection ,
  appendCollection ,
  isReady ,
  collections ,
  errorMessage ,
  resolveSelectedCollectionId ,
}
/* ApiClient Not a pure module */
