// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_array from "rescript/lib/es6/caml_array.js";
import * as Js_promise2 from "rescript/lib/es6/js_promise2.js";
import * as CollectionApi from "./CollectionApi.bs.js";
import * as AuthAppSupport from "./AuthAppSupport.bs.js";

function initialCollectionStatus() {
  return {
          kind: "loading",
          collections: []
        };
}

function emptyCollectionStatus() {
  return {
          kind: "ready",
          collections: []
        };
}

function loadingCollectionStatus() {
  return {
          kind: "loading",
          collections: []
        };
}

function readyCollectionStatus(collections) {
  return {
          kind: "ready",
          collections: collections
        };
}

function errorCollectionStatus(message) {
  return {
          kind: "error",
          message: message
        };
}

var initialCollectionForm = {
  name: "",
  isSubmitting: false,
  error: undefined
};

function updateCollectionForm(form, value) {
  return {
          name: value,
          isSubmitting: form.isSubmitting,
          error: undefined
        };
}

function startSubmittingCollectionForm(form) {
  return {
          name: form.name,
          isSubmitting: true,
          error: undefined
        };
}

function resetCollectionForm() {
  return initialCollectionForm;
}

function failCollectionForm(form, message) {
  return {
          name: form.name,
          isSubmitting: false,
          error: message
        };
}

function finishCollectionForm() {
  return initialCollectionForm;
}

function listCollections(token) {
  return Js_promise2.then(CollectionApi.listCollections(token), (function (response) {
                return Promise.resolve(AuthAppSupport.parseJson(response));
              }));
}

function createCollection(token, name) {
  return Js_promise2.then(CollectionApi.createCollection(token, name), (function (response) {
                return Promise.resolve(AuthAppSupport.parseJson(response));
              }));
}

function appendCollection(collections, collection) {
  return Belt_Array.concat(collections, [collection]);
}

function resolveSelectedCollectionId(collections, selectedCollectionId, persistedCollectionId) {
  if (collections.length === 0) {
    return ;
  }
  var currentSelectionStillExists = Belt_Array.some(collections, (function (collection) {
          if (selectedCollectionId !== undefined) {
            return collection.id === selectedCollectionId;
          } else {
            return false;
          }
        }));
  if (currentSelectionStillExists) {
    return selectedCollectionId;
  }
  var persistedSelectionStillExists = Belt_Array.some(collections, (function (collection) {
          if (persistedCollectionId !== undefined) {
            return collection.id === persistedCollectionId;
          } else {
            return false;
          }
        }));
  if (persistedSelectionStillExists) {
    return persistedCollectionId;
  } else {
    return Caml_array.get(collections, 0).id;
  }
}

export {
  initialCollectionStatus ,
  emptyCollectionStatus ,
  loadingCollectionStatus ,
  readyCollectionStatus ,
  errorCollectionStatus ,
  initialCollectionForm ,
  updateCollectionForm ,
  startSubmittingCollectionForm ,
  resetCollectionForm ,
  failCollectionForm ,
  finishCollectionForm ,
  listCollections ,
  createCollection ,
  appendCollection ,
  resolveSelectedCollectionId ,
}
/* CollectionApi Not a pure module */
