// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

var selectedClasses = "rounded-2xl border px-4 py-3 transition border-stone-950 bg-stone-950 text-white";

var unselectedClasses = "rounded-2xl border px-4 py-3 transition border-stone-200 bg-white text-stone-950";

var selectedRoleClasses = "mt-1 text-xs uppercase tracking-[0.2em] text-stone-300";

var unselectedRoleClasses = "mt-1 text-xs uppercase tracking-[0.2em] text-stone-500";

function CollectionList(props) {
  var onSelectCollection = props.onSelectCollection;
  var selectedCollectionId = props.selectedCollectionId;
  var status = props.status;
  if (typeof status !== "object") {
    return JsxRuntime.jsx("section", {
                children: JsxRuntime.jsx("p", {
                      children: "Loading your collections...",
                      className: "text-sm text-stone-600"
                    }),
                className: "rounded-[1.75rem] border border-stone-900/10 bg-stone-50/80 p-6"
              });
  }
  if (status.TAG !== "Ready") {
    return JsxRuntime.jsx("section", {
                children: JsxRuntime.jsx("p", {
                      children: status._0,
                      className: "text-sm text-rose-700"
                    }),
                className: "rounded-[1.75rem] border border-rose-200 bg-rose-50 p-6"
              });
  }
  var collections = status._0;
  if (collections.length === 0) {
    return JsxRuntime.jsxs("section", {
                children: [
                  JsxRuntime.jsx("h2", {
                        children: "No collections yet",
                        className: "text-lg font-semibold text-stone-950"
                      }),
                  JsxRuntime.jsx("p", {
                        children: "Your collections will appear here once you create your first shared wine journal.",
                        className: "mt-2 text-sm leading-6 text-stone-600"
                      })
                ],
                className: "rounded-[1.75rem] border border-dashed border-stone-300 bg-stone-50/80 p-6"
              });
  } else {
    return JsxRuntime.jsxs("section", {
                children: [
                  JsxRuntime.jsx("h2", {
                        children: "Your collections",
                        className: "text-lg font-semibold text-stone-950"
                      }),
                  JsxRuntime.jsx("ul", {
                        children: Belt_Array.map(collections, (function (collection) {
                                var isSelected = (selectedCollectionId == null) ? false : collection.id === selectedCollectionId;
                                return JsxRuntime.jsx("li", {
                                            children: JsxRuntime.jsxs("button", {
                                                  children: [
                                                    JsxRuntime.jsxs("div", {
                                                          children: [
                                                            JsxRuntime.jsx("p", {
                                                                  children: collection.name,
                                                                  className: "font-medium"
                                                                }),
                                                            JsxRuntime.jsx("p", {
                                                                  children: collection.role,
                                                                  className: isSelected ? selectedRoleClasses : unselectedRoleClasses
                                                                })
                                                          ]
                                                        }),
                                                    isSelected ? JsxRuntime.jsx("span", {
                                                            children: "Selected",
                                                            className: "rounded-full border border-white/20 px-3 py-1 text-xs font-medium uppercase tracking-[0.2em] text-stone-100"
                                                          }) : null
                                                  ],
                                                  className: "flex w-full items-center justify-between text-left",
                                                  type: "button",
                                                  onClick: (function (param) {
                                                      onSelectCollection(collection.id);
                                                    })
                                                }),
                                            className: isSelected ? selectedClasses : unselectedClasses
                                          }, String(collection.id));
                              })),
                        className: "mt-4 space-y-3"
                      })
                ],
                className: "rounded-[1.75rem] border border-stone-900/10 bg-stone-50/80 p-6"
              });
  }
}

var make = CollectionList;

export {
  selectedClasses ,
  unselectedClasses ,
  selectedRoleClasses ,
  unselectedRoleClasses ,
  make ,
}
/* react/jsx-runtime Not a pure module */
