// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as ApiClientBsJs from "./ApiClient.bs.js";

function requestWithPost(prim0, prim1) {
  return ApiClientBsJs.request(prim0, prim1);
}

function requestWithGet(prim0, prim1) {
  return ApiClientBsJs.request(prim0, prim1);
}

function authHeaders(prim0, prim1) {
  return ApiClientBsJs.authHeaders(prim0, prim1);
}

var jsonHeaders = ApiClientBsJs.jsonHeaders;

function stringify(value) {
  return Belt_Option.getExn(JSON.stringify(value));
}

function listCollections(token) {
  return ApiClientBsJs.request("/api/collections", {
              headers: ApiClientBsJs.authHeaders(token, {})
            });
}

function createCollection(token, name) {
  return ApiClientBsJs.request("/api/collections", {
              method: "POST",
              headers: ApiClientBsJs.authHeaders(token, jsonHeaders),
              body: Belt_Option.getExn(JSON.stringify({
                        name: name
                      }))
            });
}

export {
  requestWithPost ,
  requestWithGet ,
  authHeaders ,
  jsonHeaders ,
  stringify ,
  listCollections ,
  createCollection ,
}
/* jsonHeaders Not a pure module */
