// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

var root = document.querySelector("#root");

if (root == null) {
  Js_exn.raiseError("Missing #root element");
} else {
  Client.createRoot(root).render(JsxRuntime.jsx(App.make, {}));
}

export {
  
}
/* root Not a pure module */
