// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function parse(text) {
  try {
    return JSON.parse(text);
  }
  catch (exn){
    return ;
  }
}

var asObject = Js_json.decodeObject;

var string = Js_json.decodeString;

function $$int(json) {
  var value = Js_json.decodeNumber(json);
  if (value !== undefined) {
    return value | 0;
  }
  
}

var field = Js_dict.get;

function stringField(object_, key) {
  var value = Js_dict.get(object_, key);
  if (value !== undefined) {
    return Js_json.decodeString(value);
  }
  
}

function intField(object_, key) {
  var value = Js_dict.get(object_, key);
  if (value !== undefined) {
    return $$int(value);
  }
  
}

function user(json) {
  var object_ = Js_json.decodeObject(json);
  if (object_ === undefined) {
    return ;
  }
  var email = stringField(object_, "email");
  if (email !== undefined) {
    return {
            email: email
          };
  }
  
}

function authPayload(json) {
  var object_ = Js_json.decodeObject(json);
  if (object_ === undefined) {
    return ;
  }
  var match = stringField(object_, "token");
  var match$1 = Belt_Option.flatMap(Js_dict.get(object_, "user"), user);
  if (match !== undefined && match$1 !== undefined) {
    return {
            token: match,
            user: match$1
          };
  }
  
}

function collection(json) {
  var object_ = Js_json.decodeObject(json);
  if (object_ === undefined) {
    return ;
  }
  var match = intField(object_, "id");
  var match$1 = stringField(object_, "name");
  var match$2 = stringField(object_, "role");
  if (match !== undefined && match$1 !== undefined && match$2 !== undefined) {
    return {
            id: match,
            name: match$1,
            role: match$2
          };
  }
  
}

function collections(json) {
  var items = Js_json.decodeArray(json);
  if (items !== undefined) {
    return Belt_Array.reduce(items, [], (function (decoded, item) {
                  var match = collection(item);
                  if (decoded !== undefined && match !== undefined) {
                    return Belt_Array.concat(decoded, [match]);
                  }
                  
                }));
  }
  
}

export {
  parse ,
  asObject ,
  string ,
  $$int ,
  field ,
  stringField ,
  intField ,
  user ,
  authPayload ,
  collection ,
  collections ,
}
/* No side effect */
