// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AuthApi from "./AuthApi.bs.js";
import * as Js_promise2 from "rescript/lib/es6/js_promise2.js";
import * as AuthAppSupport from "./AuthAppSupport.bs.js";
import * as SessionStorage from "./SessionStorage.bs.js";

function loadSessionToken() {
  return SessionStorage.loadSessionToken();
}

function restoreSession(sessionToken) {
  return Js_promise2.then(AuthApi.me(sessionToken), (function (response) {
                return Promise.resolve({
                            sessionToken: sessionToken,
                            user: AuthAppSupport.parseJson(response)
                          });
              }));
}

export {
  loadSessionToken ,
  restoreSession ,
}
/* AuthApi Not a pure module */
