// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";

var sessionTokenKey = "wine.sessionToken";

function loadSessionToken() {
  return Caml_option.nullable_to_opt(localStorage.getItem(sessionTokenKey));
}

function saveSessionToken(token) {
  localStorage.setItem(sessionTokenKey, token);
}

function clearSessionToken() {
  localStorage.removeItem(sessionTokenKey);
}

export {
  sessionTokenKey ,
  loadSessionToken ,
  saveSessionToken ,
  clearSessionToken ,
}
/* No side effect */
