// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ApiClient from "../api/ApiClient.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Js_promise2 from "rescript/lib/es6/js_promise2.js";
import * as CollectionApi from "../api/CollectionApi.bs.js";
import * as ResponseDecoder from "../api/ResponseDecoder.bs.js";

function updateForm(form, email) {
  return {
          email: email,
          isSubmitting: form.isSubmitting,
          error: undefined,
          success: undefined
        };
}

function startSubmitting(form) {
  return {
          email: form.email,
          isSubmitting: true,
          error: undefined,
          success: undefined
        };
}

function failForm(form, message) {
  return {
          email: form.email,
          isSubmitting: false,
          error: message,
          success: undefined
        };
}

function succeedForm(invitedMember) {
  return {
          email: "",
          isSubmitting: false,
          error: undefined,
          success: "Invited " + invitedMember.email + "."
        };
}

function invite(token, collectionId, email) {
  return Js_promise2.then(CollectionApi.inviteCollectionMember(token, collectionId, email), (function (response) {
                var invitedMember = Belt_Option.flatMap(ResponseDecoder.parse(response), ResponseDecoder.invitedCollectionMember);
                if (invitedMember !== undefined) {
                  return Promise.resolve(invitedMember);
                } else {
                  return Promise.reject(ApiClient.invalidResponse());
                }
              }));
}

var initialForm = {
  email: "",
  isSubmitting: false,
  error: undefined,
  success: undefined
};

export {
  initialForm ,
  updateForm ,
  startSubmitting ,
  failForm ,
  succeedForm ,
  invite ,
}
/* ApiClient Not a pure module */
