// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Int from "rescript/lib/es6/belt_Int.js";

var selectedCollectionIdKey = "wine.selectedCollectionId";

function loadSelectedCollectionId() {
  var value = localStorage.getItem(selectedCollectionIdKey);
  if (!(value == null)) {
    return Belt_Int.fromString(value);
  }
  
}

function saveSelectedCollectionId(collectionId) {
  localStorage.setItem(selectedCollectionIdKey, String(collectionId));
}

function clearSelectedCollectionId() {
  localStorage.removeItem(selectedCollectionIdKey);
}

export {
  selectedCollectionIdKey ,
  loadSelectedCollectionId ,
  saveSelectedCollectionId ,
  clearSelectedCollectionId ,
}
/* No side effect */
