import { test, expect } from "playwright/test"

test("users can create an entry and see it in history", async ({ page }) => {
  const stamp = Date.now()
  const email = `entry-${stamp}@example.com`
  const collectionName = `Cellar ${stamp}`

  await page.goto("/")
  await expect(page.getByRole("heading", { name: "Welcome back" })).toBeVisible()
  await page.getByRole("button", { name: "Sign up" }).click()
  await page.getByLabel("Full name").fill("Entry User")
  await page.getByLabel("Email").fill(email)
  await page.getByLabel("Password").fill("password123")
  await page.getByRole("button", { name: "Create account" }).click()

  await expect(page.getByText(`Signed in as ${email}.`)).toBeVisible()
  await page.getByLabel("New collection").fill(collectionName)
  await page.getByRole("button", { name: "Create collection" }).click()
  await expect(page.getByRole("heading", { name: collectionName })).toBeVisible()

  await page.getByRole("button", { name: "Add wine" }).click()
  await page.getByLabel("Wine name").fill("Tondonia")
  await page.getByLabel("Producer").fill("Lopez de Heredia")
  await page.getByLabel("Style").fill("Red")
  await page.getByLabel("Grape").fill("Tempranillo")
  await page.getByLabel("Region").fill("Rioja")
  await page.getByLabel("Country").fill("Spain")
  await page.getByLabel("Vintage").fill("2011")
  await page.getByRole("button", { name: "Save wine" }).click()

  await expect(page.getByRole("heading", { name: "Lopez de Heredia Tondonia", exact: true })).toBeVisible()
  await expect(page.getByText("Tempranillo · 2011 · 0 entries")).toBeVisible()
  await expect(page.getByText("No occasions recorded yet for Lopez de Heredia Tondonia.")).toBeVisible()

  await page.getByRole("button", { name: "Add entry" }).click()
  await expect(page.getByLabel("Wine name")).toHaveValue("Tondonia")
  await expect(page.getByLabel("Producer")).toHaveValue("Lopez de Heredia")
  await expect(page.getByLabel("Grape")).toHaveValue("Tempranillo")
  await page.getByRole("button", { name: "Close" }).click()

  await page.getByRole("button", { name: "Add entry" }).click()
  await page.getByLabel("Wine name").fill("Taganan")
  await page.getByLabel("Producer").fill("Envinate")
  await page.getByLabel("Style").fill("Red")
  await page.getByLabel("Grape").fill("Listan Negro")
  await page.getByLabel("Region").fill("Canary Islands")
  await page.getByLabel("Country").fill("Spain")
  await page.getByLabel("Vintage").fill("2022")
  await page.getByLabel("Consumed at").fill("2025-01-15T19:30")
  await page.getByLabel("Venue").fill("Home")
  await page.getByLabel("Location").fill("Stockholm")
  await page.getByLabel("Pairing notes").fill("Roast chicken")
  await page.getByLabel("Tasting notes").fill("Salty and bright")
  await page.getByLabel("Rating").fill("4")
  await page.getByRole("button", { name: "Save entry" }).click()

  await page.getByRole("button", { name: "Add entry" }).click()
  await page.getByLabel("Wine name").fill("SP68")
  await page.getByLabel("Producer").fill("Occhipinti")
  await page.getByLabel("Style").fill("Red")
  await page.getByLabel("Grape").fill("Frappato")
  await page.getByLabel("Region").fill("Sicily")
  await page.getByLabel("Country").fill("Italy")
  await page.getByLabel("Vintage").fill("2023")
  await page.getByLabel("Consumed at").fill("2025-02-02T20:15")
  await page.getByLabel("Venue").fill("Bar Central")
  await page.getByLabel("Location").fill("Rome")
  await page.getByLabel("Tasting notes").fill("Juicy and herbal")
  await page.getByLabel("Rating").fill("3")
  await page.getByRole("button", { name: "Save entry" }).click()

  await expect(page.getByRole("button", { name: "Add entry" })).toBeVisible()
  await expect(page.getByRole("heading", { name: "Wines" })).toBeVisible()
  await expect(page.getByRole("heading", { name: "Occhipinti SP68", exact: true })).toBeVisible()
  await page.getByLabel("Search wines").fill("taga")
  await expect(page.getByText("1 of 3 wines")).toBeVisible()
  await expect(page.getByRole("heading", { name: "Envinate Taganan", exact: true })).toBeVisible()
  await expect(page.getByText("Listan Negro · 2022 · 1 entries")).toBeVisible()
  await expect(page.getByRole("definition").filter({ hasText: "Red" }).first()).toBeVisible()
  await expect(page.getByRole("definition").filter({ hasText: "Canary Islands" }).first()).toBeVisible()
  await expect(page.getByRole("definition").filter({ hasText: "Spain" }).first()).toBeVisible()
  await expect(page.getByText("2022 · Stockholm · Home")).toBeVisible()
  await expect(page.getByText("Envinate · Taganan · 2022")).toBeVisible()
  await expect(page.getByRole("definition").filter({ hasText: "Salty and bright" })).toBeVisible()
  await expect(page.getByRole("definition").filter({ hasText: "Roast chicken" })).toBeVisible()
  await expect(page.getByText("Rating 4/5")).toBeVisible()

  await page.getByRole("button", { name: "Edit entry" }).click()
  await expect(page.getByRole("heading", { name: "Update this memory" })).toBeVisible()
  await page.getByLabel("Venue").fill("Corner Bistro")
  await page.getByLabel("Location").fill("Copenhagen")
  await page.getByLabel("Tasting notes").fill("More floral on the second glass")
  await page.getByLabel("Rating").fill("5")
  await page.getByRole("button", { name: "Save changes" }).click()

  await expect(page.getByRole("button", { name: "Add entry" })).toBeVisible()
  await expect(page.getByText("2022 · Copenhagen · Corner Bistro")).toBeVisible()
  await expect(page.getByRole("definition").filter({ hasText: "More floral on the second glass" })).toBeVisible()
  await expect(page.getByText("Rating 5/5")).toBeVisible()

  await page.reload()
  await page.getByLabel("Search wines").fill("taga")
  await expect(page.getByRole("heading", { name: "Envinate Taganan", exact: true })).toBeVisible()
  await expect(page.getByText("Envinate · Taganan · 2022")).toBeVisible()
  await expect(page.getByText("Rating 5/5")).toBeVisible()
})
