// Generated by ReScript, PLEASE EDIT WITH CARE


function toCode(locale) {
  if (locale === "En") {
    return "en";
  } else {
    return "sv";
  }
}

function fromCode(code) {
  switch (code) {
    case "en" :
        return "En";
    case "sv" :
        return "Sv";
    default:
      return ;
  }
}

export {
  toCode ,
  fromCode ,
}
/* No side effect */
