// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Translations from "./Translations.bs.js";

function defaultContext_setOverride(param) {
  
}

var defaultContext = {
  locale: "En",
  override: undefined,
  setOverride: defaultContext_setOverride
};

var context = React.createContext(defaultContext);

var make = context.Provider;

var Provider = {
  make: make
};

function useContext() {
  return React.useContext(context);
}

function useLocale() {
  return React.useContext(context).locale;
}

function useT() {
  return Translations.pick(React.useContext(context).locale);
}

function useOverride() {
  return React.useContext(context).override;
}

function useSetOverride() {
  return React.useContext(context).setOverride;
}

export {
  defaultContext ,
  context ,
  Provider ,
  useContext ,
  useLocale ,
  useT ,
  useOverride ,
  useSetOverride ,
}
/* context Not a pure module */
