// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AppLocale from "./AppLocale.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function resolve(navigatorLanguage, override) {
  var locale = Belt_Option.flatMap(override, AppLocale.fromCode);
  if (locale !== undefined) {
    return locale;
  } else if (navigatorLanguage !== undefined && navigatorLanguage.toLowerCase().startsWith("sv")) {
    return "Sv";
  } else {
    return "En";
  }
}

export {
  resolve ,
}
/* No side effect */
