// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AppLocale from "./AppLocale.bs.js";

var storageKey = "locale";

function loadOverride() {
  var value = globalThis.window.localStorage.getItem(storageKey);
  if (!(value == null)) {
    return AppLocale.fromCode(value);
  }
  
}

function saveOverride(locale) {
  globalThis.window.localStorage.setItem(storageKey, AppLocale.toCode(locale));
}

function clearOverride() {
  globalThis.window.localStorage.removeItem(storageKey);
}

export {
  storageKey ,
  loadOverride ,
  saveOverride ,
  clearOverride ,
}
/* No side effect */
