// Generated by ReScript, PLEASE EDIT WITH CARE


function en_appLanguageDetectedLabel(locale) {
  if (locale === "En") {
    return "Detected: English";
  } else {
    return "Detected: Swedish";
  }
}

function en_occasionsForWine(wineLabel) {
  return "Occasions for " + wineLabel;
}

function en_loadingOccasionsFor(wineLabel) {
  return "Loading occasions for " + wineLabel + "...";
}

function en_noOccasionsFor(wineLabel) {
  return "No occasions recorded yet for " + wineLabel + ".";
}

function en_occasionCount(n) {
  if (n !== 1) {
    return String(n) + " occasions";
  } else {
    return "1 occasion";
  }
}

function en_entryCount(n) {
  if (n !== 1) {
    return String(n) + " entries";
  } else {
    return "1 entry";
  }
}

function en_rating(n) {
  return "Rating " + String(n) + "/5";
}

function en_filteredOf(visible, total) {
  return String(visible) + " of " + String(total) + " wines";
}

var en_errors = {
  authEmailTaken: "That email address is already registered.",
  authInvalidEmail: "Enter a valid email address.",
  authPasswordTooShort: "Use a password with at least 8 characters.",
  authInvalidCredentials: "The email or password was not accepted.",
  authGeneric: "Something went wrong. Try again.",
  entryInvalidConsumedAt: "Enter when you drank the wine.",
  entryInvalidRating: "Rating must be a whole number from 1 to 5.",
  entryInvalidWineName: "Enter a wine name.",
  entryInvalidWineVintage: "Vintage must be a year between 1900 and 2100.",
  entryForbidden: "You no longer have access to this collection.",
  entryGeneric: "Could not save the entry. Try again.",
  entryHistoryGeneric: "Could not load your wines. Try refreshing.",
  wineInvalidName: "Enter a wine name.",
  wineInvalidVintage: "Vintage must be a year between 1900 and 2100.",
  wineForbidden: "You no longer have access to this collection.",
  wineGeneric: "Could not save the wine. Try again."
};

var en = {
  appWines: "Wines",
  appSearchAriaOpen: "Search wines",
  appSearchAriaClose: "Close search",
  appFilterAriaOpen: "Filter wines",
  appFilterAriaClose: "Close filter",
  appMenuAriaOpen: "Open menu",
  appAddWineAriaLabel: "Add wine",
  appSignedIn: "Signed in",
  appLogOut: "Log out",
  appLanguage: "Language",
  appLanguageSwedishLabel: "Svenska",
  appLanguageEnglishLabel: "English",
  appLanguageBrowserDefault: "Use browser language",
  appLanguageDetectedLabel: en_appLanguageDetectedLabel,
  appCheckingSession: "Checking your session...",
  filterAllWines: "All wines",
  filterWithOccasions: "With occasions",
  filterWithoutOccasions: "No occasions yet",
  authBrand: "Wine",
  authWelcomeBack: "Welcome back",
  authCreateYourAccount: "Create your account",
  authLoginIntro: "Sign in to continue to your wine journal.",
  authRegisterIntro: "Start your wine journal with a personal account.",
  authLogIn: "Log in",
  authSignUp: "Sign up",
  authCreateAccount: "Create account",
  authWorking: "Working...",
  authFullName: "Full name",
  authEmail: "Email",
  authPassword: "Password",
  wineListEmptyTitle: "No wines yet",
  wineListEmptyBody: "Add your first bottle. You can record an occasion afterward.",
  wineListLoading: "Loading your wines...",
  wineListErrorTitle: "Wines",
  wineDetailBackAriaLabel: "Back to wines",
  wineDetailDefaultTitle: "Wine",
  wineDetailAddOccasion: "+ Add occasion",
  wineDetailIdentity: "Identity",
  wineDetailMemory: "Memory",
  wineDetailMostRecent: "Most recent",
  wineDetailNameLabel: "Name",
  wineDetailEmptyOccasions: "No occasions recorded yet.",
  wineDetailOccasionsLabel: "Occasions",
  wineComposerScreenTitle: "New wine",
  wineComposerCancelAriaLabel: "Cancel",
  wineComposerHelpText: "Add a bottle you want to remember now, then attach occasions later when they happen.",
  wineComposerSaveLabel: "Save wine",
  wineComposerSavingLabel: "Saving...",
  wineComposerWineNameLabel: "Wine name",
  wineComposerProducerLabel: "Producer",
  wineComposerStyleLabel: "Style",
  wineComposerGrapeLabel: "Grape",
  wineComposerRegionLabel: "Region",
  wineComposerCountryLabel: "Country",
  wineComposerVintageLabel: "Vintage",
  entryComposerNewTitle: "New occasion",
  entryComposerEditTitle: "Edit occasion",
  entryComposerCancelAriaLabel: "Cancel",
  entryComposerSelectedWine: "Selected wine",
  entryComposerDifferentWine: "Different wine",
  entryComposerUsing: "Using",
  entryComposerSaveCreate: "Save entry",
  entryComposerSaveEdit: "Save changes",
  entryComposerSavingLabel: "Saving...",
  entryComposerConsumedAtLabel: "Consumed at",
  entryComposerVenueLabel: "Venue",
  entryComposerLocationLabel: "Location",
  entryComposerPairingNotesLabel: "Pairing notes",
  entryComposerTastingNotesLabel: "Tasting notes",
  entryComposerRatingLabel: "Rating",
  entryDetailHeading: "Entry detail",
  entryDetailEmptyBody: "Select an entry from history to inspect the wine and occasion details.",
  entryDetailWineLabel: "Wine",
  entryDetailOccasionLabel: "Occasion",
  entryDetailEditEntry: "Edit entry",
  entryHistoryEmptyMessage: "No occasions recorded yet.",
  entryHistoryPairingPrefix: "Pairing: ",
  occasionsForWine: en_occasionsForWine,
  loadingOccasionsFor: en_loadingOccasionsFor,
  noOccasionsFor: en_noOccasionsFor,
  occasionCount: en_occasionCount,
  entryCount: en_entryCount,
  rating: en_rating,
  filteredOf: en_filteredOf,
  errors: en_errors
};

function sv_appLanguageDetectedLabel(locale) {
  if (locale === "En") {
    return "Upptäckt: Engelska";
  } else {
    return "Upptäckt: Svenska";
  }
}

function sv_occasionsForWine(wineLabel) {
  return "Tillfällen för " + wineLabel;
}

function sv_loadingOccasionsFor(wineLabel) {
  return "Hämtar tillfällen för " + wineLabel + "...";
}

function sv_noOccasionsFor(wineLabel) {
  return "Inga tillfällen registrerade än för " + wineLabel + ".";
}

function sv_occasionCount(n) {
  if (n !== 1) {
    return String(n) + " tillfällen";
  } else {
    return "1 tillfälle";
  }
}

function sv_entryCount(n) {
  if (n !== 1) {
    return String(n) + " anteckningar";
  } else {
    return "1 anteckning";
  }
}

function sv_rating(n) {
  return "Betyg " + String(n) + "/5";
}

function sv_filteredOf(visible, total) {
  return String(visible) + " av " + String(total) + " viner";
}

var sv_errors = {
  authEmailTaken: "E-postadressen är redan registrerad.",
  authInvalidEmail: "Ange en giltig e-postadress.",
  authPasswordTooShort: "Använd ett lösenord med minst 8 tecken.",
  authInvalidCredentials: "E-postadressen eller lösenordet godtogs inte.",
  authGeneric: "Något gick fel. Försök igen.",
  entryInvalidConsumedAt: "Ange när du drack vinet.",
  entryInvalidRating: "Betyget måste vara ett heltal från 1 till 5.",
  entryInvalidWineName: "Ange ett vinnamn.",
  entryInvalidWineVintage: "Årgången måste vara mellan 1900 och 2100.",
  entryForbidden: "Du har inte längre åtkomst till den här samlingen.",
  entryGeneric: "Det gick inte att spara tillfället. Försök igen.",
  entryHistoryGeneric: "Det gick inte att hämta dina viner. Försök igen.",
  wineInvalidName: "Ange ett vinnamn.",
  wineInvalidVintage: "Årgången måste vara mellan 1900 och 2100.",
  wineForbidden: "Du har inte längre åtkomst till den här samlingen.",
  wineGeneric: "Det gick inte att spara vinet. Försök igen."
};

var sv = {
  appWines: "Viner",
  appSearchAriaOpen: "Sök viner",
  appSearchAriaClose: "Stäng sökning",
  appFilterAriaOpen: "Filtrera viner",
  appFilterAriaClose: "Stäng filter",
  appMenuAriaOpen: "Öppna meny",
  appAddWineAriaLabel: "Lägg till vin",
  appSignedIn: "Inloggad",
  appLogOut: "Logga ut",
  appLanguage: "Språk",
  appLanguageSwedishLabel: "Svenska",
  appLanguageEnglishLabel: "English",
  appLanguageBrowserDefault: "Använd webbläsarens språk",
  appLanguageDetectedLabel: sv_appLanguageDetectedLabel,
  appCheckingSession: "Kontrollerar din session...",
  filterAllWines: "Alla viner",
  filterWithOccasions: "Med tillfällen",
  filterWithoutOccasions: "Inga tillfällen än",
  authBrand: "Wine",
  authWelcomeBack: "Välkommen tillbaka",
  authCreateYourAccount: "Skapa ditt konto",
  authLoginIntro: "Logga in för att fortsätta till din vindagbok.",
  authRegisterIntro: "Starta din vindagbok med ett personligt konto.",
  authLogIn: "Logga in",
  authSignUp: "Registrera",
  authCreateAccount: "Skapa konto",
  authWorking: "Arbetar...",
  authFullName: "Fullständigt namn",
  authEmail: "E-post",
  authPassword: "Lösenord",
  wineListEmptyTitle: "Inga viner än",
  wineListEmptyBody: "Lägg till din första flaska. Du kan registrera ett tillfälle efteråt.",
  wineListLoading: "Hämtar dina viner...",
  wineListErrorTitle: "Viner",
  wineDetailBackAriaLabel: "Tillbaka till viner",
  wineDetailDefaultTitle: "Vin",
  wineDetailAddOccasion: "+ Nytt tillfälle",
  wineDetailIdentity: "Identitet",
  wineDetailMemory: "Minne",
  wineDetailMostRecent: "Senaste",
  wineDetailNameLabel: "Namn",
  wineDetailEmptyOccasions: "Inga tillfällen registrerade än.",
  wineDetailOccasionsLabel: "Tillfällen",
  wineComposerScreenTitle: "Nytt vin",
  wineComposerCancelAriaLabel: "Avbryt",
  wineComposerHelpText: "Lägg till en flaska du vill minnas nu, koppla tillfällen senare när de inträffar.",
  wineComposerSaveLabel: "Spara vin",
  wineComposerSavingLabel: "Sparar...",
  wineComposerWineNameLabel: "Vinets namn",
  wineComposerProducerLabel: "Producent",
  wineComposerStyleLabel: "Stil",
  wineComposerGrapeLabel: "Druva",
  wineComposerRegionLabel: "Region",
  wineComposerCountryLabel: "Land",
  wineComposerVintageLabel: "Årgång",
  entryComposerNewTitle: "Nytt tillfälle",
  entryComposerEditTitle: "Redigera tillfälle",
  entryComposerCancelAriaLabel: "Avbryt",
  entryComposerSelectedWine: "Valt vin",
  entryComposerDifferentWine: "Annat vin",
  entryComposerUsing: "Använder",
  entryComposerSaveCreate: "Spara tillfälle",
  entryComposerSaveEdit: "Spara ändringar",
  entryComposerSavingLabel: "Sparar...",
  entryComposerConsumedAtLabel: "Drucket",
  entryComposerVenueLabel: "Plats",
  entryComposerLocationLabel: "Adress",
  entryComposerPairingNotesLabel: "Matanteckningar",
  entryComposerTastingNotesLabel: "Smakanteckningar",
  entryComposerRatingLabel: "Betyg",
  entryDetailHeading: "Tillfälle",
  entryDetailEmptyBody: "Välj ett tillfälle från historiken för att se vinet och tillfällets detaljer.",
  entryDetailWineLabel: "Vin",
  entryDetailOccasionLabel: "Tillfälle",
  entryDetailEditEntry: "Redigera tillfälle",
  entryHistoryEmptyMessage: "Inga tillfällen registrerade än.",
  entryHistoryPairingPrefix: "Mat: ",
  occasionsForWine: sv_occasionsForWine,
  loadingOccasionsFor: sv_loadingOccasionsFor,
  noOccasionsFor: sv_noOccasionsFor,
  occasionCount: sv_occasionCount,
  entryCount: sv_entryCount,
  rating: sv_rating,
  filteredOf: sv_filteredOf,
  errors: sv_errors
};

function pick(locale) {
  if (locale === "En") {
    return en;
  } else {
    return sv;
  }
}

export {
  en ,
  sv ,
  pick ,
}
/* No side effect */
